#/******************************************************************************
#* Copyright (c) 2011  Marvell International, Ltd. All Rights Reserved
#*
#*                         Marvell Confidential
#******************************************************************************/

#Include master environment
include $(BUILD_ROOT)/project.mk

INCFLAGS = -I./src -I$(BUILD_ROOT)/$(GLOBAL_INCLUDE)
SOURCE = cmd_parser.c

include $(BUILD_ROOT)/stdtargets.mk
