/*
 *  $RCSfile: t35_cty.h,v $
 * $Revision: 1.3 $
 *   $Author: miurat $
 *     $Date: 2009/11/11 22:20:28 $
 */
/*****************************************************************
***               Copyright (c) 1994 - 2009                    ***
***               Conexant Systems Inc.                        ***
***               Imaging and PC Media                         ***
***               All Rights Reserved                          ***
***                                                            ***
***            CONFIDENTIAL -- No Dissemination or             ***
***            use without prior written permission.           ***
***                                                            ***
******************************************************************
*                                                                *
*  2004 - 2006 Major modification for Embedded T.32 with V.34    *
*  2008 - 2009 Modification for SSF336                           *
*                                                                *
******************************************************************/

#ifndef _T35_CTY_H
#define _T35_CTY_H

#define T35_JAPAN                                 (0x00)
#define T35_ALBANIA                               (0x01)
#define T35_ALGERIA                               (0x02)
#define T35_AMERICAN_SAMOA                        (0x03)
#define T35_GERMANY                               (0x04)
#define T35_ANGUILLA                              (0x05)
#define T35_ANTIGUA_AND_BARBUDA                   (0x06)
#define T35_ARGENTINA                             (0x07)
#define T35_ASCENSION                             (0x08)
#define T35_AUSTRALIA                             (0x09)
#define T35_AUSTRIA                               (0x0A)
#define T35_BAHAMAS                               (0x0B)
#define T35_BAHRAIN                               (0x0C)
#define T35_BANGLADESH                            (0x0D)
#define T35_BARBADOS                              (0x0E)
#define T35_BELGIUM                               (0x0F)

#define T35_BELIZE                                (0x10)
#define T35_BENIN                                 (0x11)
#define T35_BERMUDA                               (0x12)
#define T35_BHUTAN                                (0x13)
#define T35_BOLIVIA                               (0x14)
#define T35_BOTSWANA                              (0x15)
#define T35_BRAZIL                                (0x16)
#define T35_BRITISH_ANTARCTIC_TERRITORY           (0x17)
#define T35_BRITISH_INDIAN_OCEAN_TERRITORY        (0x18)
#define T35_BRITISH_VIRGIN_ISLANDS                (0x19)
#define T35_BRUNEI_DARUSSALAM                     (0x1A)
#define T35_BULGARIA                              (0x1B)
#define T35_MYANMAR                               (0x1C)
#define T35_BURUNDI                               (0x1D)
#define T35_BELARUS                               (0x1E)
#define T35_CAMEROON                              (0x1F)

#define T35_CANADA                                (0x20)
#define T35_CAPE_VERDE                            (0x21)
#define T35_CAYMAN_ISLANDS                        (0x22)
#define T35_CENTRAL_AFRICAN_REPUBLIC              (0x23)
#define T35_CHAD                                  (0x24)
#define T35_CHILE                                 (0x25)
#define T35_CHINA                                 (0x26)
#define T35_COLOMBIA                              (0x27)
#define T35_COMOROS                               (0x28)
#define T35_CONGO                                 (0x29)
#define T35_COOK_ISLANDS                          (0x2A)
#define T35_COSTA_RICA                            (0x2B)
#define T35_CUBA                                  (0x2C)
#define T35_CYPRUS                                (0x2D)
#define T35_CZECH_REPUBLIC                        (0x2E)
#define T35_CAMBODIA                              (0x2F)

#define T35_DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA  (0x30)
#define T35_DENMARK                               (0x31)
#define T35_DJIBOUTI                              (0x32)
#define T35_DOMINICAN_REPUBLIC                    (0x33)
#define T35_DOMINICA                              (0x34)
#define T35_ECUADOR                               (0x35)
#define T35_EGYPT                                 (0x36)
#define T35_EL_SALVADOR                           (0x37)
#define T35_EQUATORIAL_GUINEA                     (0x38)
#define T35_ETHIOPIA                              (0x39)
#define T35_FALKLAND_ISLANDS                      (0x3A)
#define T35_FIJI                                  (0x3B)
#define T35_FINLAND                               (0x3C)
#define T35_FRANCE                                (0x3D)
#define T35_FRENCH_POLYNESIA                      (0x3E)
//#define T35_                                      (0x3F)

#define T35_GABON                                 (0x40)
#define T35_GAMBIA                                (0x41)
#define T35_GERMANY_42                            (0x42)
#define T35_ANGOLA                                (0x43)
#define T35_GHANA                                 (0x44)
#define T35_GIBRALTAR                             (0x45)
#define T35_GREECE                                (0x46)
#define T35_GRENADA                               (0x47)
#define T35_GUAM                                  (0x48)
#define T35_GUATEMALA                             (0x49)
#define T35_GUERNSEY                              (0x4A)
#define T35_GUINEA                                (0x4B)
#define T35_GUINEA_BISSAU                         (0x4C)
#define T35_GUAYANA                               (0x4D)
#define T35_HAITI                                 (0x4E)
#define T35_HONDURAS                              (0x4F)

#define T35_HONGKONG                              (0x50)
#define T35_HUNGARY                               (0x51)
#define T35_ICELAND                               (0x52)
#define T35_INDIA                                 (0x53)
#define T35_INDONESIA                             (0x54)
#define T35_IRAN                                  (0x55)
#define T35_IRAQ                                  (0x56)
#define T35_IRELAND                               (0x57)
#define T35_ISRAEL                                (0x58)
#define T35_ITALY                                 (0x59)
#define T35_COTE_DIVOIRE                          (0x5A)
#define T35_JAMAICA                               (0x5B)
#define T35_AFGHANISTAN                           (0x5C)
#define T35_JERSEY                                (0x5D)
#define T35_JORDAN                                (0x5E)
#define T35_KENYA                                 (0x5F)

#define T35_KIRIBATI                              (0x60)
#define T35_KOREA                                 (0x61)
#define T35_KUWAIT                                (0x62)
#define T35_LAO_PEOPLES_DEMOCRATIC_REPUBLIC       (0x63)
#define T35_LEBANON                               (0x64)
#define T35_LESOTHO                               (0x65)
#define T35_LIBERIA                               (0x66)
#define T35_LIBYAN_ARAB_JAMAHIRIYA                (0x67)
#define T35_LIECHTENSTEIN                         (0x68)
#define T35_LUXEMBOURG                            (0x69)
#define T35_MACAO                                 (0x6A)
#define T35_MADAGASCAR                            (0x6B)
#define T35_MALAYSIA                              (0x6C)
#define T35_MALAWI                                (0x6D)
#define T35_MALDIVES                              (0x6E)
#define T35_MALI                                  (0x6F)

#define T35_MALTA                                 (0x70)
#define T35_MAURITANIA                            (0x71)
#define T35_MAURITIUS                             (0x72)
#define T35_MEXICO                                (0x73)
#define T35_MONACO                                (0x74)
#define T35_MONGOLIA                              (0x75)
#define T35_MONTSERRAT                            (0x76)
#define T35_MOROCCO                               (0x77)
#define T35_MOZAMBIQUE                            (0x78)
#define T35_NAURU                                 (0x79)
#define T35_NEPAL                                 (0x7A)
#define T35_NETHERLANDS                           (0x7B)
#define T35_NETHERLANDS_ANTILLES                  (0x7C)
#define T35_NEW_CALEDONIA                         (0x7D)
#define T35_NEW_ZEALAND                           (0x7E)
#define T35_NICARAGUA                             (0x7F)

#define T35_NIGER                                 (0x80)
#define T35_NIGERIA                               (0x81)
#define T35_NORWAY                                (0x82)
#define T35_OMAN                                  (0x83)
#define T35_PAKISTAN                              (0x84)
#define T35_PANAMA                                (0x85)
#define T35_PAPUA_NEW_GUINEA                      (0x86)
#define T35_PARAGUAY                              (0x87)
#define T35_PERU                                  (0x88)
#define T35_PHILIPPINES                           (0x89)
#define T35_POLAND                                (0x8A)
#define T35_PORTUGAL                              (0x8B)
#define T35_PUERTO_RICO                           (0x8C)
#define T35_QATAR                                 (0x8D)
#define T35_ROMANIA                               (0x8E)
#define T35_RWANDA                                (0x8F)

#define T35_SAINT_KITTS_AND_NEVIS                 (0x90)
#define T35_SAINT_CROIX                           (0x91)
#define T35_SAINT_HELENA_AND_ASCENSION            (0x92)
#define T35_SAINT_LUCIA                           (0x93)
#define T35_SAN_MARINO                            (0x94)
#define T35_SAINT_THOMAS                          (0x95)
#define T35_SAO_TOME_AND_PRINCIPE                 (0x96)
#define T35_SAINT_VINCENT_AND_THE_GRENADINES      (0x97)
#define T35_SAUDI_ARABIA                          (0x98)
#define T35_SENEGAL                               (0x99)
#define T35_SEYCHELLES                            (0x9A)
#define T35_SIERRA_LEONE                          (0x9B)
#define T35_SINGAPORE                             (0x9C)
#define T35_SOLOMON_ISLANDS                       (0x9D)
#define T35_SOMALIA                               (0x9E)
#define T35_SOUTH_AFRICA                          (0x9F)

#define T35_SPAIN                                 (0xA0)
#define T35_SRI_LANKA                             (0xA1)
#define T35_SUDAN                                 (0xA2)
#define T35_SURINAME                              (0xA3)
#define T35_SWAZILAND                             (0xA4)
#define T35_SWEDEN                                (0xA5)
#define T35_SWITZERLAND                           (0xA6)
#define T35_SYRIAN_ARAB_REPUBLIC                  (0xA7)
#define T35_TANZANIA                              (0xA8)
#define T35_THAILAND                              (0xA9)
#define T35_TOGO                                  (0xAA)
#define T35_TONGA                                 (0xAB)
#define T35_TRINIDAD_AND_TOBAGO                   (0xAC)
#define T35_TUNISIA                               (0xAD)
#define T35_TURKEY                                (0xAE)
#define T35_TURKS_AND_CAICOS_ISLANDS              (0xAF)

#define T35_TUVALU                                (0xB0)
#define T35_UGANDA                                (0xB1)
#define T35_UKRAINE                               (0xB2)
#define T35_UNITED_ARAB_EMIRATES                  (0xB3)
#define T35_UNITED_KINGDOM                        (0xB4)
#define T35_UNITED_STATES                         (0xB5)
#define T35_BURKINA_FASO                          (0xB6)
#define T35_URUGUAY                               (0xB7)
#define T35_RUSSIAN_FEDERATION                    (0xB8)
#define T35_VANUATU                               (0xB9)
#define T35_VATICAN                               (0xBA)
#define T35_VENEZUELA                             (0xBB)
#define T35_VIET_NAM                              (0xBC)
#define T35_WALLIS_AND_FUTUNA                     (0xBD)
#define T35_SAMOA                                 (0xBE)
#define T35_YEMEN_BF                              (0xBF)

#define T35_YEMEN_C0                              (0xC0)
#define T35_SERBIA                                (0xC1)
#define T35_DEMOCRATIC_REPUBLIC_OF_THE_CONGO      (0xC2)
#define T35_ZAMBIA                                (0xC3)
#define T35_ZIMBABWE                              (0xC4)
#define T35_SLOVAKIA                              (0xC5)
#define T35_SLOVENIA                              (0xC6)
#define T35_LITHUANIA                             (0xC7)
//#define T35_MONTENEGRO                            (0xC8)
#define T35_AZERBAIJAN                            (0xC8)
#define T35_KAZAKHSTAN					 		  (0xD2)
#define T35_BOSNIA_HERZEGOVINA					  (0xE5)

	/* undefined code by ITU-T */
#define T35_LATVIA                                (0xF8)
#define T35_ESTONIA                               (0xF9)
#define T35_US_VIRGIN_ISLAND                      (0xFA)
#define T35_TAIWAN_REPUBLIC_OF_CHINA              (0xFE)

#endif //_T35_CTY_H

