# ============================================================================
# Copyright (c) 2011 Marvell Semiconductor, Inc. All Rights Reserved
#                      
#                         Marvell Confidential
# ============================================================================

#Include master environment
BUILD_ROOT = ../../../..
include $(BUILD_ROOT)/project.mk

INSTALL_SRC_DIR = include

INSTALL_SRC = regAddrs.h
INSTALL_SRC += intnums.h
INSTALL_SRC += ADCNorm_regmasks.h ADCNorm_regstructs.h
INSTALL_SRC += adc_regmasks.h adc_regstructs.h
INSTALL_SRC += antic_top_regmasks.h antic_top_regstructs.h
INSTALL_SRC += apb_config_regmasks.h apb_config_regstructs.h
INSTALL_SRC += apb_ddac_regmasks.h apb_ddac_regstructs.h
INSTALL_SRC += APB2_cfg_regmasks.h APB2_cfg_regstructs.h
INSTALL_SRC += asela_regmasks.h asela_regstructs.h
INSTALL_SRC += AUTO_HT_regmasks.h AUTO_HT_regstructs.h
INSTALL_SRC += BDEnhance_regmasks.h BDEnhance_regstructs.h
INSTALL_SRC += BitReduct_regmasks.h BitReduct_regstructs.h
INSTALL_SRC += BLOOM_regmasks.h BLOOM_regstructs.h
INSTALL_SRC += BMLR_regmasks.h BMLR_regstructs.h
INSTALL_SRC += BOOTSPI_regmasks.h BOOTSPI_regstructs.h
INSTALL_SRC += BUS_regmasks.h BUS_regstructs.h
INSTALL_SRC += CBI2CDMA_regmasks.h CBI2CDMA_regstructs.h
INSTALL_SRC += cdma_peripheral_ids.h
INSTALL_SRC += CDMA_regmasks.h CDMA_regstructs.h
INSTALL_SRC += CDMA_Top_Int_regmasks.h CDMA_Top_Int_regstructs.h
INSTALL_SRC += CDMA_Top_regmasks.h CDMA_Top_regstructs.h
INSTALL_SRC += CHG_OWI_regmasks.h CHG_OWI_regstructs.h
INSTALL_SRC += CISX_IDMA_AXI_regmasks.h CISX_IDMA_AXI_regstructs.h
INSTALL_SRC += CISX_int_regmasks.h CISX_int_regstructs.h
INSTALL_SRC += CISX_ODMA_AXI_regmasks.h CISX_ODMA_AXI_regstructs.h
INSTALL_SRC += COLOR_SHIFT_regmasks.h COLOR_SHIFT_regstructs.h
INSTALL_SRC += CREG_regmasks.h CREG_regstructs.h
INSTALL_SRC += CRE_regmasks.h CRE_regstructs.h
INSTALL_SRC += CR_regmasks.h CR_regstructs.h
INSTALL_SRC += CSC_DAVINCI_regmasks.h CSC_DAVINCI_regstructs.h
INSTALL_SRC += CSC_ES2Y_regmasks.h CSC_ES2Y_regstructs.h
INSTALL_SRC += CSC_RGB2ES_3L_regmasks.h CSC_RGB2ES_3L_regstructs.h
INSTALL_SRC += CSC_Y2ES_regmasks.h CSC_Y2ES_regstructs.h
INSTALL_SRC += CSSCG_regmasks.h CSSCG_regstructs.h
INSTALL_SRC += CStats_regmasks.h CStats_regstructs.h
INSTALL_SRC += DavBuff_regmasks.h DavBuff_regstructs.h
INSTALL_SRC += DCMotor_BASE_regmasks.h DCMotor_BASE_regstructs.h
INSTALL_SRC += DCMotor_S2_regmasks.h DCMotor_S2_regstructs.h
INSTALL_SRC += DEC_CONFIG_regmasks.h DEC_CONFIG_regstructs.h
INSTALL_SRC += DNAND_regmasks.h DNAND_regstructs.h
INSTALL_SRC += DPWM_regmasks.h DPWM_regstructs.h
INSTALL_SRC += dro_regmasks.h dro_regstructs.h
INSTALL_SRC += efuse_regmasks.h efuse_regstructs.h
INSTALL_SRC += engctl_regmasks.h engctl_regstructs.h
INSTALL_SRC += EXP_regmasks.h EXP_regstructs.h
INSTALL_SRC += FHS_regmasks.h FHS_regstructs.h
INSTALL_SRC += fuser_regmasks.h fuser_regstructs.h
INSTALL_SRC += GALVO_regmasks.h GALVO_regstructs.h
INSTALL_SRC += gic_regstructs.h
INSTALL_SRC += GPIO_regmasks.h GPIO_regstructs.h
INSTALL_SRC += HFIR_regmasks.h HFIR_regstructs.h
INSTALL_SRC += HiPS_regmasks.h HiPS_regstructs.h
INSTALL_SRC += HiPWM_regmasks.h HiPWM_regstructs.h
INSTALL_SRC += HScale_regmasks.h HScale_regstructs.h
INSTALL_SRC += HVSync_regmasks.h HVSync_regstructs.h
INSTALL_SRC += I2C_regmasks.h I2C_regstructs.h
INSTALL_SRC += I2S_regmasks.h I2S_regstructs.h
INSTALL_SRC += ICE_test_regmasks.h ICE_test_regstructs.h
INSTALL_SRC += IDMA_2D_regmasks.h IDMA_2D_regstructs.h
INSTALL_SRC += idma_regmasks.h idma_regstructs.h
INSTALL_SRC += ieee1284c_regmasks.h ieee1284c_regstructs.h
INSTALL_SRC += istone_regmasks.h istone_regstructs.h
INSTALL_SRC += JBIG_regmasks.h JBIG_regstructs.h
INSTALL_SRC += JEDI_regmasks.h JEDI_regstructs.h
INSTALL_SRC += KMOD_regmasks.h KMOD_regstructs.h
INSTALL_SRC += l2_cache_regstructs.h
INSTALL_SRC += LAN_regmasks.h LAN_regstructs.h
INSTALL_SRC += LCD2_regmasks.h LCD2_regstructs.h
INSTALL_SRC += LCM_regmasks.h LCM_regstructs.h
INSTALL_SRC += LPC_regmasks.h LPC_regstructs.h
INSTALL_SRC += LPT_regmasks.h LPT_regstructs.h
INSTALL_SRC += LSCAN_regmasks.h LSCAN_regstructs.h
INSTALL_SRC += m2m_top_regmasks.h m2m_top_regstructs.h
INSTALL_SRC += MC_regmasks.h MC_regstructs.h
INSTALL_SRC += MFilter_regmasks.h MFilter_regstructs.h
INSTALL_SRC += MIP_regmasks.h MIP_regstructs.h
INSTALL_SRC += MVDO_top_regmasks.h MVDO_top_regstructs.h
INSTALL_SRC += NGAdjust_PIE_regmasks.h NGAdjust_PIE_regstructs.h
INSTALL_SRC += NGAdjust_DAVINCI_regmasks.h NGAdjust_DAVINCI_regstructs.h
INSTALL_SRC += ODMA_AXI_regmasks.h ODMA_AXI_regstructs.h
INSTALL_SRC += PCIE_regmasks.h PCIE_regstructs.h
INSTALL_SRC += PIC_IntCtrl_regmasks.h PIC_IntCtrl_regstructs.h
INSTALL_SRC += PIC_WDMA_6_regmasks.h PIC_WDMA_6_regstructs.h
INSTALL_SRC += PIE_ICE_Common_regmasks.h PIE_ICE_Common_regstructs.h
INSTALL_SRC += PIE_RDMA_ICE_regmasks.h PIE_RDMA_ICE_regstructs.h
INSTALL_SRC += PIE_WDMA_ICE_regmasks.h PIE_WDMA_ICE_regstructs.h
INSTALL_SRC += PIP_regmasks.h PIP_regstructs.h
INSTALL_SRC += PIPE_ACCESS_regmasks.h PIPE_ACCESS_regstructs.h
INSTALL_SRC += PIP_STATS_regmasks.h PIP_STATS_regstructs.h
INSTALL_SRC += PLNR_regmasks.h PLNR_regstructs.h
INSTALL_SRC += PNU2D_regmasks.h PNU2D_regstructs.h
INSTALL_SRC += PRNUDSNU_CORR_regmasks.h PRNUDSNU_CORR_regstructs.h
INSTALL_SRC += RTC_SZ_regmasks.h RTC_SZ_regstructs.h
INSTALL_SRC += SCAN_regmasks.h SCAN_regstructs.h
INSTALL_SRC += SCCP_regmasks.h SCCP_regstructs.h
INSTALL_SRC += ScCSC_regmasks.h ScCSC_regstructs.h
INSTALL_SRC += SDMMC2_regmasks.h SDMMC2_regstructs.h
INSTALL_SRC += SENSOR_regmasks.h SENSOR_regstructs.h
INSTALL_SRC += SERP_regmasks.h SERP_regstructs.h
INSTALL_SRC += SIC_regmasks.h SIC_regstructs.h
INSTALL_SRC += SILABS_regmasks.h SILABS_regstructs.h
INSTALL_SRC += SIZAR_regmasks.h SIZAR_regstructs.h
INSTALL_SRC += SPI_MASTER_regmasks.h SPI_MASTER_regstructs.h
INSTALL_SRC += STMotor_regmasks.h STMotor_regstructs.h
INSTALL_SRC += SVDO_regmasks.h SVDO_regstructs.h
INSTALL_SRC += SWITCHER_regmasks.h SWITCHER_regstructs.h
INSTALL_SRC += TCNSense_regmasks.h TCNSense_regstructs.h
INSTALL_SRC += TH_regmasks.h TH_regstructs.h
INSTALL_SRC += TIMEBASE_regmasks.h TIMEBASE_regstructs.h
INSTALL_SRC += TIMERS_regmasks.h TIMERS_regstructs.h
INSTALL_SRC += TP_CONTONE_regmasks.h TP_CONTONE_regstructs.h
INSTALL_SRC += TP_TEXT_regmasks.h TP_TEXT_regstructs.h
INSTALL_SRC += tsen_regmasks.h tsen_regstructs.h
INSTALL_SRC += UART_regmasks.h UART_regstructs.h
INSTALL_SRC += UED_advanced_regmasks.h UED_advanced_regstructs.h
INSTALL_SRC += USB2TOP_regmasks.h USB2TOP_regstructs.h
INSTALL_SRC += WaveGenLUT_regmasks.h WaveGenLUT_regstructs.h
INSTALL_SRC += Xena_regmasks.h Xena_regstructs.h
INSTALL_SRC += XYCScale_regmasks.h XYCScale_regstructs.h
INSTALL_SRC += XYScale_regmasks.h XYScale_regstructs.h
INSTALL_SRC += YIPI_regmasks.h YIPI_regstructs.h
INSTALL_SRC += Zx_regmasks.h Zx_regstructs.h 

INSTALL_DEST_DIR = $(BUILD_ROOT)/$(GLOBAL_INCLUDE)

include $(BUILD_ROOT)/stdtargets.mk

