/*
 *
 * ============================================================================
 * Copyright (c) 2011  Marvell International, Ltd. All Rights Reserved.
 *
 *                         Marvell Confidential
 * ============================================================================
 */

 /**
  * \file jbig_compatibility.h 
  *  
  * \brief Mapping of register naming to allow the same jbig 
  *        driver to work across multiple asics.
  *  
  */
#ifndef JBIG_COMPATIBILITY_H
#define JBIG_COMPATIBILITY_H

/* JBIG control registers renamed on future architectures*/
#define JBIG_REGS_t JBIG_CODEC_REGS_t

#define JBIG_JSTAT_D_REPLACE_VAL JBIG_CODEC_JSTAT_D_REPLACE_VAL
#define JBIG_JSTAT_E_MASK JBIG_CODEC_JSTAT_E_MASK
#define JBIG_JSTAT_D_MASK JBIG_CODEC_JSTAT_D_MASK
#define JBIG_JSTAT_DD_MASK JBIG_CODEC_JSTAT_DD_MASK
#define JBIG_JSTAT_ED_MASK JBIG_CODEC_JSTAT_ED_MASK
#define JBIG_JSTAT_I_MASK JBIG_CODEC_JSTAT_I_MASK
#define JBIG_JBIG_EN_E_REPLACE_VAL JBIG_CODEC_JBIG_EN_E_REPLACE_VAL
#define JBIG_JBIG_EN_S_REPLACE_VAL JBIG_CODEC_JBIG_EN_S_REPLACE_VAL
#define JBIG_JCTL_E_REPLACE_VAL JBIG_CODEC_JCTL_E_REPLACE_VAL
#define JBIG_JCTL_D_REPLACE_VAL JBIG_CODEC_JCTL_D_REPLACE_VAL
#define JBIG_JSTAT_E_MASK JBIG_CODEC_JSTAT_E_MASK
#define JBIG_JCTL_T_REPLACE_VAL JBIG_CODEC_JCTL_T_REPLACE_VAL
#define JBIG_JCTL_A_REPLACE_VAL JBIG_CODEC_JCTL_A_REPLACE_VAL
#define JBIG_JCTL_M_REPLACE_VAL JBIG_CODEC_JCTL_M_REPLACE_VAL
#define JBIG_JCTL_L_REPLACE_VAL JBIG_CODEC_JCTL_L_REPLACE_VAL
#define JBIG_JCTL_BE_REPLACE_VAL JBIG_CODEC_JCTL_BE_REPLACE_VAL
#define JBIG_JCTL_B_REPLACE_VAL JBIG_CODEC_JCTL_B_REPLACE_VAL
#define JBIG_JCTL_C_REPLACE_VAL JBIG_CODEC_JCTL_C_REPLACE_VAL
#define JBIG_JSTAT_V_MASK JBIG_CODEC_JSTAT_V_MASK
#define JBIG_JSTAT_AR_MASK JBIG_CODEC_JSTAT_AR_MASK

/* JBIG specific IDMA maps to generic IDMA on future architectures*/
#define IDMA_SLI_REGS_t JBIG_CODEC_IDMA_REGS_t

#define IDMA_SLI_STATUS_DMA_BUSY_MASK JBIG_CODEC_IDMA_STATUS_DMA_BUSY_MASK
#define IDMA_SLI_CFG_REPLICATE_REPLACE_VAL JBIG_CODEC_IDMA_CFG_REPLICATE_REPLACE_VAL
#define IDMA_SLI_CFG_OUT_WIDTH_REPLACE_VAL JBIG_CODEC_IDMA_CFG_OUT_WIDTH_REPLACE_VAL
#define IDMA_SLI_CFG_BURST_LEN_REPLACE_VAL JBIG_CODEC_IDMA_CFG_BURST_LEN_REPLACE_VAL
#define IDMA_SLI_LINE_WIDTH_LINE_WIDTH_REPLACE_VAL JBIG_CODEC_IDMA_LINE_WIDTH_LINE_WIDTH_REPLACE_VAL
#define IDMA_SLI_CFG_ENABLE_REPLACE_VAL JBIG_CODEC_IDMA_CFG_ENABLE_REPLACE_VAL
#define IDMA_SLI_INT_ST_WHO_INT_ST_MASK JBIG_CODEC_IDMA_INT_ST_WHO_INT_ST_MASK
#define IDMA_SLI_INT_ST_FIN_INT_ST_MASK JBIG_CODEC_IDMA_INT_ST_FIN_INT_ST_MASK
#define IDMA_SLI_INT_ST_EOI_INT_ST_MASK JBIG_CODEC_IDMA_INT_ST_EOI_INT_ST_MASK
#define IDMA_SLI_INT_ST_RST_INT_ST_MASK JBIG_CODEC_IDMA_INT_ST_RST_INT_ST_MASK
#define IDMA_SLI_RESET_SOFT_RESET_REPLACE_VAL JBIG_CODEC_IDMA_RESET_SOFT_RESET_REPLACE_VAL 
#define IDMA_SLI_STATUS_SOFTRESET_MASK IDMA_STATUS_SOFTRESET_MASK

#if 0

/* JBIG specific ODMA maps to generic ODMA on future architectures*/
#define ODMA_SLI_REGS_t JBIG_CODEC_ODMA_REGS_t

#define ODMA_SLI_STATUS_DMA_BUSY_MASK JBIG_CODEC_ODMA_STATUS_DMA_BUSY_MASK
#define ODMA_SLI_CFG_REPLICATE_REPLACE_VAL JBIG_CODEC_ODMA_CFG_REPLICATE_REPLACE_VAL
#define ODMA_SLI_CFG_OUT_WIDTH_REPLACE_VAL JBIG_CODEC_ODMA_CFG_OUT_WIDTH_REPLACE_VAL
#define ODMA_SLI_CFG_BURST_LEN_REPLACE_VAL JBIG_CODEC_ODMA_CFG_BURST_LEN_REPLACE_VAL
#define ODMA_SLI_LINE_WIDTH_LINE_WIDTH_REPLACE_VAL JBIG_CODEC_ODMA_LINE_WIDTH_LINE_WIDTH_REPLACE_VAL
#define ODMA_SLI_CFG_ENABLE_REPLACE_VAL JBIG_CODEC_ODMA_CFG_ENABLE_REPLACE_VAL
#define ODMA_SLI_INT_ST_WHO_INT_ST_MASK JBIG_CODEC_ODMA_INT_ST_WHO_INT_ST_MASK
#define ODMA_SLI_INT_ST_FIN_INT_ST_MASK JBIG_CODEC_ODMA_INT_ST_FIN_INT_ST_MASK
#define ODMA_SLI_INT_ST_EOI_INT_ST_MASK JBIG_CODEC_ODMA_INT_ST_EOI_INT_ST_MASK
#define ODMA_SLI_INT_ST_RST_INT_ST_MASK JBIG_CODEC_ODMA_INT_ST_RST_INT_ST_MASK
#define ODMA_SLI_INT_ST_RST_INT_ST_MASK JBIG_CODEC_ODMA_INT_ST_RST_INT_ST_MASK
#define ODMA_SLI_RESET_SOFT_RESET_REPLACE_VAL JBIG_CODEC_ODMA_RESET_SOFT_RESET_REPLACE_VAL 
#define ODMA_SLI_CFG_IN_WIDTH_REPLACE_VAL JBIG_CODEC_ODMA_CFG_IN_WIDTH_REPLACE_VAL
#define ODMA_SLI_INT_PEND_WHO_INT_PEND_MASK JBIG_CODEC_ODMA_INT_PEND_WHO_INT_PEND_MASK
#define ODMA_SLI_INT_PEND_FIN_INT_PEND_MASK JBIG_CODEC_ODMA_INT_PEND_FIN_INT_PEND_MASK
#define ODMA_SLI_INT_PEND_EOI_ERR_INT_PEND_MASK JBIG_CODEC_ODMA_INT_PEND_EOI_ERR_INT_PEND_MASK
#define ODMA_SLI_INT_PEND_EOI_INT_PEND_MASK JBIG_CODEC_ODMA_INT_PEND_EOI_INT_PEND_MASK

#endif // ASIC_REV < ASIC_REV_Z3


#endif //TEXT_PAD_COMPATIBILITY_H

