/**
 * ============================================================================
 * Copyright (c) 2012 Marvell International, Ltd. All Rights Reserved.
 *
 *                         Marvell Confidential
 * ============================================================================
 **/

#ifndef SCANHW_H
#define SCANHW_H

// auto generated by rereg.py @ 16:26:12 02-Jul-2012

#define SCIF_SCFG1                ((volatile uint32_t *)(ICE_BASE+0x40000))
#define SCIF_SCFG1_P1CLKEN(x)     (((x) & 0x1) << 31)
#define SCIF_SCFG1_P2CLKEN(x)     (((x) & 0x1) << 30)
#define SCIF_SCFG1_RSCLKEN(x)     (((x) & 0x1) << 29)
#define SCIF_SCFG1_CPCLKEN(x)     (((x) & 0x1) << 28)
#define SCIF_SCFG1_MCLKEN(x)      (((x) & 0x1) << 27)
#define SCIF_SCFG1_VSCLKEN(x)     (((x) & 0x1) << 26)
#define SCIF_SCFG1_CLCKEN(x)      (((x) & 0x1) << 25)
#define SCIF_SCFG1_LCLMPEN(x)     (((x) & 0x1) << 24)
#define SCIF_SCFG1_BULBEN(x)      (((x) & 0x1) << 20)
#define SCIF_SCFG1_SSMEN(x)       (((x) & 0xf) << 16)
#define SCIF_SCFG1_SMPOL(x)       (((x) & 0xf) << 12)
#define SCIF_SCFG1_P1APOL(x)      (((x) & 0x1) << 11)
#define SCIF_SCFG1_SPPOL(x)       (((x) & 0x1) << 8)
#define SCIF_SCFG1_SPPOL(x)       (((x) & 0x1) << 8)
#define SCIF_SCFG1_SPTOG(x)       (((x) & 0x1) << 9)
#define SCIF_SCFG1_SCPOL(x)       (((x) & 0xf) << 4)
#define SCIF_SCFG1_SCPOL_CPCLK(x) (((x) & 0x1) << 4)
#define SCIF_SCFG1_SCPOL_RSCLK(x) (((x) & 0x1) << 5)
#define SCIF_SCFG1_SCPOL_P2CLK(x) (((x) & 0x1) << 6)
#define SCIF_SCFG1_SCPOL_P1CLK(x) (((x) & 0x1) << 7)
#define SCIF_SCFG1_SCPOL(x)       (((x) & 0xf) << 4)
#define SCIF_SCFG1_SCPOL_CPCLK(x) (((x) & 0x1) << 4)
#define SCIF_SCFG1_SCPOL_RSCLK(x) (((x) & 0x1) << 5)
#define SCIF_SCFG1_SCPOL_P2CLK(x) (((x) & 0x1) << 6)
#define SCIF_SCFG1_SCPOL_P1CLK(x) (((x) & 0x1) << 7)
#define SCIF_SCFG1_ACPOL(x)       (((x) & 0xf) << 0)
#define SCIF_SCFG1_ACPOL_LCCLK(x) (((x) & 0x1) << 0)
#define SCIF_SCFG1_ACPOL_CD1CLK(x) (((x) & 0x1) << 1)
#define SCIF_SCFG1_ACPOL_VSCLk(x) (((x) & 0x1) << 2)
#define SCIF_SCFG1_ACPOL_MCLK(x)  (((x) & 0x1) << 3)

#define SCIF_SCFG2                ((volatile uint32_t *)(ICE_BASE+0x40004))
#define SCIF_SCFG2_CMODE(x)       (((x) & 0x1) << 31)
#define SCIF_SCFG2_STYPE(x)       (((x) & 0x1) << 30)
#define SCIF_SCFG2_SSEL(x)        (((x) & 0x3) << 28)
#define SCIF_SCFG2_AFEWIDTH(x)    (((x) & 0x3) << 26)
#define SCIF_SCFG2_EXPMASK(x)     (((x) & 0x1) << 25)
#define SCIF_SCFG2_LEDEN0(x)      (((x) & 0x7) << 16)
#define SCIF_SCFG2_EXPDIV(x)      (((x) & 0xff) << 8)
#define SCIF_SCFG2_EXPDIV(x)      (((x) & 0xff) << 8)
#define SCIF_SCFG2_PIXPER(x)      (((x) & 0xff) << 0)
#define SCIF_SCFG2_LEDEN1(x)      (((x) & 0x7) << 19)
#define SCIF_SCFG2_LEDEN0(x)      (((x) & 0x7) << 16)
/* AFE Data Widths, 2-bit value */
#define SCIF_SCFG2_AFEWIDTH_4   0  /* 4-bit AFE Data Width. For example, WM8152 */
#define SCIF_SCFG2_AFEWIDTH_8   1  /* 8-bit AFE Data Width. For example, AD9826W */
#define SCIF_SCFG2_AFEWIDTH_16  2  /* 16-bit AFE Data Width. For example, Internal AFE */

#define SCIF_SCFG3                ((volatile uint32_t *)(ICE_BASE+0x40008))
#define SCIF_SCFG3_P1RISE(x)      (((x) & 0x3) << 30)
#define SCIF_SCFG3_P1FALL(x)      (((x) & 0x3) << 28)
#define SCIF_SCFG3_P2RISE(x)      (((x) & 0x3) << 26)
#define SCIF_SCFG3_P2FALL(x)      (((x) & 0x3) << 24)
#define SCIF_SCFG3_RSRISE(x)      (((x) & 0x3) << 22)
#define SCIF_SCFG3_RSFALL(x)      (((x) & 0x3) << 20)
#define SCIF_SCFG3_CPRISE(x)      (((x) & 0x3) << 18)
#define SCIF_SCFG3_CPFALL(x)      (((x) & 0x3) << 16)
#define SCIF_SCFG3_MCRISE(x)      (((x) & 0x3) << 14)
#define SCIF_SCFG3_MCFALL(x)      (((x) & 0x3) << 12)
#define SCIF_SCFG3_VSRISE(x)      (((x) & 0x3) << 10)
#define SCIF_SCFG3_VSFALL(x)      (((x) & 0x3) << 8)
#define SCIF_SCFG3_CD1RISE(x)     (((x) & 0x3) << 6)
#define SCIF_SCFG3_CD1FALL(x)     (((x) & 0x3) << 4)
#define SCIF_SCFG3_SPRISE(x)      (((x) & 0x3) << 2)
#define SCIF_SCFG3_SPFALL(x)      (((x) & 0x3) << 0)

#define SCIF_SCTRL                ((volatile uint32_t *)(ICE_BASE+0x4000c))
#define SCIF_SCTRL_UMSEN(x)       (((x) & 0x1) << 7)
#define SCIF_SCTRL_CMDQEN(x)      (((x) & 0x1) << 6)
#define SCIF_SCTRL_TERMCMD(x)     (((x) & 0x1) << 5)
#define SCIF_SCTRL_SRESET(x)      (((x) & 0x1) << 4)
#define SCIF_SCTRL_AFEPIE(x)      (((x) & 0x1) << 3)
#define SCIF_SCTRL_SCMDIE(x)      (((x) & 0x1) << 2)
#define SCIF_SCTRL_RUN(x)         (((x) & 0x1) << 1)
#define SCIF_SCTRL_SCANEN(x)      (((x) & 0x1) << 0)

#define SCIF_SCMD                 ((volatile uint32_t *)(ICE_BASE+0x40010))
#define SCIF_SCMD_SDATA(x)        (((x) & 0x1) << 30)
#define SCIF_SCMD_SPTOGVAL(x)     (((x) & 0x1) << 29)
#define SCIF_SCMD_SCLKPER(x)      (((x) & 0x1fff) << 16)
#define SCIF_SCMD_SCANY(x)        (((x) & 0xffff) << 0)
#define SCIF_SCMD_WRITE(cmd) *SCIF_SCMD=(cmd)

#define SCIF_SSTAT                ((volatile uint32_t *)(ICE_BASE+0x40014))
#define SCIF_SSTAT_SCANYR         (0xffff << 16)
#define SCIF_SSTAT_EXTINTSTAT     (0xf << 8)
#define SCIF_SSTAT_UNEXPSYNC      (0x1 << 7)
#define SCIF_SSTAT_CMDSTAT        (0x1 << 6)
#define SCIF_SSTAT_QEMPTY         (0x1 << 5)
#define SCIF_SSTAT_QFULL          (0x1 << 4)
#define SCIF_SSTAT_QOVR           (0x1 << 3)
#define SCIF_SSTAT_CIOVR          (0x1 << 2)
#define SCIF_SSTAT_SCMDCOMP       (0x1 << 0)

#define SCIF_SIACK                ((volatile uint32_t *)(ICE_BASE+0x40018))
#define SCIF_SIACK_UMSACK(x)      (((x) & 0x1) << 4)
#define SCIF_SIACK_QOVRACK(x)     (((x) & 0x1) << 3)
#define SCIF_SIACK_CIOVRACK(x)    (((x) & 0x1) << 2)
#define SCIF_SIACK_SCMDACK(x)     (((x) & 0x1) << 0)

#define SCIF_SCANX                ((volatile uint32_t *)(ICE_BASE+0x4001c))
#define SCIF_SCANX_EXPVAL(x)      (((x) & 0xffff) << 16)
#define SCIF_SCANX_SCANX(x)       (((x) & 0xffff) << 0)

#define SCIF_SCYCLE               ((volatile uint32_t *)(ICE_BASE+0x40020))
#define SCIF_SCYCLE_EXPPER(x)     (((x) & 0xffff) << 16)
#define SCIF_SCYCLE_SCYCLE(x)     (((x) & 0x3f) << 0)

#define SCIF_STCFG1               ((volatile uint32_t *)(ICE_BASE+0x40024))
#define SCIF_STCFG1_SPGEN(x)      (((x) & 0x1) << 31)
#define SCIF_STCFG1_MSKEXTD(x)    (((x) & 0xf) << 24)
#define SCIF_STCFG1_SSME1(x)      (((x) & 0xff) << 16)
#define SCIF_STCFG1_SSME2(x)      (((x) & 0xff) << 0)

#define SCIF_STCFG2               ((volatile uint32_t *)(ICE_BASE+0x40028))
#define SCIF_STCFG2_SPE1(x)       (((x) & 0xff) << 16)
#define SCIF_STCFG2_SPE2(x)       (((x) & 0xff) << 0)

#define SCIF_STCFG3               ((volatile uint32_t *)(ICE_BASE+0x4002c))
#define SCIF_STCFG3_APH1E1(x)     (((x) & 0xff) << 24)
#define SCIF_STCFG3_APH1E2(x)     (((x) & 0xff) << 16)
#define SCIF_STCFG3_APH1E3(x)     (((x) & 0xff) << 8)
#define SCIF_STCFG3_APH1E4(x)     (((x) & 0xff) << 0)

#define SCIF_STCFG4               ((volatile uint32_t *)(ICE_BASE+0x40030))
#define SCIF_STCFG4_APH1E5(x)     (((x) & 0xff) << 24)
#define SCIF_STCFG4_APH1E6(x)     (((x) & 0xff) << 16)
#define SCIF_STCFG4_APH1E7(x)     (((x) & 0xff) << 8)
#define SCIF_STCFG4_APH1E8(x)     (((x) & 0xff) << 0)

#define SCIF_CCFG                 ((volatile uint32_t *)(ICE_BASE+0x40034))
#define SCIF_CCFG_CPMODE(x)       (((x) & 0x1) << 31)
#define SCIF_CCFG_CLMODE(x)       (((x) & 0x1) << 30)
#define SCIF_CCFG_CLE1(x)         (((x) & 0xff) << 16)
#define SCIF_CCFG_CCLE2(x)        (((x) & 0xff) << 8)
#define SCIF_CCFG_ACLE2(x)        (((x) & 0xff) << 0)

#define SCIF_SCLK1                ((volatile uint32_t *)(ICE_BASE+0x40038))
#define SCIF_SCLK1_P1E1(x)        (((x) & 0xff) << 24)
#define SCIF_SCLK1_P1E2(x)        (((x) & 0xff) << 16)
#define SCIF_SCLK1_P1E3(x)        (((x) & 0xff) << 8)
#define SCIF_SCLK1_P1E4(x)        (((x) & 0xff) << 0)

#define SCIF_SCLK2                ((volatile uint32_t *)(ICE_BASE+0x4003c))
#define SCIF_SCLK2_P1E5(x)        (((x) & 0xff) << 24)
#define SCIF_SCLK2_P1E6(x)        (((x) & 0xff) << 16)
#define SCIF_SCLK2_P1E7(x)        (((x) & 0xff) << 8)
#define SCIF_SCLK2_P1E8(x)        (((x) & 0xff) << 0)

#define SCIF_SCLK3                ((volatile uint32_t *)(ICE_BASE+0x40040))
#define SCIF_SCLK3_P2E1(x)        (((x) & 0xff) << 24)
#define SCIF_SCLK3_P2E2(x)        (((x) & 0xff) << 16)
#define SCIF_SCLK3_P2E3(x)        (((x) & 0xff) << 8)
#define SCIF_SCLK3_P2E4(x)        (((x) & 0xff) << 0)

#define SCIF_SCLK4                ((volatile uint32_t *)(ICE_BASE+0x40044))
#define SCIF_SCLK4_P2E5(x)        (((x) & 0xff) << 24)
#define SCIF_SCLK4_P2E6(x)        (((x) & 0xff) << 16)
#define SCIF_SCLK4_P2E7(x)        (((x) & 0xff) << 8)
#define SCIF_SCLK4_P2E8(x)        (((x) & 0xff) << 0)

#define SCIF_SCLK5                ((volatile uint32_t *)(ICE_BASE+0x40048))
#define SCIF_SCLK5_RSE1(x)        (((x) & 0xff) << 24)
#define SCIF_SCLK5_RSE2(x)        (((x) & 0xff) << 16)
#define SCIF_SCLK5_RSE3(x)        (((x) & 0xff) << 8)
#define SCIF_SCLK5_RSE4(x)        (((x) & 0xff) << 0)

#define SCIF_SCLK6                ((volatile uint32_t *)(ICE_BASE+0x4004c))
#define SCIF_SCLK6_CPE1(x)        (((x) & 0xff) << 24)
#define SCIF_SCLK6_CPE2(x)        (((x) & 0xff) << 16)
#define SCIF_SCLK6_CPE3(x)        (((x) & 0xff) << 8)
#define SCIF_SCLK6_CPE4(x)        (((x) & 0xff) << 0)

#define SCIF_ACLK1                ((volatile uint32_t *)(ICE_BASE+0x40050))
#define SCIF_ACLK1_MCE1(x)        (((x) & 0xff) << 24)
#define SCIF_ACLK1_MCE2(x)        (((x) & 0xff) << 16)
#define SCIF_ACLK1_MCE3(x)        (((x) & 0xff) << 8)
#define SCIF_ACLK1_MCE4(x)        (((x) & 0xff) << 0)

#define SCIF_ACLK2                ((volatile uint32_t *)(ICE_BASE+0x40054))
#define SCIF_ACLK2_MCE5(x)        (((x) & 0xff) << 24)
#define SCIF_ACLK2_MCE6(x)        (((x) & 0xff) << 16)
#define SCIF_ACLK2_MCE7(x)        (((x) & 0xff) << 8)
#define SCIF_ACLK2_MCE8(x)        (((x) & 0xff) << 0)

#define SCIF_ACLK3                ((volatile uint32_t *)(ICE_BASE+0x40058))
#define SCIF_ACLK3_MCE9(x)        (((x) & 0xff) << 24)
#define SCIF_ACLK3_MCE10(x)       (((x) & 0xff) << 16)
#define SCIF_ACLK3_MCE11(x)       (((x) & 0xff) << 8)
#define SCIF_ACLK3_MCE12(x)       (((x) & 0xff) << 0)

#define SCIF_ACLK4                ((volatile uint32_t *)(ICE_BASE+0x4005c))
#define SCIF_ACLK4_VSE1(x)        (((x) & 0xff) << 24)
#define SCIF_ACLK4_VSE2(x)        (((x) & 0xff) << 16)
#define SCIF_ACLK4_VSE3(x)        (((x) & 0xff) << 8)
#define SCIF_ACLK4_VSE4(x)        (((x) & 0xff) << 0)

#define SCIF_ACLK5                ((volatile uint32_t *)(ICE_BASE+0x40060))
#define SCIF_ACLK5_CD1E1(x)       (((x) & 0xff) << 24)
#define SCIF_ACLK5_CD1E2(x)       (((x) & 0xff) << 16)
#define SCIF_ACLK5_CD1E3(x)       (((x) & 0xff) << 8)
#define SCIF_ACLK5_CD1E4(x)       (((x) & 0xff) << 0)

#define SCIF_ACLK6                ((volatile uint32_t *)(ICE_BASE+0x40064))
#define SCIF_ACLK6_MCE13(x)       (((x) & 0xff) << 24)
#define SCIF_ACLK6_MCE14(x)       (((x) & 0xff) << 16)
#define SCIF_ACLK6_MCE15(x)       (((x) & 0xff) << 8)
#define SCIF_ACLK6_MCE16(x)       (((x) & 0xff) << 0)

#define SCIF_LDATA1               ((volatile uint32_t *)(ICE_BASE+0x40068))
#define SCIF_LDATA_DS_A(x)       (((x) & 0xff) << 24)
#define SCIF_LDATA_DC_A(x)       (((x) & 0x1f) << 16)
#define SCIF_LDATA_DS_B(x)       (((x) & 0xff) << 8)
#define SCIF_LDATA_DC_B(x)       (((x) & 0x1f) << 0)
/* AFE Load Data codes; 3 bits each; 16-bit value "ABCD" */
#define SCIF_LDATA_CODE_CLEAR   0  /* clear all bits */
#define SCIF_LDATA_CODE_AB_BITS 1  /* "AB", 8 MS bits */
#define SCIF_LDATA_CODE_CD_BITS 2  /* "CD", LS bits */
#define SCIF_LDATA_CODE_ABCD_BITS 3  /* "ABCD" (not implemented) */
#define SCIF_LDATA_CODE_A_BITS  4  /* "A", 4 MS bits */
#define SCIF_LDATA_CODE_B_BITS  5  /* "B", next 4 bits */
#define SCIF_LDATA_CODE_C_BITS  6  /* "C", next 4 bits */
#define SCIF_LDATA_CODE_D_BITS  7  /* "D", 4 LS bits */
#define SCIF_LDATA_CODE_LOAD_COMPL  (1<<3) /* load complete */
#define SCIF_LDATA_CODE_SEQ_COMPL   (1<<4) /* sequence complete */

//#define SCIF_LDATA1               ((volatile uint32_t *)(ICE_BASE+0x4006c))
//#define SCIF_LDATA_DS_A(x)       (((x) & 0xff) << 24)
//#define SCIF_LDATA_DC_A(x)       (((x) & 0x1f) << 16)
//#define SCIF_LDATA_DS_B(x)       (((x) & 0xff) << 8)
//#define SCIF_LDATA_DC_B(x)       (((x) & 0x1f) << 0)
///* AFE Load Data codes; 3 bits each; 16-bit value "ABCD" */
//#define SCIF_LDATA_CODE_CLEAR   0  /* clear all bits */
//#define SCIF_LDATA_CODE_AB_BITS 1  /* "AB", 8 MS bits */
//#define SCIF_LDATA_CODE_CD_BITS 2  /* "CD", LS bits */
//#define SCIF_LDATA_CODE_ABCD_BITS 3  /* "ABCD" (not implemented) */
//#define SCIF_LDATA_CODE_A_BITS  4  /* "A", 4 MS bits */
//#define SCIF_LDATA_CODE_B_BITS  5  /* "B", next 4 bits */
//#define SCIF_LDATA_CODE_C_BITS  6  /* "C", next 4 bits */
//#define SCIF_LDATA_CODE_D_BITS  7  /* "D", 4 LS bits */
//#define SCIF_LDATA_CODE_LOAD_COMPL  (1<<3) /* load complete */
//#define SCIF_LDATA_CODE_SEQ_COMPL   (1<<4) /* sequence complete */

#define SCIF_LDATA2               ((volatile uint32_t *)(ICE_BASE+0x40070))

//#define SCIF_LDATA2               ((volatile uint32_t *)(ICE_BASE+0x40074))

#define SCIF_LDATA3               ((volatile uint32_t *)(ICE_BASE+0x40078))

//#define SCIF_LDATA3               ((volatile uint32_t *)(ICE_BASE+0x4007c))

#define SCIF_LDATA4               ((volatile uint32_t *)(ICE_BASE+0x40080))

//#define SCIF_LDATA4               ((volatile uint32_t *)(ICE_BASE+0x40084))

#define SCIF_LDATA5               ((volatile uint32_t *)(ICE_BASE+0x40088))

//#define SCIF_LDATA5               ((volatile uint32_t *)(ICE_BASE+0x4008c))

#define SCIF_LDATA6               ((volatile uint32_t *)(ICE_BASE+0x40090))

//#define SCIF_LDATA6               ((volatile uint32_t *)(ICE_BASE+0x40094))

#define SCIF_PSEQ1                ((volatile uint32_t *)(ICE_BASE+0x40098))
#define SCIF_PSEQ1_PSEQ1(x)       (((x) & 0x3f) << 24)
#define SCIF_PSEQ1_PSEQ2(x)       (((x) & 0x3f) << 16)
#define SCIF_PSEQ1_PSEQ3(x)       (((x) & 0x3f) << 8)
#define SCIF_PSEQ1_PSEQ4(x)       (((x) & 0x3f) << 0)

#define SCIF_PSEQ2                ((volatile uint32_t *)(ICE_BASE+0x4009c))
#define SCIF_PSEQ2_PSEQ5(x)       (((x) & 0x3f) << 8)
#define SCIF_PSEQ2_PSEQ6(x)       (((x) & 0x3f) << 0)

#define SCIF_BPWM                 ((volatile uint32_t *)(ICE_BASE+0x400a0))
#define SCIF_BPWM_BPWMPER(x)      (((x) & 0xfff) << 16)
#define SCIF_BPWM_BPWMDTY(x)      (((x) & 0xfff) << 0)

#define SCIF_MCFG                 ((volatile uint32_t *)(ICE_BASE+0x400a4))
#define SCIF_MCFG_PSMODE          (0x1 << 31)
#define SCIF_MCFG_PSCFG           (0x7 << 28)
#define SCIF_MCFG_PSCOUNT         (0x3ff << 16)
#define SCIF_MCFG_LSMODE(x)       (((x) & 0x3) << 13)
#define SCIF_MCFG_MTYPE(x)        (((x) & 0x1) << 11)

#define SCIF_AFEPC                ((volatile uint32_t *)(ICE_BASE+0x400ac))
#define SCIF_AFEPC_AUTO(x)        (((x) & 0x1) << 30)

#define SCIF_CFGARB               ((volatile uint32_t *)(ICE_BASE+0x400b4))
#define SCIF_CFGARB_EXTEN(x)      (((x) & 0x7) << 16)
#define SCIF_CFGARB_PAREN(x)      (((x) & 0x3) << 0)

#define SCIF_LED0                 ((volatile uint32_t *)(ICE_BASE+0x400b8))
#define SCIF_LED0_LEDPOS(x)       (((x) & 0xffff) << 16)
#define SCIF_LED0_LEDNEG(x)       (((x) & 0xffff) << 0)
#define SCIF_LED_POS(x) (((x) & 0xFFFF) << 16) // LED Positive Edge Delay
#define SCIF_LED_NEG(x) (((x) & 0xFFFF) <<  0) // LED Negative Edge Delay

//#define SCIF_LED0                 ((volatile uint32_t *)(ICE_BASE+0x400bc))
//#define SCIF_LED0_LEDPOS(x)       (((x) & 0xffff) << 16)
//#define SCIF_LED0_LEDNEG(x)       (((x) & 0xffff) << 0)
//#define SCIF_LED_POS(x) (((x) & 0xFFFF) << 16) // LED Positive Edge Delay
//#define SCIF_LED_NEG(x) (((x) & 0xFFFF) <<  0) // LED Negative Edge Delay

#define SCIF_LED1                 ((volatile uint32_t *)(ICE_BASE+0x400c0))
#define SCIF_LED1_LEDPOS(x)       (((x) & 0xffff) << 16)
#define SCIF_LED1_LEDNEG(x)       (((x) & 0xffff) << 0)

//#define SCIF_LED1                 ((volatile uint32_t *)(ICE_BASE+0x400c4))
//#define SCIF_LED1_LEDPOS(x)       (((x) & 0xffff) << 16)
//#define SCIF_LED1_LEDNEG(x)       (((x) & 0xffff) << 0)

#define SCIF_LED2                 ((volatile uint32_t *)(ICE_BASE+0x400c8))
#define SCIF_LED2_LEDPOS(x)       (((x) & 0xffff) << 16)
#define SCIF_LED2_LEDNEG(x)       (((x) & 0xffff) << 0)

//#define SCIF_LED2                 ((volatile uint32_t *)(ICE_BASE+0x400cc))
//#define SCIF_LED2_LEDPOS(x)       (((x) & 0xffff) << 16)
//#define SCIF_LED2_LEDNEG(x)       (((x) & 0xffff) << 0)

#define SCIF_LPWMCONFIG           ((volatile uint32_t *)(ICE_BASE+0x400d0))
#define SCIF_LPWMCONFIG_LPWMPER(x) (((x) & 0xffff) << 16)
#define SCIF_LPWMCONFIG_LEDPOL(x) (((x) & 0x7) << 0)
/* hide the ScanBlock2005 SCFG1.LEDEN field so we can maintain some vestige of
 * code compatibility
 */
#define SCIF_SCFG1_LEDEN(x) 0


//#define SCIF_LPWMCONFIG           ((volatile uint32_t *)(ICE_BASE+0x400d4))
//#define SCIF_LPWMCONFIG_LPWMPER(x) (((x) & 0xffff) << 16)
//#define SCIF_LPWMCONFIG_LEDPOL(x) (((x) & 0x7) << 0)
///* hide the ScanBlock2005 SCFG1.LEDEN field so we can maintain some vestige of
// * code compatibility
// */
//#define SCIF_SCFG1_LEDEN(x) 0


#define SCIF_LPWM0                ((volatile uint32_t *)(ICE_BASE+0x400d8))
#define SCIF_LPWM0_LEDON(x)       (((x) & 0xffff) << 16)
#define SCIF_LPWM0_LEDOFF(x)      (((x) & 0xffff) << 0)

//#define SCIF_LPWM0                ((volatile uint32_t *)(ICE_BASE+0x400dc))
//#define SCIF_LPWM0_LEDON(x)       (((x) & 0xffff) << 16)
//#define SCIF_LPWM0_LEDOFF(x)      (((x) & 0xffff) << 0)

#define SCIF_LPWM1                ((volatile uint32_t *)(ICE_BASE+0x400e0))
#define SCIF_LPWM1_LEDON(x)       (((x) & 0xffff) << 16)
#define SCIF_LPWM1_LEDOFF(x)      (((x) & 0xffff) << 0)

//#define SCIF_LPWM1                ((volatile uint32_t *)(ICE_BASE+0x400e4))
//#define SCIF_LPWM1_LEDON(x)       (((x) & 0xffff) << 16)
//#define SCIF_LPWM1_LEDOFF(x)      (((x) & 0xffff) << 0)

#define SCIF_LPWM2                ((volatile uint32_t *)(ICE_BASE+0x400e8))
#define SCIF_LPWM2_LEDON(x)       (((x) & 0xffff) << 16)
#define SCIF_LPWM2_LEDOFF(x)      (((x) & 0xffff) << 0)

//#define SCIF_LPWM2                ((volatile uint32_t *)(ICE_BASE+0x400ec))
//#define SCIF_LPWM2_LEDON(x)       (((x) & 0xffff) << 16)
//#define SCIF_LPWM2_LEDOFF(x)      (((x) & 0xffff) << 0)

#endif // SCANHW_H
