/*===================================================
*	(C) Copyright 2010   Marvell International Ltd.
*		All Rights Reserved
*
*		Marvell Confidential
=====================================================
*/
const char*  __SYMBOL_TABLE__[] =
{
"1200",		/*	0 */ 
"2400",		/*	1 */ 
"300",		/*	2 */ 
"600",		/*	3 */ 
"AUTO",		/*	4 */ 
"AUTOSELECT",		/*	5 */ 
"CANCELED",		/*	6 */ 
"CARDSTOCK",		/*	7 */ 
"CASSETTE",		/*	8 */ 
"CODE",		/*	9 */ 
"COLOR",		/*	10 */ 
"COMMENT",		/*	11 */ 
"CONFIG",		/*	12 */ 
"CONTINUE",		/*	13 */ 
"COPIES_",		/*	14 */ 
"DEFAULT",		/*	15 */ 
"DEVICE",		/*	16 */ 
"DINQUIRE",		/*	17 */ 
"DISPLAY",		/*	18 */ 
"DRAFT",		/*	19 */ 
"ECHO",		/*	20 */ 
"ECONOMODE",		/*	21 */
"END",		/*	22 */ 
"ENTER",		/*	23 */ 
"ENUMERATED",		/*	24 */ 
"ENVELOPE",		/*	25 */ 
"EOJ",		/*	26 */ 
"FALSE",		/*	27 */ 
"FAST",		/*	28 */ 
"FIRST",		/*	29 */ 
"GLOSSY",		/*	30 */ 
"GRAYSCALE",		/*	31 */ 
"HIGH",		/*	32 */ 
"ID",		/*	33 */ 
"INFO",		/*	34 */ 
"INITIALIZE",		/*	35 */ 
"INQUIRE",		/*	36 */ 
"INSTALLED",		/*	37 */ 
"INTRAY1SIZE",		/*	38 */ 
"INTRAY2SIZE",		/*	39 */ 
"INTRAY3SIZE",		/*	40 */ 
"INTRAY4SIZE",		/*	41 */ 
"JOB",		/*	42 */ 
"LANDSCAPE",		/*	43 */ 
"LANGUAGE",		/*	44 */ 
"LIGHT",		/*	45 */ 
"LONGEDGE",		/*	46 */ 
"LOWER",		/*	47 */ 
"MANUAL",		/*	48 */ 
"MANUALFEED",		/*	49 */ 
"MEDIASOURCE",		/*	50 */ 
"MEDIATYPE",		/*	51 */ 
"MEDIUM",		/*	52 */ 
"MEMORY",		/*	53 */ 
"MPTRAY",		/*	54 */ 
"NAME",		/*	55 */ 
"NORMAL",		/*	56 */ 
"OFF",		/*	57 */ 
"ON",		/*	58 */ 
"ONLINE",		/*	59 */ 
"OPTIONALOUTPUTBIN1",		/*	60 */ 
"OPTIONALOUTPUTBIN2",		/*	61 */ 
"ORIENTATION",		/*	62 */ 
"OUTBIN",		/*	63 */ 
"OUTLINEPOINTSIZE",		/*	64 */ 
"PAGE",		/*	65 */ 
"PAGECOUNT",		/*	66 */ 
"PAPER",		/*	67 */ 
"PAPERLABEL",		/*	68 */ 
"PARALLEL",		/*	69 */ 
"PASSWORD",		/*	70 */ 
"PJL",		/*	71 */ 
"PLAIN",		/*	72 */ 
"PORTRAIT",		/*	73 */ 
"POSTCARD",		/*	74 */ 
"POWERSAVE",		/*	75 */ 
"POWERSAVETIME",		/*	76 */ 
"QTY",		/*	77 */ 
"RANGE",		/*	78 */ 
"READONLY",		/*	79 */ 
"RENDERMODE",		/*	80 */ 
"REPRINT",		/*	81 */ 
"RESET",		/*	82 */ 
"RESOLUTION",		/*	83 */ 
"SET",		/*	84 */ 
"SHORTEDGE",		/*	85 */ 
"SLOW",		/*	86 */ 
"SPECIAL",		/*	87 */ 
"START",		/*	88 */ 
"STATUS",		/*	89 */ 
"STOP",		/*	90 */ 
"THICK",		/*	91 */ 
"THIN",		/*	92 */ 
"TIMED",		/*	93 */ 
"TIMEOUT",		/*	94 */ 
"TONERDARKNESS",		/*	95 */ 
"TRANSPARENCY",		/*	96 */ 
"TRAY1",		/*	97 */ 
"TRAY2",		/*	98 */ 
"TRAY3",		/*	99 */ 
"TRAY4",		/*	100 */ 
"TRUE",		/*	101 */ 
"UEL",		/*	102 */ 
"UPPER",		/*	103 */ 
"USTATUS",		/*	104 */ 
"USTATUSOFF",		/*	105 */ 
"VARIABLES",		/*	106 */ 
"VERBOSE",		/*	107 */ 
"VERYTHICK",		/*	108 */ 
"VINYLLABEL",		/*	109 */
"LJOBINFO",		/*	110 */
"RECYCLED",		/*	111 */
"SINDOHUSERNAME",	/*	112 */
"LETTERHEAD",
	((void *)0L)
};
