# ============================================================================
# Copyright (c) 2009-2011 Marvell Semiconductor, Inc. All Rights Reserved
#                      
#                         Marvell Confidential
# ============================================================================

 
#Include master environment
include $(BUILD_ROOT)/project.mk

INCFLAGS = -I./src -I./tests -I./include -I$(BUILD_ROOT)/$(GLOBAL_INCLUDE) 

INSTALL_SRC = print_mode_api.h print_mode_typedef.h
CONFIG_SRC = 
INSTALL_SRC_DIR = include
CONFIG_SRC_DIR = 
INSTALL_DEST_DIR = $(BUILD_ROOT)/$(GLOBAL_INCLUDE)


MODULE_LIB_TARGET = ./lib/libprint_le_$(TYPE).a
MODULE_LIB_DIR = ./lib

#  objects to build:    
SOURCE =  


include $(BUILD_ROOT)/stdtargets.mk
