# ============================================================================
# Copyright (c) 2009-2010 Marvell Semiconductor, Inc. All Rights Reserved
#                      
#                         Marvell Confidential
# ============================================================================


#Include master environment
BUILD_ROOT = ../..
include $(BUILD_ROOT)/project.mk

INCFLAGS = -I. -I$(BUILD_ROOT)/$(GLOBAL_INCLUDE)

INSTALL_SRC = ATypes.h error_types.h fwVersion.h lassert.h spec.h
INSTALL_SRC_DIR = .
INSTALL_DEST_DIR = $(BUILD_ROOT)/$(GLOBAL_INCLUDE)



SOURCE =

include $(BUILD_ROOT)/stdtargets.mk

