#define I2C_DEV_NAME		"/dev/i2cdev"
#define I2C_MAJOR_NUM		238

#define IOCTL_MAGIC			0xE000
#define	TRAY_ADDRESS		0x10
#define	SMARTCHIP_ADDRESS	0x20

#define SYNC				1
#define NOSYNC				0

#if 1 /* [KSF050201] */

#define SMARTIC_DEVICE				"/dev/i2c-0"
#define SMARTIC_ADDR 				(0x20 >> 1)

#endif

enum
{
	CMD_WRITE_TRAY				= IOCTL_MAGIC | 0,
	CMD_READ_TRAY				= IOCTL_MAGIC | 1,
	CMD_WRITE_SMARTIC_MEMORY	= IOCTL_MAGIC | 2,
	CMD_WRITE_SMARTIC_CERTKEY	= IOCTL_MAGIC | 3,
	CMD_READ_SMARTIC_MEMORY		= IOCTL_MAGIC | 4,
	CMD_READ_SMARTIC_CERTKEY	= IOCTL_MAGIC | 5,
	CMD_SYNC_TRAY				= IOCTL_MAGIC | 6,
	CMD_I2C_LAST				= IOCTL_MAGIC | 7,
};
