 /*
 **************************************************************************************
 *
 * Copyright (c) 2010 Marvell International, Ltd.
 *
 **************************************************************************************
 *
 * Marvell Commercial License Option
 *
 * If you received this File from Marvell as part of a proprietary software release,
 * the File is considered Marvell Proprietary and Confidential Information, and is
 * licensed to you under the terms of the applicable Commercial License.
 *
 **************************************************************************************
 *
 * Marvell GPL License Option
 *
 * If you received this File from Marvell as part of a Linux distribution, this File
 * is licensed to you in accordance with the terms and conditions of the General Public
 * License Version 2, June 1991 (the "GPL License").  You can redistribute it and/or
 * modify it under the terms of the GPL License; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GPL License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this
 * program.  If not, see http://www.gnu.org/licenses/.
 *
 **************************************************************************************
 *
 * \file GALVO_regmasks.h
 * Generated using RegBuild 1.6.1
 *
 *************************************************************************
 */

#ifndef _GALVO_REGMASKS_H_
#define _GALVO_REGMASKS_H_

#include <stdint.h>

//====================================================================
//
//Register File: GALVO (GALVO)
//
//====================================================================

//====================================================================
//Register: Galvo Digital Synthesis Control  (gv_dsscntl)
//====================================================================

#define  GALVO_GV_DSSCNTL_RESERVED1_MASK 0xfffe0000
#define  GALVO_GV_DSSCNTL_RESERVED1_SHIFT 17
#define  GALVO_GV_DSSCNTL_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_RESERVED1_MASK) >> GALVO_GV_DSSCNTL_RESERVED1_SHIFT)
#define  GALVO_GV_DSSCNTL_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_RESERVED1_SHIFT))

#define  GALVO_GV_DSSCNTL_REJECTRST_MASK 0x10000
#define  GALVO_GV_DSSCNTL_REJECTRST_SHIFT 16
#define  GALVO_GV_DSSCNTL_REJECTRST_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_REJECTRST_MASK) >> GALVO_GV_DSSCNTL_REJECTRST_SHIFT)
#define  GALVO_GV_DSSCNTL_REJECTRST_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_REJECTRST_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_REJECTRST_SHIFT))

#define  GALVO_GV_DSSCNTL_AL_REJECT_MASK 0x8000
#define  GALVO_GV_DSSCNTL_AL_REJECT_SHIFT 15
#define  GALVO_GV_DSSCNTL_AL_REJECT_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_AL_REJECT_MASK) >> GALVO_GV_DSSCNTL_AL_REJECT_SHIFT)
#define  GALVO_GV_DSSCNTL_AL_REJECT_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_AL_REJECT_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_AL_REJECT_SHIFT))

#define  GALVO_GV_DSSCNTL_H2_REJECT_MASK 0x4000
#define  GALVO_GV_DSSCNTL_H2_REJECT_SHIFT 14
#define  GALVO_GV_DSSCNTL_H2_REJECT_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_H2_REJECT_MASK) >> GALVO_GV_DSSCNTL_H2_REJECT_SHIFT)
#define  GALVO_GV_DSSCNTL_H2_REJECT_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_H2_REJECT_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_H2_REJECT_SHIFT))

#define  GALVO_GV_DSSCNTL_H1_REJECT_MASK 0x2000
#define  GALVO_GV_DSSCNTL_H1_REJECT_SHIFT 13
#define  GALVO_GV_DSSCNTL_H1_REJECT_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_H1_REJECT_MASK) >> GALVO_GV_DSSCNTL_H1_REJECT_SHIFT)
#define  GALVO_GV_DSSCNTL_H1_REJECT_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_H1_REJECT_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_H1_REJECT_SHIFT))

#define  GALVO_GV_DSSCNTL_SAFETYNET_MASK 0x1000
#define  GALVO_GV_DSSCNTL_SAFETYNET_SHIFT 12
#define  GALVO_GV_DSSCNTL_SAFETYNET_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_SAFETYNET_MASK) >> GALVO_GV_DSSCNTL_SAFETYNET_SHIFT)
#define  GALVO_GV_DSSCNTL_SAFETYNET_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_SAFETYNET_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_SAFETYNET_SHIFT))

#define  GALVO_GV_DSSCNTL_TRAINSIZE_MASK 0xc00
#define  GALVO_GV_DSSCNTL_TRAINSIZE_SHIFT 10
#define  GALVO_GV_DSSCNTL_TRAINSIZE_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_TRAINSIZE_MASK) >> GALVO_GV_DSSCNTL_TRAINSIZE_SHIFT)
#define  GALVO_GV_DSSCNTL_TRAINSIZE_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_TRAINSIZE_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_TRAINSIZE_SHIFT))

#define  GALVO_GV_DSSCNTL_GPT_TB_MASK 0x300
#define  GALVO_GV_DSSCNTL_GPT_TB_SHIFT 8
#define  GALVO_GV_DSSCNTL_GPT_TB_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_GPT_TB_MASK) >> GALVO_GV_DSSCNTL_GPT_TB_SHIFT)
#define  GALVO_GV_DSSCNTL_GPT_TB_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_GPT_TB_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_GPT_TB_SHIFT))

#define  GALVO_GV_DSSCNTL_OFFLEVEL_MASK 0x80
#define  GALVO_GV_DSSCNTL_OFFLEVEL_SHIFT 7
#define  GALVO_GV_DSSCNTL_OFFLEVEL_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_OFFLEVEL_MASK) >> GALVO_GV_DSSCNTL_OFFLEVEL_SHIFT)
#define  GALVO_GV_DSSCNTL_OFFLEVEL_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_OFFLEVEL_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_OFFLEVEL_SHIFT))

#define  GALVO_GV_DSSCNTL_NOFILT_MASK 0x40
#define  GALVO_GV_DSSCNTL_NOFILT_SHIFT 6
#define  GALVO_GV_DSSCNTL_NOFILT_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_NOFILT_MASK) >> GALVO_GV_DSSCNTL_NOFILT_SHIFT)
#define  GALVO_GV_DSSCNTL_NOFILT_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_NOFILT_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_NOFILT_SHIFT))

#define  GALVO_GV_DSSCNTL_FILT_TB_MASK 0x30
#define  GALVO_GV_DSSCNTL_FILT_TB_SHIFT 4
#define  GALVO_GV_DSSCNTL_FILT_TB_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_FILT_TB_MASK) >> GALVO_GV_DSSCNTL_FILT_TB_SHIFT)
#define  GALVO_GV_DSSCNTL_FILT_TB_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_FILT_TB_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_FILT_TB_SHIFT))

#define  GALVO_GV_DSSCNTL_ONCEMODE_MASK 0x8
#define  GALVO_GV_DSSCNTL_ONCEMODE_SHIFT 3
#define  GALVO_GV_DSSCNTL_ONCEMODE_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_ONCEMODE_MASK) >> GALVO_GV_DSSCNTL_ONCEMODE_SHIFT)
#define  GALVO_GV_DSSCNTL_ONCEMODE_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_ONCEMODE_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_ONCEMODE_SHIFT))

#define  GALVO_GV_DSSCNTL_DSSEN_MASK 0x4
#define  GALVO_GV_DSSCNTL_DSSEN_SHIFT 2
#define  GALVO_GV_DSSCNTL_DSSEN_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_DSSEN_MASK) >> GALVO_GV_DSSCNTL_DSSEN_SHIFT)
#define  GALVO_GV_DSSCNTL_DSSEN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_DSSEN_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_DSSEN_SHIFT))

#define  GALVO_GV_DSSCNTL_DSS_TB_MASK 0x3
#define  GALVO_GV_DSSCNTL_DSS_TB_SHIFT 0
#define  GALVO_GV_DSSCNTL_DSS_TB_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSCNTL_DSS_TB_MASK) >> GALVO_GV_DSSCNTL_DSS_TB_SHIFT)
#define  GALVO_GV_DSSCNTL_DSS_TB_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSCNTL_DSS_TB_MASK) | (((uint32_t)val) << GALVO_GV_DSSCNTL_DSS_TB_SHIFT))

//====================================================================
//Register: Digital Synthesis Adder (gv_dssadder)
//====================================================================

#define  GALVO_GV_DSSADDER_RESERVED1_MASK 0xfff00000
#define  GALVO_GV_DSSADDER_RESERVED1_SHIFT 20
#define  GALVO_GV_DSSADDER_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSADDER_RESERVED1_MASK) >> GALVO_GV_DSSADDER_RESERVED1_SHIFT)
#define  GALVO_GV_DSSADDER_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSADDER_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_DSSADDER_RESERVED1_SHIFT))

#define  GALVO_GV_DSSADDER_DSSADDER_MASK 0xfffff
#define  GALVO_GV_DSSADDER_DSSADDER_SHIFT 0
#define  GALVO_GV_DSSADDER_DSSADDER_MASK_SHIFT(reg) (((reg) & GALVO_GV_DSSADDER_DSSADDER_MASK) >> GALVO_GV_DSSADDER_DSSADDER_SHIFT)
#define  GALVO_GV_DSSADDER_DSSADDER_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DSSADDER_DSSADDER_MASK) | (((uint32_t)val) << GALVO_GV_DSSADDER_DSSADDER_SHIFT))

//====================================================================
//Register: Galvo Time Info (gv_timeinfo)
//====================================================================

#define  GALVO_GV_TIMEINFO_PHASETIME_MASK 0xffff0000
#define  GALVO_GV_TIMEINFO_PHASETIME_SHIFT 16
#define  GALVO_GV_TIMEINFO_PHASETIME_MASK_SHIFT(reg) (((reg) & GALVO_GV_TIMEINFO_PHASETIME_MASK) >> GALVO_GV_TIMEINFO_PHASETIME_SHIFT)
#define  GALVO_GV_TIMEINFO_PHASETIME_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_TIMEINFO_PHASETIME_MASK) | (((uint32_t)val) << GALVO_GV_TIMEINFO_PHASETIME_SHIFT))

#define  GALVO_GV_TIMEINFO_CAPTIME_MASK 0xffff
#define  GALVO_GV_TIMEINFO_CAPTIME_SHIFT 0
#define  GALVO_GV_TIMEINFO_CAPTIME_MASK_SHIFT(reg) (((reg) & GALVO_GV_TIMEINFO_CAPTIME_MASK) >> GALVO_GV_TIMEINFO_CAPTIME_SHIFT)
#define  GALVO_GV_TIMEINFO_CAPTIME_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_TIMEINFO_CAPTIME_MASK) | (((uint32_t)val) << GALVO_GV_TIMEINFO_CAPTIME_SHIFT))

//====================================================================
//Register: Galvo Drive Limit (gv_drvlimit)
//====================================================================

#define  GALVO_GV_DRVLIMIT_DRV_MIN_MASK 0xffff0000
#define  GALVO_GV_DRVLIMIT_DRV_MIN_SHIFT 16
#define  GALVO_GV_DRVLIMIT_DRV_MIN_MASK_SHIFT(reg) (((reg) & GALVO_GV_DRVLIMIT_DRV_MIN_MASK) >> GALVO_GV_DRVLIMIT_DRV_MIN_SHIFT)
#define  GALVO_GV_DRVLIMIT_DRV_MIN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DRVLIMIT_DRV_MIN_MASK) | (((uint32_t)val) << GALVO_GV_DRVLIMIT_DRV_MIN_SHIFT))

#define  GALVO_GV_DRVLIMIT_DRV_MAX_MASK 0xffff
#define  GALVO_GV_DRVLIMIT_DRV_MAX_SHIFT 0
#define  GALVO_GV_DRVLIMIT_DRV_MAX_MASK_SHIFT(reg) (((reg) & GALVO_GV_DRVLIMIT_DRV_MAX_MASK) >> GALVO_GV_DRVLIMIT_DRV_MAX_SHIFT)
#define  GALVO_GV_DRVLIMIT_DRV_MAX_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_DRVLIMIT_DRV_MAX_MASK) | (((uint32_t)val) << GALVO_GV_DRVLIMIT_DRV_MAX_SHIFT))

//====================================================================
//Register: Galvo Profile Ram (gv_profram)
//====================================================================

#define  GALVO_GV_PROFRAM_RESERVED1_MASK 0xffe00000
#define  GALVO_GV_PROFRAM_RESERVED1_SHIFT 21
#define  GALVO_GV_PROFRAM_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PROFRAM_RESERVED1_MASK) >> GALVO_GV_PROFRAM_RESERVED1_SHIFT)
#define  GALVO_GV_PROFRAM_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PROFRAM_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_PROFRAM_RESERVED1_SHIFT))

#define  GALVO_GV_PROFRAM_PROFADDR_MASK 0x1f0000
#define  GALVO_GV_PROFRAM_PROFADDR_SHIFT 16
#define  GALVO_GV_PROFRAM_PROFADDR_MASK_SHIFT(reg) (((reg) & GALVO_GV_PROFRAM_PROFADDR_MASK) >> GALVO_GV_PROFRAM_PROFADDR_SHIFT)
#define  GALVO_GV_PROFRAM_PROFADDR_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PROFRAM_PROFADDR_MASK) | (((uint32_t)val) << GALVO_GV_PROFRAM_PROFADDR_SHIFT))

#define  GALVO_GV_PROFRAM_RESERVED2_MASK 0xc000
#define  GALVO_GV_PROFRAM_RESERVED2_SHIFT 14
#define  GALVO_GV_PROFRAM_RESERVED2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PROFRAM_RESERVED2_MASK) >> GALVO_GV_PROFRAM_RESERVED2_SHIFT)
#define  GALVO_GV_PROFRAM_RESERVED2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PROFRAM_RESERVED2_MASK) | (((uint32_t)val) << GALVO_GV_PROFRAM_RESERVED2_SHIFT))

#define  GALVO_GV_PROFRAM_PROFNOM_MASK 0x3fff
#define  GALVO_GV_PROFRAM_PROFNOM_SHIFT 0
#define  GALVO_GV_PROFRAM_PROFNOM_MASK_SHIFT(reg) (((reg) & GALVO_GV_PROFRAM_PROFNOM_MASK) >> GALVO_GV_PROFRAM_PROFNOM_SHIFT)
#define  GALVO_GV_PROFRAM_PROFNOM_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PROFRAM_PROFNOM_MASK) | (((uint32_t)val) << GALVO_GV_PROFRAM_PROFNOM_SHIFT))

//====================================================================
//Register: Galvo Pulse Width Control (gv_pwcntl)
//====================================================================

#define  GALVO_GV_PWCNTL_PW_HW_MASK 0xffff0000
#define  GALVO_GV_PWCNTL_PW_HW_SHIFT 16
#define  GALVO_GV_PWCNTL_PW_HW_MASK_SHIFT(reg) (((reg) & GALVO_GV_PWCNTL_PW_HW_MASK) >> GALVO_GV_PWCNTL_PW_HW_SHIFT)
#define  GALVO_GV_PWCNTL_PW_HW_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PWCNTL_PW_HW_MASK) | (((uint32_t)val) << GALVO_GV_PWCNTL_PW_HW_SHIFT))

#define  GALVO_GV_PWCNTL_WDEN_MASK 0x8000
#define  GALVO_GV_PWCNTL_WDEN_SHIFT 15
#define  GALVO_GV_PWCNTL_WDEN_MASK_SHIFT(reg) (((reg) & GALVO_GV_PWCNTL_WDEN_MASK) >> GALVO_GV_PWCNTL_WDEN_SHIFT)
#define  GALVO_GV_PWCNTL_WDEN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PWCNTL_WDEN_MASK) | (((uint32_t)val) << GALVO_GV_PWCNTL_WDEN_SHIFT))

#define  GALVO_GV_PWCNTL_WDRESET_MASK 0x4000
#define  GALVO_GV_PWCNTL_WDRESET_SHIFT 14
#define  GALVO_GV_PWCNTL_WDRESET_MASK_SHIFT(reg) (((reg) & GALVO_GV_PWCNTL_WDRESET_MASK) >> GALVO_GV_PWCNTL_WDRESET_SHIFT)
#define  GALVO_GV_PWCNTL_WDRESET_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PWCNTL_WDRESET_MASK) | (((uint32_t)val) << GALVO_GV_PWCNTL_WDRESET_SHIFT))

#define  GALVO_GV_PWCNTL_WDTRIP_MASK 0x2000
#define  GALVO_GV_PWCNTL_WDTRIP_SHIFT 13
#define  GALVO_GV_PWCNTL_WDTRIP_MASK_SHIFT(reg) (((reg) & GALVO_GV_PWCNTL_WDTRIP_MASK) >> GALVO_GV_PWCNTL_WDTRIP_SHIFT)
#define  GALVO_GV_PWCNTL_WDTRIP_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PWCNTL_WDTRIP_MASK) | (((uint32_t)val) << GALVO_GV_PWCNTL_WDTRIP_SHIFT))

#define  GALVO_GV_PWCNTL_WDLIMIT_MASK 0x1f00
#define  GALVO_GV_PWCNTL_WDLIMIT_SHIFT 8
#define  GALVO_GV_PWCNTL_WDLIMIT_MASK_SHIFT(reg) (((reg) & GALVO_GV_PWCNTL_WDLIMIT_MASK) >> GALVO_GV_PWCNTL_WDLIMIT_SHIFT)
#define  GALVO_GV_PWCNTL_WDLIMIT_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PWCNTL_WDLIMIT_MASK) | (((uint32_t)val) << GALVO_GV_PWCNTL_WDLIMIT_SHIFT))

#define  GALVO_GV_PWCNTL_GATE_PI_MASK 0x80
#define  GALVO_GV_PWCNTL_GATE_PI_SHIFT 7
#define  GALVO_GV_PWCNTL_GATE_PI_MASK_SHIFT(reg) (((reg) & GALVO_GV_PWCNTL_GATE_PI_MASK) >> GALVO_GV_PWCNTL_GATE_PI_SHIFT)
#define  GALVO_GV_PWCNTL_GATE_PI_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PWCNTL_GATE_PI_MASK) | (((uint32_t)val) << GALVO_GV_PWCNTL_GATE_PI_SHIFT))

#define  GALVO_GV_PWCNTL_HOLD_PI_MASK 0x40
#define  GALVO_GV_PWCNTL_HOLD_PI_SHIFT 6
#define  GALVO_GV_PWCNTL_HOLD_PI_MASK_SHIFT(reg) (((reg) & GALVO_GV_PWCNTL_HOLD_PI_MASK) >> GALVO_GV_PWCNTL_HOLD_PI_SHIFT)
#define  GALVO_GV_PWCNTL_HOLD_PI_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PWCNTL_HOLD_PI_MASK) | (((uint32_t)val) << GALVO_GV_PWCNTL_HOLD_PI_SHIFT))

#define  GALVO_GV_PWCNTL_PW_EN_MASK 0x20
#define  GALVO_GV_PWCNTL_PW_EN_SHIFT 5
#define  GALVO_GV_PWCNTL_PW_EN_MASK_SHIFT(reg) (((reg) & GALVO_GV_PWCNTL_PW_EN_MASK) >> GALVO_GV_PWCNTL_PW_EN_SHIFT)
#define  GALVO_GV_PWCNTL_PW_EN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PWCNTL_PW_EN_MASK) | (((uint32_t)val) << GALVO_GV_PWCNTL_PW_EN_SHIFT))

#define  GALVO_GV_PWCNTL_PEGRESET_MASK 0x10
#define  GALVO_GV_PWCNTL_PEGRESET_SHIFT 4
#define  GALVO_GV_PWCNTL_PEGRESET_MASK_SHIFT(reg) (((reg) & GALVO_GV_PWCNTL_PEGRESET_MASK) >> GALVO_GV_PWCNTL_PEGRESET_SHIFT)
#define  GALVO_GV_PWCNTL_PEGRESET_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PWCNTL_PEGRESET_MASK) | (((uint32_t)val) << GALVO_GV_PWCNTL_PEGRESET_SHIFT))

#define  GALVO_GV_PWCNTL_PW_PG_R_MASK 0xc
#define  GALVO_GV_PWCNTL_PW_PG_R_SHIFT 2
#define  GALVO_GV_PWCNTL_PW_PG_R_MASK_SHIFT(reg) (((reg) & GALVO_GV_PWCNTL_PW_PG_R_MASK) >> GALVO_GV_PWCNTL_PW_PG_R_SHIFT)
#define  GALVO_GV_PWCNTL_PW_PG_R_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PWCNTL_PW_PG_R_MASK) | (((uint32_t)val) << GALVO_GV_PWCNTL_PW_PG_R_SHIFT))

#define  GALVO_GV_PWCNTL_PW_PG_F_MASK 0x3
#define  GALVO_GV_PWCNTL_PW_PG_F_SHIFT 0
#define  GALVO_GV_PWCNTL_PW_PG_F_MASK_SHIFT(reg) (((reg) & GALVO_GV_PWCNTL_PW_PG_F_MASK) >> GALVO_GV_PWCNTL_PW_PG_F_SHIFT)
#define  GALVO_GV_PWCNTL_PW_PG_F_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PWCNTL_PW_PG_F_MASK) | (((uint32_t)val) << GALVO_GV_PWCNTL_PW_PG_F_SHIFT))

//====================================================================
//Register: Galvo Alignment Control  (gv_aligncntl)
//====================================================================

#define  GALVO_GV_ALIGNCNTL_ALIGNEN_MASK 0x80000000
#define  GALVO_GV_ALIGNCNTL_ALIGNEN_SHIFT 31
#define  GALVO_GV_ALIGNCNTL_ALIGNEN_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGNCNTL_ALIGNEN_MASK) >> GALVO_GV_ALIGNCNTL_ALIGNEN_SHIFT)
#define  GALVO_GV_ALIGNCNTL_ALIGNEN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGNCNTL_ALIGNEN_MASK) | (((uint32_t)val) << GALVO_GV_ALIGNCNTL_ALIGNEN_SHIFT))

#define  GALVO_GV_ALIGNCNTL_ALSTART_MASK 0x70000000
#define  GALVO_GV_ALIGNCNTL_ALSTART_SHIFT 28
#define  GALVO_GV_ALIGNCNTL_ALSTART_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGNCNTL_ALSTART_MASK) >> GALVO_GV_ALIGNCNTL_ALSTART_SHIFT)
#define  GALVO_GV_ALIGNCNTL_ALSTART_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGNCNTL_ALSTART_MASK) | (((uint32_t)val) << GALVO_GV_ALIGNCNTL_ALSTART_SHIFT))

#define  GALVO_GV_ALIGNCNTL_ALSLCT_MASK 0xc000000
#define  GALVO_GV_ALIGNCNTL_ALSLCT_SHIFT 26
#define  GALVO_GV_ALIGNCNTL_ALSLCT_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGNCNTL_ALSLCT_MASK) >> GALVO_GV_ALIGNCNTL_ALSLCT_SHIFT)
#define  GALVO_GV_ALIGNCNTL_ALSLCT_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGNCNTL_ALSLCT_MASK) | (((uint32_t)val) << GALVO_GV_ALIGNCNTL_ALSLCT_SHIFT))

#define  GALVO_GV_ALIGNCNTL_VIDWIDTH_MASK 0x3ff0000
#define  GALVO_GV_ALIGNCNTL_VIDWIDTH_SHIFT 16
#define  GALVO_GV_ALIGNCNTL_VIDWIDTH_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGNCNTL_VIDWIDTH_MASK) >> GALVO_GV_ALIGNCNTL_VIDWIDTH_SHIFT)
#define  GALVO_GV_ALIGNCNTL_VIDWIDTH_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGNCNTL_VIDWIDTH_MASK) | (((uint32_t)val) << GALVO_GV_ALIGNCNTL_VIDWIDTH_SHIFT))

#define  GALVO_GV_ALIGNCNTL_VIDDELAY_MASK 0xffff
#define  GALVO_GV_ALIGNCNTL_VIDDELAY_SHIFT 0
#define  GALVO_GV_ALIGNCNTL_VIDDELAY_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGNCNTL_VIDDELAY_MASK) >> GALVO_GV_ALIGNCNTL_VIDDELAY_SHIFT)
#define  GALVO_GV_ALIGNCNTL_VIDDELAY_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGNCNTL_VIDDELAY_MASK) | (((uint32_t)val) << GALVO_GV_ALIGNCNTL_VIDDELAY_SHIFT))

//====================================================================
//Register: Galvo Alignment Feedback  (gv_align_fb)
//====================================================================

#define  GALVO_GV_ALIGN_FB_RESERVED1_MASK 0xfe000000
#define  GALVO_GV_ALIGN_FB_RESERVED1_SHIFT 25
#define  GALVO_GV_ALIGN_FB_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_FB_RESERVED1_MASK) >> GALVO_GV_ALIGN_FB_RESERVED1_SHIFT)
#define  GALVO_GV_ALIGN_FB_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_FB_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_FB_RESERVED1_SHIFT))

#define  GALVO_GV_ALIGN_FB_NUMFAKES_MASK 0x1ff0000
#define  GALVO_GV_ALIGN_FB_NUMFAKES_SHIFT 16
#define  GALVO_GV_ALIGN_FB_NUMFAKES_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_FB_NUMFAKES_MASK) >> GALVO_GV_ALIGN_FB_NUMFAKES_SHIFT)
#define  GALVO_GV_ALIGN_FB_NUMFAKES_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_FB_NUMFAKES_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_FB_NUMFAKES_SHIFT))

#define  GALVO_GV_ALIGN_FB_RESERVED2_MASK 0xfc00
#define  GALVO_GV_ALIGN_FB_RESERVED2_SHIFT 10
#define  GALVO_GV_ALIGN_FB_RESERVED2_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_FB_RESERVED2_MASK) >> GALVO_GV_ALIGN_FB_RESERVED2_SHIFT)
#define  GALVO_GV_ALIGN_FB_RESERVED2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_FB_RESERVED2_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_FB_RESERVED2_SHIFT))

#define  GALVO_GV_ALIGN_FB_ALIGN_FB_MASK 0x3ff
#define  GALVO_GV_ALIGN_FB_ALIGN_FB_SHIFT 0
#define  GALVO_GV_ALIGN_FB_ALIGN_FB_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_FB_ALIGN_FB_MASK) >> GALVO_GV_ALIGN_FB_ALIGN_FB_SHIFT)
#define  GALVO_GV_ALIGN_FB_ALIGN_FB_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_FB_ALIGN_FB_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_FB_ALIGN_FB_SHIFT))

//====================================================================
//Register: Galvo Miscellaneous Control (gv_align_misccntl)
//====================================================================

#define  GALVO_GV_ALIGN_MISCCNTL_DRV_EN_MASK 0x80000000
#define  GALVO_GV_ALIGN_MISCCNTL_DRV_EN_SHIFT 31
#define  GALVO_GV_ALIGN_MISCCNTL_DRV_EN_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_MISCCNTL_DRV_EN_MASK) >> GALVO_GV_ALIGN_MISCCNTL_DRV_EN_SHIFT)
#define  GALVO_GV_ALIGN_MISCCNTL_DRV_EN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_MISCCNTL_DRV_EN_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_MISCCNTL_DRV_EN_SHIFT))

#define  GALVO_GV_ALIGN_MISCCNTL_LEMASKEN_MASK 0x40000000
#define  GALVO_GV_ALIGN_MISCCNTL_LEMASKEN_SHIFT 30
#define  GALVO_GV_ALIGN_MISCCNTL_LEMASKEN_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_MISCCNTL_LEMASKEN_MASK) >> GALVO_GV_ALIGN_MISCCNTL_LEMASKEN_SHIFT)
#define  GALVO_GV_ALIGN_MISCCNTL_LEMASKEN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_MISCCNTL_LEMASKEN_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_MISCCNTL_LEMASKEN_SHIFT))

#define  GALVO_GV_ALIGN_MISCCNTL_PHZSTOP_MASK 0x38000000
#define  GALVO_GV_ALIGN_MISCCNTL_PHZSTOP_SHIFT 27
#define  GALVO_GV_ALIGN_MISCCNTL_PHZSTOP_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_MISCCNTL_PHZSTOP_MASK) >> GALVO_GV_ALIGN_MISCCNTL_PHZSTOP_SHIFT)
#define  GALVO_GV_ALIGN_MISCCNTL_PHZSTOP_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_MISCCNTL_PHZSTOP_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_MISCCNTL_PHZSTOP_SHIFT))

#define  GALVO_GV_ALIGN_MISCCNTL_PHZSTART_MASK 0x7000000
#define  GALVO_GV_ALIGN_MISCCNTL_PHZSTART_SHIFT 24
#define  GALVO_GV_ALIGN_MISCCNTL_PHZSTART_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_MISCCNTL_PHZSTART_MASK) >> GALVO_GV_ALIGN_MISCCNTL_PHZSTART_SHIFT)
#define  GALVO_GV_ALIGN_MISCCNTL_PHZSTART_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_MISCCNTL_PHZSTART_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_MISCCNTL_PHZSTART_SHIFT))

#define  GALVO_GV_ALIGN_MISCCNTL_DBGSLCT_MASK 0xf00000
#define  GALVO_GV_ALIGN_MISCCNTL_DBGSLCT_SHIFT 20
#define  GALVO_GV_ALIGN_MISCCNTL_DBGSLCT_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_MISCCNTL_DBGSLCT_MASK) >> GALVO_GV_ALIGN_MISCCNTL_DBGSLCT_SHIFT)
#define  GALVO_GV_ALIGN_MISCCNTL_DBGSLCT_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_MISCCNTL_DBGSLCT_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_MISCCNTL_DBGSLCT_SHIFT))

#define  GALVO_GV_ALIGN_MISCCNTL_DRVSLCT_MASK 0xc0000
#define  GALVO_GV_ALIGN_MISCCNTL_DRVSLCT_SHIFT 18
#define  GALVO_GV_ALIGN_MISCCNTL_DRVSLCT_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_MISCCNTL_DRVSLCT_MASK) >> GALVO_GV_ALIGN_MISCCNTL_DRVSLCT_SHIFT)
#define  GALVO_GV_ALIGN_MISCCNTL_DRVSLCT_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_MISCCNTL_DRVSLCT_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_MISCCNTL_DRVSLCT_SHIFT))

#define  GALVO_GV_ALIGN_MISCCNTL_CALC_TB_MASK 0x30000
#define  GALVO_GV_ALIGN_MISCCNTL_CALC_TB_SHIFT 16
#define  GALVO_GV_ALIGN_MISCCNTL_CALC_TB_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_MISCCNTL_CALC_TB_MASK) >> GALVO_GV_ALIGN_MISCCNTL_CALC_TB_SHIFT)
#define  GALVO_GV_ALIGN_MISCCNTL_CALC_TB_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_MISCCNTL_CALC_TB_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_MISCCNTL_CALC_TB_SHIFT))

#define  GALVO_GV_ALIGN_MISCCNTL_FAKEHDLY_MASK 0xffff
#define  GALVO_GV_ALIGN_MISCCNTL_FAKEHDLY_SHIFT 0
#define  GALVO_GV_ALIGN_MISCCNTL_FAKEHDLY_MASK_SHIFT(reg) (((reg) & GALVO_GV_ALIGN_MISCCNTL_FAKEHDLY_MASK) >> GALVO_GV_ALIGN_MISCCNTL_FAKEHDLY_SHIFT)
#define  GALVO_GV_ALIGN_MISCCNTL_FAKEHDLY_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ALIGN_MISCCNTL_FAKEHDLY_MASK) | (((uint32_t)val) << GALVO_GV_ALIGN_MISCCNTL_FAKEHDLY_SHIFT))

//====================================================================
//Register: Galvo XNOR Shift  (gv_xshifts)
//====================================================================

#define  GALVO_GV_XSHIFTS_RESERVED1_MASK 0xfffe0000
#define  GALVO_GV_XSHIFTS_RESERVED1_SHIFT 17
#define  GALVO_GV_XSHIFTS_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_XSHIFTS_RESERVED1_MASK) >> GALVO_GV_XSHIFTS_RESERVED1_SHIFT)
#define  GALVO_GV_XSHIFTS_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_XSHIFTS_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_XSHIFTS_RESERVED1_SHIFT))

#define  GALVO_GV_XSHIFTS_XSHIFTS_MASK 0x1ffff
#define  GALVO_GV_XSHIFTS_XSHIFTS_SHIFT 0
#define  GALVO_GV_XSHIFTS_XSHIFTS_MASK_SHIFT(reg) (((reg) & GALVO_GV_XSHIFTS_XSHIFTS_MASK) >> GALVO_GV_XSHIFTS_XSHIFTS_SHIFT)
#define  GALVO_GV_XSHIFTS_XSHIFTS_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_XSHIFTS_XSHIFTS_MASK) | (((uint32_t)val) << GALVO_GV_XSHIFTS_XSHIFTS_SHIFT))

//====================================================================
//Register: Galvo XNOR Count  (gv_xcount)
//====================================================================

#define  GALVO_GV_XCOUNT_RESERVED1_MASK 0xffe00000
#define  GALVO_GV_XCOUNT_RESERVED1_SHIFT 21
#define  GALVO_GV_XCOUNT_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_XCOUNT_RESERVED1_MASK) >> GALVO_GV_XCOUNT_RESERVED1_SHIFT)
#define  GALVO_GV_XCOUNT_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_XCOUNT_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_XCOUNT_RESERVED1_SHIFT))

#define  GALVO_GV_XCOUNT_XDONE_MASK 0x100000
#define  GALVO_GV_XCOUNT_XDONE_SHIFT 20
#define  GALVO_GV_XCOUNT_XDONE_MASK_SHIFT(reg) (((reg) & GALVO_GV_XCOUNT_XDONE_MASK) >> GALVO_GV_XCOUNT_XDONE_SHIFT)
#define  GALVO_GV_XCOUNT_XDONE_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_XCOUNT_XDONE_MASK) | (((uint32_t)val) << GALVO_GV_XCOUNT_XDONE_SHIFT))

#define  GALVO_GV_XCOUNT_RESERVED2_MASK 0xe0000
#define  GALVO_GV_XCOUNT_RESERVED2_SHIFT 17
#define  GALVO_GV_XCOUNT_RESERVED2_MASK_SHIFT(reg) (((reg) & GALVO_GV_XCOUNT_RESERVED2_MASK) >> GALVO_GV_XCOUNT_RESERVED2_SHIFT)
#define  GALVO_GV_XCOUNT_RESERVED2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_XCOUNT_RESERVED2_MASK) | (((uint32_t)val) << GALVO_GV_XCOUNT_RESERVED2_SHIFT))

#define  GALVO_GV_XCOUNT_XCOUNTER_MASK 0x1ffff
#define  GALVO_GV_XCOUNT_XCOUNTER_SHIFT 0
#define  GALVO_GV_XCOUNT_XCOUNTER_MASK_SHIFT(reg) (((reg) & GALVO_GV_XCOUNT_XCOUNTER_MASK) >> GALVO_GV_XCOUNT_XCOUNTER_SHIFT)
#define  GALVO_GV_XCOUNT_XCOUNTER_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_XCOUNT_XCOUNTER_MASK) | (((uint32_t)val) << GALVO_GV_XCOUNT_XCOUNTER_SHIFT))

//====================================================================
//Register:  (gv_simcntl)
//====================================================================

#define  GALVO_GV_SIMCNTL_RESERVED1_MASK 0xfffffff0
#define  GALVO_GV_SIMCNTL_RESERVED1_SHIFT 4
#define  GALVO_GV_SIMCNTL_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_SIMCNTL_RESERVED1_MASK) >> GALVO_GV_SIMCNTL_RESERVED1_SHIFT)
#define  GALVO_GV_SIMCNTL_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_SIMCNTL_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_SIMCNTL_RESERVED1_SHIFT))

#define  GALVO_GV_SIMCNTL_DRVMUX1_MASK 0xc
#define  GALVO_GV_SIMCNTL_DRVMUX1_SHIFT 2
#define  GALVO_GV_SIMCNTL_DRVMUX1_MASK_SHIFT(reg) (((reg) & GALVO_GV_SIMCNTL_DRVMUX1_MASK) >> GALVO_GV_SIMCNTL_DRVMUX1_SHIFT)
#define  GALVO_GV_SIMCNTL_DRVMUX1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_SIMCNTL_DRVMUX1_MASK) | (((uint32_t)val) << GALVO_GV_SIMCNTL_DRVMUX1_SHIFT))

#define  GALVO_GV_SIMCNTL_DRVMUX2_MASK 0x3
#define  GALVO_GV_SIMCNTL_DRVMUX2_SHIFT 0
#define  GALVO_GV_SIMCNTL_DRVMUX2_MASK_SHIFT(reg) (((reg) & GALVO_GV_SIMCNTL_DRVMUX2_MASK) >> GALVO_GV_SIMCNTL_DRVMUX2_SHIFT)
#define  GALVO_GV_SIMCNTL_DRVMUX2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_SIMCNTL_DRVMUX2_MASK) | (((uint32_t)val) << GALVO_GV_SIMCNTL_DRVMUX2_SHIFT))

//====================================================================
//Register: Galvo Capture Interval 0:1  (gv_cap0_1)
//====================================================================

#define  GALVO_GV_CAP0_1_CAP0_MASK 0xffff0000
#define  GALVO_GV_CAP0_1_CAP0_SHIFT 16
#define  GALVO_GV_CAP0_1_CAP0_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP0_1_CAP0_MASK) >> GALVO_GV_CAP0_1_CAP0_SHIFT)
#define  GALVO_GV_CAP0_1_CAP0_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP0_1_CAP0_MASK) | (((uint32_t)val) << GALVO_GV_CAP0_1_CAP0_SHIFT))

#define  GALVO_GV_CAP0_1_CAP1_MASK 0xffff
#define  GALVO_GV_CAP0_1_CAP1_SHIFT 0
#define  GALVO_GV_CAP0_1_CAP1_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP0_1_CAP1_MASK) >> GALVO_GV_CAP0_1_CAP1_SHIFT)
#define  GALVO_GV_CAP0_1_CAP1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP0_1_CAP1_MASK) | (((uint32_t)val) << GALVO_GV_CAP0_1_CAP1_SHIFT))

//====================================================================
//Register: Galvo Capture Interval 2:3 (gv_cap2_3)
//====================================================================

#define  GALVO_GV_CAP2_3_CAP2_MASK 0xffff0000
#define  GALVO_GV_CAP2_3_CAP2_SHIFT 16
#define  GALVO_GV_CAP2_3_CAP2_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP2_3_CAP2_MASK) >> GALVO_GV_CAP2_3_CAP2_SHIFT)
#define  GALVO_GV_CAP2_3_CAP2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP2_3_CAP2_MASK) | (((uint32_t)val) << GALVO_GV_CAP2_3_CAP2_SHIFT))

#define  GALVO_GV_CAP2_3_CAP3_MASK 0xffff
#define  GALVO_GV_CAP2_3_CAP3_SHIFT 0
#define  GALVO_GV_CAP2_3_CAP3_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP2_3_CAP3_MASK) >> GALVO_GV_CAP2_3_CAP3_SHIFT)
#define  GALVO_GV_CAP2_3_CAP3_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP2_3_CAP3_MASK) | (((uint32_t)val) << GALVO_GV_CAP2_3_CAP3_SHIFT))

//====================================================================
//Register: Galvo Control (galvcntl)
//====================================================================

#define  GALVO_GALVCNTL_RESERVED1_MASK 0xf8000000
#define  GALVO_GALVCNTL_RESERVED1_SHIFT 27
#define  GALVO_GALVCNTL_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_RESERVED1_MASK) >> GALVO_GALVCNTL_RESERVED1_SHIFT)
#define  GALVO_GALVCNTL_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_RESERVED1_SHIFT))

#define  GALVO_GALVCNTL_WR_STRETCH_MASK 0x4000000
#define  GALVO_GALVCNTL_WR_STRETCH_SHIFT 26
#define  GALVO_GALVCNTL_WR_STRETCH_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_WR_STRETCH_MASK) >> GALVO_GALVCNTL_WR_STRETCH_SHIFT)
#define  GALVO_GALVCNTL_WR_STRETCH_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_WR_STRETCH_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_WR_STRETCH_SHIFT))

#define  GALVO_GALVCNTL_NOFILT_MASK 0x2000000
#define  GALVO_GALVCNTL_NOFILT_SHIFT 25
#define  GALVO_GALVCNTL_NOFILT_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_NOFILT_MASK) >> GALVO_GALVCNTL_NOFILT_SHIFT)
#define  GALVO_GALVCNTL_NOFILT_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_NOFILT_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_NOFILT_SHIFT))

#define  GALVO_GALVCNTL_HPATERR_MASK 0x1000000
#define  GALVO_GALVCNTL_HPATERR_SHIFT 24
#define  GALVO_GALVCNTL_HPATERR_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_HPATERR_MASK) >> GALVO_GALVCNTL_HPATERR_SHIFT)
#define  GALVO_GALVCNTL_HPATERR_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_HPATERR_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_HPATERR_SHIFT))

#define  GALVO_GALVCNTL_RESERVED2_MASK 0x800000
#define  GALVO_GALVCNTL_RESERVED2_SHIFT 23
#define  GALVO_GALVCNTL_RESERVED2_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_RESERVED2_MASK) >> GALVO_GALVCNTL_RESERVED2_SHIFT)
#define  GALVO_GALVCNTL_RESERVED2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_RESERVED2_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_RESERVED2_SHIFT))

#define  GALVO_GALVCNTL_HCNTERR_MASK 0x400000
#define  GALVO_GALVCNTL_HCNTERR_SHIFT 22
#define  GALVO_GALVCNTL_HCNTERR_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_HCNTERR_MASK) >> GALVO_GALVCNTL_HCNTERR_SHIFT)
#define  GALVO_GALVCNTL_HCNTERR_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_HCNTERR_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_HCNTERR_SHIFT))

#define  GALVO_GALVCNTL_HERESET_MASK 0x200000
#define  GALVO_GALVCNTL_HERESET_SHIFT 21
#define  GALVO_GALVCNTL_HERESET_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_HERESET_MASK) >> GALVO_GALVCNTL_HERESET_SHIFT)
#define  GALVO_GALVCNTL_HERESET_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_HERESET_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_HERESET_SHIFT))

#define  GALVO_GALVCNTL_TWOSENSOR_MASK 0x100000
#define  GALVO_GALVCNTL_TWOSENSOR_SHIFT 20
#define  GALVO_GALVCNTL_TWOSENSOR_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_TWOSENSOR_MASK) >> GALVO_GALVCNTL_TWOSENSOR_SHIFT)
#define  GALVO_GALVCNTL_TWOSENSOR_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_TWOSENSOR_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_TWOSENSOR_SHIFT))

#define  GALVO_GALVCNTL_ASELA_MAP_MASK 0xe0000
#define  GALVO_GALVCNTL_ASELA_MAP_SHIFT 17
#define  GALVO_GALVCNTL_ASELA_MAP_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_ASELA_MAP_MASK) >> GALVO_GALVCNTL_ASELA_MAP_SHIFT)
#define  GALVO_GALVCNTL_ASELA_MAP_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_ASELA_MAP_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_ASELA_MAP_SHIFT))

#define  GALVO_GALVCNTL_RESERVED3_MASK 0x18000
#define  GALVO_GALVCNTL_RESERVED3_SHIFT 15
#define  GALVO_GALVCNTL_RESERVED3_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_RESERVED3_MASK) >> GALVO_GALVCNTL_RESERVED3_SHIFT)
#define  GALVO_GALVCNTL_RESERVED3_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_RESERVED3_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_RESERVED3_SHIFT))

#define  GALVO_GALVCNTL_AUTOSYNC_MASK 0x6000
#define  GALVO_GALVCNTL_AUTOSYNC_SHIFT 13
#define  GALVO_GALVCNTL_AUTOSYNC_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_AUTOSYNC_MASK) >> GALVO_GALVCNTL_AUTOSYNC_SHIFT)
#define  GALVO_GALVCNTL_AUTOSYNC_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_AUTOSYNC_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_AUTOSYNC_SHIFT))

#define  GALVO_GALVCNTL_RESERVED4_MASK 0x1000
#define  GALVO_GALVCNTL_RESERVED4_SHIFT 12
#define  GALVO_GALVCNTL_RESERVED4_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_RESERVED4_MASK) >> GALVO_GALVCNTL_RESERVED4_SHIFT)
#define  GALVO_GALVCNTL_RESERVED4_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_RESERVED4_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_RESERVED4_SHIFT))

#define  GALVO_GALVCNTL_OVFLCAP3_MASK 0x800
#define  GALVO_GALVCNTL_OVFLCAP3_SHIFT 11
#define  GALVO_GALVCNTL_OVFLCAP3_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_OVFLCAP3_MASK) >> GALVO_GALVCNTL_OVFLCAP3_SHIFT)
#define  GALVO_GALVCNTL_OVFLCAP3_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_OVFLCAP3_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_OVFLCAP3_SHIFT))

#define  GALVO_GALVCNTL_OVFLCAP2_MASK 0x400
#define  GALVO_GALVCNTL_OVFLCAP2_SHIFT 10
#define  GALVO_GALVCNTL_OVFLCAP2_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_OVFLCAP2_MASK) >> GALVO_GALVCNTL_OVFLCAP2_SHIFT)
#define  GALVO_GALVCNTL_OVFLCAP2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_OVFLCAP2_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_OVFLCAP2_SHIFT))

#define  GALVO_GALVCNTL_OVFLCAP1_MASK 0x200
#define  GALVO_GALVCNTL_OVFLCAP1_SHIFT 9
#define  GALVO_GALVCNTL_OVFLCAP1_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_OVFLCAP1_MASK) >> GALVO_GALVCNTL_OVFLCAP1_SHIFT)
#define  GALVO_GALVCNTL_OVFLCAP1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_OVFLCAP1_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_OVFLCAP1_SHIFT))

#define  GALVO_GALVCNTL_OVFLCAP0_MASK 0x100
#define  GALVO_GALVCNTL_OVFLCAP0_SHIFT 8
#define  GALVO_GALVCNTL_OVFLCAP0_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_OVFLCAP0_MASK) >> GALVO_GALVCNTL_OVFLCAP0_SHIFT)
#define  GALVO_GALVCNTL_OVFLCAP0_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_OVFLCAP0_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_OVFLCAP0_SHIFT))

#define  GALVO_GALVCNTL_SKIPSCAN_MASK 0xf0
#define  GALVO_GALVCNTL_SKIPSCAN_SHIFT 4
#define  GALVO_GALVCNTL_SKIPSCAN_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_SKIPSCAN_MASK) >> GALVO_GALVCNTL_SKIPSCAN_SHIFT)
#define  GALVO_GALVCNTL_SKIPSCAN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_SKIPSCAN_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_SKIPSCAN_SHIFT))

#define  GALVO_GALVCNTL_CLEARCAP_MASK 0x8
#define  GALVO_GALVCNTL_CLEARCAP_SHIFT 3
#define  GALVO_GALVCNTL_CLEARCAP_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_CLEARCAP_MASK) >> GALVO_GALVCNTL_CLEARCAP_SHIFT)
#define  GALVO_GALVCNTL_CLEARCAP_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_CLEARCAP_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_CLEARCAP_SHIFT))

#define  GALVO_GALVCNTL_SYNCCAP_MASK 0x4
#define  GALVO_GALVCNTL_SYNCCAP_SHIFT 2
#define  GALVO_GALVCNTL_SYNCCAP_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_SYNCCAP_MASK) >> GALVO_GALVCNTL_SYNCCAP_SHIFT)
#define  GALVO_GALVCNTL_SYNCCAP_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_SYNCCAP_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_SYNCCAP_SHIFT))

#define  GALVO_GALVCNTL_SYNCREG_MASK 0x3
#define  GALVO_GALVCNTL_SYNCREG_SHIFT 0
#define  GALVO_GALVCNTL_SYNCREG_MASK_SHIFT(reg) (((reg) & GALVO_GALVCNTL_SYNCREG_MASK) >> GALVO_GALVCNTL_SYNCREG_SHIFT)
#define  GALVO_GALVCNTL_SYNCREG_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GALVCNTL_SYNCREG_MASK) | (((uint32_t)val) << GALVO_GALVCNTL_SYNCREG_SHIFT))

//====================================================================
//Register: Galvo Laser Control 1  (gv_lascntl1)
//====================================================================

#define  GALVO_GV_LASCNTL1_RESERVED1_MASK 0xfffe0000
#define  GALVO_GV_LASCNTL1_RESERVED1_SHIFT 17
#define  GALVO_GV_LASCNTL1_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL1_RESERVED1_MASK) >> GALVO_GV_LASCNTL1_RESERVED1_SHIFT)
#define  GALVO_GV_LASCNTL1_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL1_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL1_RESERVED1_SHIFT))

#define  GALVO_GV_LASCNTL1_GMUXEN_MASK 0x10000
#define  GALVO_GV_LASCNTL1_GMUXEN_SHIFT 16
#define  GALVO_GV_LASCNTL1_GMUXEN_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL1_GMUXEN_MASK) >> GALVO_GV_LASCNTL1_GMUXEN_SHIFT)
#define  GALVO_GV_LASCNTL1_GMUXEN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL1_GMUXEN_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL1_GMUXEN_SHIFT))

#define  GALVO_GV_LASCNTL1_PRINTBIDI_MASK 0x8000
#define  GALVO_GV_LASCNTL1_PRINTBIDI_SHIFT 15
#define  GALVO_GV_LASCNTL1_PRINTBIDI_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL1_PRINTBIDI_MASK) >> GALVO_GV_LASCNTL1_PRINTBIDI_SHIFT)
#define  GALVO_GV_LASCNTL1_PRINTBIDI_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL1_PRINTBIDI_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL1_PRINTBIDI_SHIFT))

#define  GALVO_GV_LASCNTL1_GATEHSYNC_MASK 0x4000
#define  GALVO_GV_LASCNTL1_GATEHSYNC_SHIFT 14
#define  GALVO_GV_LASCNTL1_GATEHSYNC_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL1_GATEHSYNC_MASK) >> GALVO_GV_LASCNTL1_GATEHSYNC_SHIFT)
#define  GALVO_GV_LASCNTL1_GATEHSYNC_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL1_GATEHSYNC_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL1_GATEHSYNC_SHIFT))

#define  GALVO_GV_LASCNTL1_LASERON_MASK 0x2000
#define  GALVO_GV_LASCNTL1_LASERON_SHIFT 13
#define  GALVO_GV_LASCNTL1_LASERON_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL1_LASERON_MASK) >> GALVO_GV_LASCNTL1_LASERON_SHIFT)
#define  GALVO_GV_LASCNTL1_LASERON_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL1_LASERON_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL1_LASERON_SHIFT))

#define  GALVO_GV_LASCNTL1_TOGBOOST_MASK 0x1000
#define  GALVO_GV_LASCNTL1_TOGBOOST_SHIFT 12
#define  GALVO_GV_LASCNTL1_TOGBOOST_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL1_TOGBOOST_MASK) >> GALVO_GV_LASCNTL1_TOGBOOST_SHIFT)
#define  GALVO_GV_LASCNTL1_TOGBOOST_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL1_TOGBOOST_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL1_TOGBOOST_SHIFT))

#define  GALVO_GV_LASCNTL1_ZONE_EN_MASK 0x800
#define  GALVO_GV_LASCNTL1_ZONE_EN_SHIFT 11
#define  GALVO_GV_LASCNTL1_ZONE_EN_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL1_ZONE_EN_MASK) >> GALVO_GV_LASCNTL1_ZONE_EN_SHIFT)
#define  GALVO_GV_LASCNTL1_ZONE_EN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL1_ZONE_EN_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL1_ZONE_EN_SHIFT))

#define  GALVO_GV_LASCNTL1_QUALHSYNC_MASK 0x400
#define  GALVO_GV_LASCNTL1_QUALHSYNC_SHIFT 10
#define  GALVO_GV_LASCNTL1_QUALHSYNC_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL1_QUALHSYNC_MASK) >> GALVO_GV_LASCNTL1_QUALHSYNC_SHIFT)
#define  GALVO_GV_LASCNTL1_QUALHSYNC_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL1_QUALHSYNC_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL1_QUALHSYNC_SHIFT))

#define  GALVO_GV_LASCNTL1_SAMEHSYNC_MASK 0x200
#define  GALVO_GV_LASCNTL1_SAMEHSYNC_SHIFT 9
#define  GALVO_GV_LASCNTL1_SAMEHSYNC_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL1_SAMEHSYNC_MASK) >> GALVO_GV_LASCNTL1_SAMEHSYNC_SHIFT)
#define  GALVO_GV_LASCNTL1_SAMEHSYNC_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL1_SAMEHSYNC_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL1_SAMEHSYNC_SHIFT))

#define  GALVO_GV_LASCNTL1_RESERVED2_MASK 0x1f0
#define  GALVO_GV_LASCNTL1_RESERVED2_SHIFT 4
#define  GALVO_GV_LASCNTL1_RESERVED2_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL1_RESERVED2_MASK) >> GALVO_GV_LASCNTL1_RESERVED2_SHIFT)
#define  GALVO_GV_LASCNTL1_RESERVED2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL1_RESERVED2_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL1_RESERVED2_SHIFT))

#define  GALVO_GV_LASCNTL1_ZONEON_MASK 0xf
#define  GALVO_GV_LASCNTL1_ZONEON_SHIFT 0
#define  GALVO_GV_LASCNTL1_ZONEON_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL1_ZONEON_MASK) >> GALVO_GV_LASCNTL1_ZONEON_SHIFT)
#define  GALVO_GV_LASCNTL1_ZONEON_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL1_ZONEON_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL1_ZONEON_SHIFT))

//====================================================================
//Register: Galvo Laser Control 2  (gv_lascntl2)
//====================================================================

#define  GALVO_GV_LASCNTL2_ZONEEON_MASK 0xffff0000
#define  GALVO_GV_LASCNTL2_ZONEEON_SHIFT 16
#define  GALVO_GV_LASCNTL2_ZONEEON_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL2_ZONEEON_MASK) >> GALVO_GV_LASCNTL2_ZONEEON_SHIFT)
#define  GALVO_GV_LASCNTL2_ZONEEON_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL2_ZONEEON_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL2_ZONEEON_SHIFT))

#define  GALVO_GV_LASCNTL2_ZONEBOOST_MASK 0xffff
#define  GALVO_GV_LASCNTL2_ZONEBOOST_SHIFT 0
#define  GALVO_GV_LASCNTL2_ZONEBOOST_MASK_SHIFT(reg) (((reg) & GALVO_GV_LASCNTL2_ZONEBOOST_MASK) >> GALVO_GV_LASCNTL2_ZONEBOOST_SHIFT)
#define  GALVO_GV_LASCNTL2_ZONEBOOST_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_LASCNTL2_ZONEBOOST_MASK) | (((uint32_t)val) << GALVO_GV_LASCNTL2_ZONEBOOST_SHIFT))

//====================================================================
//Register: Galvo Interrupt Control (gv_girqcntl)
//====================================================================

#define  GALVO_GV_GIRQCNTL_RESERVED1_MASK 0xfffe0000
#define  GALVO_GV_GIRQCNTL_RESERVED1_SHIFT 17
#define  GALVO_GV_GIRQCNTL_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_GIRQCNTL_RESERVED1_MASK) >> GALVO_GV_GIRQCNTL_RESERVED1_SHIFT)
#define  GALVO_GV_GIRQCNTL_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_GIRQCNTL_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_GIRQCNTL_RESERVED1_SHIFT))

#define  GALVO_GV_GIRQCNTL_GIRQRST_MASK 0x10000
#define  GALVO_GV_GIRQCNTL_GIRQRST_SHIFT 16
#define  GALVO_GV_GIRQCNTL_GIRQRST_MASK_SHIFT(reg) (((reg) & GALVO_GV_GIRQCNTL_GIRQRST_MASK) >> GALVO_GV_GIRQCNTL_GIRQRST_SHIFT)
#define  GALVO_GV_GIRQCNTL_GIRQRST_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_GIRQCNTL_GIRQRST_MASK) | (((uint32_t)val) << GALVO_GV_GIRQCNTL_GIRQRST_SHIFT))

#define  GALVO_GV_GIRQCNTL_GIRQSRC_MASK 0xf000
#define  GALVO_GV_GIRQCNTL_GIRQSRC_SHIFT 12
#define  GALVO_GV_GIRQCNTL_GIRQSRC_MASK_SHIFT(reg) (((reg) & GALVO_GV_GIRQCNTL_GIRQSRC_MASK) >> GALVO_GV_GIRQCNTL_GIRQSRC_SHIFT)
#define  GALVO_GV_GIRQCNTL_GIRQSRC_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_GIRQCNTL_GIRQSRC_MASK) | (((uint32_t)val) << GALVO_GV_GIRQCNTL_GIRQSRC_SHIFT))

#define  GALVO_GV_GIRQCNTL_ZONEIRQ_MASK 0xf00
#define  GALVO_GV_GIRQCNTL_ZONEIRQ_SHIFT 8
#define  GALVO_GV_GIRQCNTL_ZONEIRQ_MASK_SHIFT(reg) (((reg) & GALVO_GV_GIRQCNTL_ZONEIRQ_MASK) >> GALVO_GV_GIRQCNTL_ZONEIRQ_SHIFT)
#define  GALVO_GV_GIRQCNTL_ZONEIRQ_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_GIRQCNTL_ZONEIRQ_MASK) | (((uint32_t)val) << GALVO_GV_GIRQCNTL_ZONEIRQ_SHIFT))

#define  GALVO_GV_GIRQCNTL_GIRQSKIP_MASK 0xff
#define  GALVO_GV_GIRQCNTL_GIRQSKIP_SHIFT 0
#define  GALVO_GV_GIRQCNTL_GIRQSKIP_MASK_SHIFT(reg) (((reg) & GALVO_GV_GIRQCNTL_GIRQSKIP_MASK) >> GALVO_GV_GIRQCNTL_GIRQSKIP_SHIFT)
#define  GALVO_GV_GIRQCNTL_GIRQSKIP_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_GIRQCNTL_GIRQSKIP_MASK) | (((uint32_t)val) << GALVO_GV_GIRQCNTL_GIRQSKIP_SHIFT))

//====================================================================
//Register:  (gv_zone_2_3)
//====================================================================

#define  GALVO_GV_ZONE_2_3_ZONE2_MASK 0xffff0000
#define  GALVO_GV_ZONE_2_3_ZONE2_SHIFT 16
#define  GALVO_GV_ZONE_2_3_ZONE2_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_2_3_ZONE2_MASK) >> GALVO_GV_ZONE_2_3_ZONE2_SHIFT)
#define  GALVO_GV_ZONE_2_3_ZONE2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_2_3_ZONE2_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_2_3_ZONE2_SHIFT))

#define  GALVO_GV_ZONE_2_3_ZONE3_MASK 0xffff
#define  GALVO_GV_ZONE_2_3_ZONE3_SHIFT 0
#define  GALVO_GV_ZONE_2_3_ZONE3_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_2_3_ZONE3_MASK) >> GALVO_GV_ZONE_2_3_ZONE3_SHIFT)
#define  GALVO_GV_ZONE_2_3_ZONE3_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_2_3_ZONE3_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_2_3_ZONE3_SHIFT))

//====================================================================
//Register:  (gv_zone_5_6)
//====================================================================

#define  GALVO_GV_ZONE_5_6_ZONE5_MASK 0xffff0000
#define  GALVO_GV_ZONE_5_6_ZONE5_SHIFT 16
#define  GALVO_GV_ZONE_5_6_ZONE5_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_5_6_ZONE5_MASK) >> GALVO_GV_ZONE_5_6_ZONE5_SHIFT)
#define  GALVO_GV_ZONE_5_6_ZONE5_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_5_6_ZONE5_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_5_6_ZONE5_SHIFT))

#define  GALVO_GV_ZONE_5_6_ZONE6_MASK 0xffff
#define  GALVO_GV_ZONE_5_6_ZONE6_SHIFT 0
#define  GALVO_GV_ZONE_5_6_ZONE6_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_5_6_ZONE6_MASK) >> GALVO_GV_ZONE_5_6_ZONE6_SHIFT)
#define  GALVO_GV_ZONE_5_6_ZONE6_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_5_6_ZONE6_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_5_6_ZONE6_SHIFT))

//====================================================================
//Register:  (gv_zone_C_4)
//====================================================================

#define  GALVO_GV_ZONE_C_4_ZONEC_MASK 0xffff0000
#define  GALVO_GV_ZONE_C_4_ZONEC_SHIFT 16
#define  GALVO_GV_ZONE_C_4_ZONEC_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_C_4_ZONEC_MASK) >> GALVO_GV_ZONE_C_4_ZONEC_SHIFT)
#define  GALVO_GV_ZONE_C_4_ZONEC_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_C_4_ZONEC_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_C_4_ZONEC_SHIFT))

#define  GALVO_GV_ZONE_C_4_ZONE4_MASK 0xffff
#define  GALVO_GV_ZONE_C_4_ZONE4_SHIFT 0
#define  GALVO_GV_ZONE_C_4_ZONE4_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_C_4_ZONE4_MASK) >> GALVO_GV_ZONE_C_4_ZONE4_SHIFT)
#define  GALVO_GV_ZONE_C_4_ZONE4_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_C_4_ZONE4_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_C_4_ZONE4_SHIFT))

//====================================================================
//Register:  (gv_zone_E_F)
//====================================================================

#define  GALVO_GV_ZONE_E_F_ZONEE_MASK 0xffff0000
#define  GALVO_GV_ZONE_E_F_ZONEE_SHIFT 16
#define  GALVO_GV_ZONE_E_F_ZONEE_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_E_F_ZONEE_MASK) >> GALVO_GV_ZONE_E_F_ZONEE_SHIFT)
#define  GALVO_GV_ZONE_E_F_ZONEE_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_E_F_ZONEE_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_E_F_ZONEE_SHIFT))

#define  GALVO_GV_ZONE_E_F_ZONEF_MASK 0xffff
#define  GALVO_GV_ZONE_E_F_ZONEF_SHIFT 0
#define  GALVO_GV_ZONE_E_F_ZONEF_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_E_F_ZONEF_MASK) >> GALVO_GV_ZONE_E_F_ZONEF_SHIFT)
#define  GALVO_GV_ZONE_E_F_ZONEF_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_E_F_ZONEF_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_E_F_ZONEF_SHIFT))

//====================================================================
//Register:  (gv_zone_9_A)
//====================================================================

#define  GALVO_GV_ZONE_9_A_ZONE9_MASK 0xffff0000
#define  GALVO_GV_ZONE_9_A_ZONE9_SHIFT 16
#define  GALVO_GV_ZONE_9_A_ZONE9_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_9_A_ZONE9_MASK) >> GALVO_GV_ZONE_9_A_ZONE9_SHIFT)
#define  GALVO_GV_ZONE_9_A_ZONE9_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_9_A_ZONE9_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_9_A_ZONE9_SHIFT))

#define  GALVO_GV_ZONE_9_A_ZONEA_MASK 0xffff
#define  GALVO_GV_ZONE_9_A_ZONEA_SHIFT 0
#define  GALVO_GV_ZONE_9_A_ZONEA_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_9_A_ZONEA_MASK) >> GALVO_GV_ZONE_9_A_ZONEA_SHIFT)
#define  GALVO_GV_ZONE_9_A_ZONEA_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_9_A_ZONEA_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_9_A_ZONEA_SHIFT))

//====================================================================
//Register:  (gv_zone_0_8)
//====================================================================

#define  GALVO_GV_ZONE_0_8_ZONE0_MASK 0xffff0000
#define  GALVO_GV_ZONE_0_8_ZONE0_SHIFT 16
#define  GALVO_GV_ZONE_0_8_ZONE0_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_0_8_ZONE0_MASK) >> GALVO_GV_ZONE_0_8_ZONE0_SHIFT)
#define  GALVO_GV_ZONE_0_8_ZONE0_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_0_8_ZONE0_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_0_8_ZONE0_SHIFT))

#define  GALVO_GV_ZONE_0_8_ZONE8_MASK 0xffff
#define  GALVO_GV_ZONE_0_8_ZONE8_SHIFT 0
#define  GALVO_GV_ZONE_0_8_ZONE8_MASK_SHIFT(reg) (((reg) & GALVO_GV_ZONE_0_8_ZONE8_MASK) >> GALVO_GV_ZONE_0_8_ZONE8_SHIFT)
#define  GALVO_GV_ZONE_0_8_ZONE8_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ZONE_0_8_ZONE8_MASK) | (((uint32_t)val) << GALVO_GV_ZONE_0_8_ZONE8_SHIFT))

//====================================================================
//Register:  (gv_adjwidth)
//====================================================================

#define  GALVO_GV_ADJWIDTH_RESERVED1_MASK 0xffffffff
#define  GALVO_GV_ADJWIDTH_RESERVED1_SHIFT 0
#define  GALVO_GV_ADJWIDTH_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_ADJWIDTH_RESERVED1_MASK) >> GALVO_GV_ADJWIDTH_RESERVED1_SHIFT)
#define  GALVO_GV_ADJWIDTH_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ADJWIDTH_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_ADJWIDTH_RESERVED1_SHIFT))

//====================================================================
//Register: Galvo Proportional Integral Control 1  (gv_picntl1)
//====================================================================

#define  GALVO_GV_PICNTL1_PI_SRAP1_MASK 0xf0000000
#define  GALVO_GV_PICNTL1_PI_SRAP1_SHIFT 28
#define  GALVO_GV_PICNTL1_PI_SRAP1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL1_PI_SRAP1_MASK) >> GALVO_GV_PICNTL1_PI_SRAP1_SHIFT)
#define  GALVO_GV_PICNTL1_PI_SRAP1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL1_PI_SRAP1_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL1_PI_SRAP1_SHIFT))

#define  GALVO_GV_PICNTL1_PI_SRAI1_MASK 0xf000000
#define  GALVO_GV_PICNTL1_PI_SRAI1_SHIFT 24
#define  GALVO_GV_PICNTL1_PI_SRAI1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL1_PI_SRAI1_MASK) >> GALVO_GV_PICNTL1_PI_SRAI1_SHIFT)
#define  GALVO_GV_PICNTL1_PI_SRAI1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL1_PI_SRAI1_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL1_PI_SRAI1_SHIFT))

#define  GALVO_GV_PICNTL1_RESERVED1_MASK 0x800000
#define  GALVO_GV_PICNTL1_RESERVED1_SHIFT 23
#define  GALVO_GV_PICNTL1_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL1_RESERVED1_MASK) >> GALVO_GV_PICNTL1_RESERVED1_SHIFT)
#define  GALVO_GV_PICNTL1_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL1_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL1_RESERVED1_SHIFT))

#define  GALVO_GV_PICNTL1_PI_EN1_MASK 0x400000
#define  GALVO_GV_PICNTL1_PI_EN1_SHIFT 22
#define  GALVO_GV_PICNTL1_PI_EN1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL1_PI_EN1_MASK) >> GALVO_GV_PICNTL1_PI_EN1_SHIFT)
#define  GALVO_GV_PICNTL1_PI_EN1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL1_PI_EN1_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL1_PI_EN1_SHIFT))

#define  GALVO_GV_PICNTL1_PI_TB1_MASK 0x300000
#define  GALVO_GV_PICNTL1_PI_TB1_SHIFT 20
#define  GALVO_GV_PICNTL1_PI_TB1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL1_PI_TB1_MASK) >> GALVO_GV_PICNTL1_PI_TB1_SHIFT)
#define  GALVO_GV_PICNTL1_PI_TB1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL1_PI_TB1_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL1_PI_TB1_SHIFT))

#define  GALVO_GV_PICNTL1_PI_LOC1_MASK 0xc0000
#define  GALVO_GV_PICNTL1_PI_LOC1_SHIFT 18
#define  GALVO_GV_PICNTL1_PI_LOC1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL1_PI_LOC1_MASK) >> GALVO_GV_PICNTL1_PI_LOC1_SHIFT)
#define  GALVO_GV_PICNTL1_PI_LOC1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL1_PI_LOC1_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL1_PI_LOC1_SHIFT))

#define  GALVO_GV_PICNTL1_PI_SLCT1_MASK 0x30000
#define  GALVO_GV_PICNTL1_PI_SLCT1_SHIFT 16
#define  GALVO_GV_PICNTL1_PI_SLCT1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL1_PI_SLCT1_MASK) >> GALVO_GV_PICNTL1_PI_SLCT1_SHIFT)
#define  GALVO_GV_PICNTL1_PI_SLCT1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL1_PI_SLCT1_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL1_PI_SLCT1_SHIFT))

#define  GALVO_GV_PICNTL1_PI_SKIP1_MASK 0xf000
#define  GALVO_GV_PICNTL1_PI_SKIP1_SHIFT 12
#define  GALVO_GV_PICNTL1_PI_SKIP1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL1_PI_SKIP1_MASK) >> GALVO_GV_PICNTL1_PI_SKIP1_SHIFT)
#define  GALVO_GV_PICNTL1_PI_SKIP1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL1_PI_SKIP1_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL1_PI_SKIP1_SHIFT))

#define  GALVO_GV_PICNTL1_PI_KI1_MASK 0xf00
#define  GALVO_GV_PICNTL1_PI_KI1_SHIFT 8
#define  GALVO_GV_PICNTL1_PI_KI1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL1_PI_KI1_MASK) >> GALVO_GV_PICNTL1_PI_KI1_SHIFT)
#define  GALVO_GV_PICNTL1_PI_KI1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL1_PI_KI1_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL1_PI_KI1_SHIFT))

#define  GALVO_GV_PICNTL1_RESERVED2_MASK 0xc0
#define  GALVO_GV_PICNTL1_RESERVED2_SHIFT 6
#define  GALVO_GV_PICNTL1_RESERVED2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL1_RESERVED2_MASK) >> GALVO_GV_PICNTL1_RESERVED2_SHIFT)
#define  GALVO_GV_PICNTL1_RESERVED2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL1_RESERVED2_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL1_RESERVED2_SHIFT))

#define  GALVO_GV_PICNTL1_PI_KP1_MASK 0x3f
#define  GALVO_GV_PICNTL1_PI_KP1_SHIFT 0
#define  GALVO_GV_PICNTL1_PI_KP1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL1_PI_KP1_MASK) >> GALVO_GV_PICNTL1_PI_KP1_SHIFT)
#define  GALVO_GV_PICNTL1_PI_KP1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL1_PI_KP1_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL1_PI_KP1_SHIFT))

//====================================================================
//Register: Galvo Proportional Integral Target 1  (gv_pitarget1)
//====================================================================

#define  GALVO_GV_PITARGET1_PI_OUT1_MASK 0xffff0000
#define  GALVO_GV_PITARGET1_PI_OUT1_SHIFT 16
#define  GALVO_GV_PITARGET1_PI_OUT1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PITARGET1_PI_OUT1_MASK) >> GALVO_GV_PITARGET1_PI_OUT1_SHIFT)
#define  GALVO_GV_PITARGET1_PI_OUT1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PITARGET1_PI_OUT1_MASK) | (((uint32_t)val) << GALVO_GV_PITARGET1_PI_OUT1_SHIFT))

#define  GALVO_GV_PITARGET1_PITARGET_MASK 0xffff
#define  GALVO_GV_PITARGET1_PITARGET_SHIFT 0
#define  GALVO_GV_PITARGET1_PITARGET_MASK_SHIFT(reg) (((reg) & GALVO_GV_PITARGET1_PITARGET_MASK) >> GALVO_GV_PITARGET1_PITARGET_SHIFT)
#define  GALVO_GV_PITARGET1_PITARGET_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PITARGET1_PITARGET_MASK) | (((uint32_t)val) << GALVO_GV_PITARGET1_PITARGET_SHIFT))

//====================================================================
//Register: Galvo Proportional Integral Control 2 (gv_picntl2)
/** \brief This PI block is used for offset control. This controller is identical to the amplitude controller described in GV_PICNTL1
with one exception: the offset controller attempts to control the difference between the hsyncn0 interval and the hsyncn2 interval.
When PI_SLCT2 is 0, the offset controller feedback is hsyncn0 - hsyncn2. When PI_SLCT2 is non-zero, the offset controller
               feedback is hsyncn2 - hsyncn0. The offset controller's target register should be loaded accordingly.*/
//====================================================================

#define  GALVO_GV_PICNTL2_PI_SRAP2_MASK 0xf0000000
#define  GALVO_GV_PICNTL2_PI_SRAP2_SHIFT 28
#define  GALVO_GV_PICNTL2_PI_SRAP2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL2_PI_SRAP2_MASK) >> GALVO_GV_PICNTL2_PI_SRAP2_SHIFT)
#define  GALVO_GV_PICNTL2_PI_SRAP2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL2_PI_SRAP2_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL2_PI_SRAP2_SHIFT))

#define  GALVO_GV_PICNTL2_PI_SRAI2_MASK 0xf000000
#define  GALVO_GV_PICNTL2_PI_SRAI2_SHIFT 24
#define  GALVO_GV_PICNTL2_PI_SRAI2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL2_PI_SRAI2_MASK) >> GALVO_GV_PICNTL2_PI_SRAI2_SHIFT)
#define  GALVO_GV_PICNTL2_PI_SRAI2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL2_PI_SRAI2_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL2_PI_SRAI2_SHIFT))

#define  GALVO_GV_PICNTL2_RESERVED1_MASK 0x800000
#define  GALVO_GV_PICNTL2_RESERVED1_SHIFT 23
#define  GALVO_GV_PICNTL2_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL2_RESERVED1_MASK) >> GALVO_GV_PICNTL2_RESERVED1_SHIFT)
#define  GALVO_GV_PICNTL2_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL2_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL2_RESERVED1_SHIFT))

#define  GALVO_GV_PICNTL2_PI_EN2_MASK 0x400000
#define  GALVO_GV_PICNTL2_PI_EN2_SHIFT 22
#define  GALVO_GV_PICNTL2_PI_EN2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL2_PI_EN2_MASK) >> GALVO_GV_PICNTL2_PI_EN2_SHIFT)
#define  GALVO_GV_PICNTL2_PI_EN2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL2_PI_EN2_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL2_PI_EN2_SHIFT))

#define  GALVO_GV_PICNTL2_PI_TB2_MASK 0x300000
#define  GALVO_GV_PICNTL2_PI_TB2_SHIFT 20
#define  GALVO_GV_PICNTL2_PI_TB2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL2_PI_TB2_MASK) >> GALVO_GV_PICNTL2_PI_TB2_SHIFT)
#define  GALVO_GV_PICNTL2_PI_TB2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL2_PI_TB2_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL2_PI_TB2_SHIFT))

#define  GALVO_GV_PICNTL2_PI_LOC2_MASK 0xc0000
#define  GALVO_GV_PICNTL2_PI_LOC2_SHIFT 18
#define  GALVO_GV_PICNTL2_PI_LOC2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL2_PI_LOC2_MASK) >> GALVO_GV_PICNTL2_PI_LOC2_SHIFT)
#define  GALVO_GV_PICNTL2_PI_LOC2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL2_PI_LOC2_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL2_PI_LOC2_SHIFT))

#define  GALVO_GV_PICNTL2_PI_SLCT2_MASK 0x30000
#define  GALVO_GV_PICNTL2_PI_SLCT2_SHIFT 16
#define  GALVO_GV_PICNTL2_PI_SLCT2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL2_PI_SLCT2_MASK) >> GALVO_GV_PICNTL2_PI_SLCT2_SHIFT)
#define  GALVO_GV_PICNTL2_PI_SLCT2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL2_PI_SLCT2_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL2_PI_SLCT2_SHIFT))

#define  GALVO_GV_PICNTL2_PI_SKIP2_MASK 0xf000
#define  GALVO_GV_PICNTL2_PI_SKIP2_SHIFT 12
#define  GALVO_GV_PICNTL2_PI_SKIP2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL2_PI_SKIP2_MASK) >> GALVO_GV_PICNTL2_PI_SKIP2_SHIFT)
#define  GALVO_GV_PICNTL2_PI_SKIP2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL2_PI_SKIP2_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL2_PI_SKIP2_SHIFT))

#define  GALVO_GV_PICNTL2_PI_KI2_MASK 0xf00
#define  GALVO_GV_PICNTL2_PI_KI2_SHIFT 8
#define  GALVO_GV_PICNTL2_PI_KI2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL2_PI_KI2_MASK) >> GALVO_GV_PICNTL2_PI_KI2_SHIFT)
#define  GALVO_GV_PICNTL2_PI_KI2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL2_PI_KI2_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL2_PI_KI2_SHIFT))

#define  GALVO_GV_PICNTL2_RESERVED2_MASK 0xc0
#define  GALVO_GV_PICNTL2_RESERVED2_SHIFT 6
#define  GALVO_GV_PICNTL2_RESERVED2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL2_RESERVED2_MASK) >> GALVO_GV_PICNTL2_RESERVED2_SHIFT)
#define  GALVO_GV_PICNTL2_RESERVED2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL2_RESERVED2_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL2_RESERVED2_SHIFT))

#define  GALVO_GV_PICNTL2_PI_KP2_MASK 0x3f
#define  GALVO_GV_PICNTL2_PI_KP2_SHIFT 0
#define  GALVO_GV_PICNTL2_PI_KP2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PICNTL2_PI_KP2_MASK) >> GALVO_GV_PICNTL2_PI_KP2_SHIFT)
#define  GALVO_GV_PICNTL2_PI_KP2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PICNTL2_PI_KP2_MASK) | (((uint32_t)val) << GALVO_GV_PICNTL2_PI_KP2_SHIFT))

//====================================================================
//Register: Galvo Proportional Integral Target 2  (gv_pitarget2)
/** \brief Same as GV_PITARGET1, but pertains to the offset controller.*/
//====================================================================

#define  GALVO_GV_PITARGET2_PI_OU2_MASK 0xffff0000
#define  GALVO_GV_PITARGET2_PI_OU2_SHIFT 16
#define  GALVO_GV_PITARGET2_PI_OU2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PITARGET2_PI_OU2_MASK) >> GALVO_GV_PITARGET2_PI_OU2_SHIFT)
#define  GALVO_GV_PITARGET2_PI_OU2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PITARGET2_PI_OU2_MASK) | (((uint32_t)val) << GALVO_GV_PITARGET2_PI_OU2_SHIFT))

#define  GALVO_GV_PITARGET2_PITARGET_MASK 0xffff
#define  GALVO_GV_PITARGET2_PITARGET_SHIFT 0
#define  GALVO_GV_PITARGET2_PITARGET_MASK_SHIFT(reg) (((reg) & GALVO_GV_PITARGET2_PITARGET_MASK) >> GALVO_GV_PITARGET2_PITARGET_SHIFT)
#define  GALVO_GV_PITARGET2_PITARGET_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PITARGET2_PITARGET_MASK) | (((uint32_t)val) << GALVO_GV_PITARGET2_PITARGET_SHIFT))

//====================================================================
//Register: Galvo Proportional Integral Accumlator 1  (gv_piaccum1)
//====================================================================

#define  GALVO_GV_PIACCUM1_RESERVED1_MASK 0xffff0000
#define  GALVO_GV_PIACCUM1_RESERVED1_SHIFT 16
#define  GALVO_GV_PIACCUM1_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PIACCUM1_RESERVED1_MASK) >> GALVO_GV_PIACCUM1_RESERVED1_SHIFT)
#define  GALVO_GV_PIACCUM1_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PIACCUM1_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_PIACCUM1_RESERVED1_SHIFT))

#define  GALVO_GV_PIACCUM1_PIACCUM1_MASK 0xffff
#define  GALVO_GV_PIACCUM1_PIACCUM1_SHIFT 0
#define  GALVO_GV_PIACCUM1_PIACCUM1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PIACCUM1_PIACCUM1_MASK) >> GALVO_GV_PIACCUM1_PIACCUM1_SHIFT)
#define  GALVO_GV_PIACCUM1_PIACCUM1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PIACCUM1_PIACCUM1_MASK) | (((uint32_t)val) << GALVO_GV_PIACCUM1_PIACCUM1_SHIFT))

//====================================================================
//Register: Galvo Proportional Integral Accumlator 2 (gv_piaccum2)
//====================================================================

#define  GALVO_GV_PIACCUM2_RESERVED1_MASK 0xffff0000
#define  GALVO_GV_PIACCUM2_RESERVED1_SHIFT 16
#define  GALVO_GV_PIACCUM2_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_PIACCUM2_RESERVED1_MASK) >> GALVO_GV_PIACCUM2_RESERVED1_SHIFT)
#define  GALVO_GV_PIACCUM2_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PIACCUM2_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_PIACCUM2_RESERVED1_SHIFT))

#define  GALVO_GV_PIACCUM2_PIACCUM2_MASK 0xffff
#define  GALVO_GV_PIACCUM2_PIACCUM2_SHIFT 0
#define  GALVO_GV_PIACCUM2_PIACCUM2_MASK_SHIFT(reg) (((reg) & GALVO_GV_PIACCUM2_PIACCUM2_MASK) >> GALVO_GV_PIACCUM2_PIACCUM2_SHIFT)
#define  GALVO_GV_PIACCUM2_PIACCUM2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_PIACCUM2_PIACCUM2_MASK) | (((uint32_t)val) << GALVO_GV_PIACCUM2_PIACCUM2_SHIFT))

//====================================================================
//Register:  (gv_err_msk)
//====================================================================

#define  GALVO_GV_ERR_MSK_ERRORRST_MASK 0x80000000
#define  GALVO_GV_ERR_MSK_ERRORRST_SHIFT 31
#define  GALVO_GV_ERR_MSK_ERRORRST_MASK_SHIFT(reg) (((reg) & GALVO_GV_ERR_MSK_ERRORRST_MASK) >> GALVO_GV_ERR_MSK_ERRORRST_SHIFT)
#define  GALVO_GV_ERR_MSK_ERRORRST_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ERR_MSK_ERRORRST_MASK) | (((uint32_t)val) << GALVO_GV_ERR_MSK_ERRORRST_SHIFT))

#define  GALVO_GV_ERR_MSK_RESERVED1_MASK 0x7ffffe00
#define  GALVO_GV_ERR_MSK_RESERVED1_SHIFT 9
#define  GALVO_GV_ERR_MSK_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_ERR_MSK_RESERVED1_MASK) >> GALVO_GV_ERR_MSK_RESERVED1_SHIFT)
#define  GALVO_GV_ERR_MSK_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ERR_MSK_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_ERR_MSK_RESERVED1_SHIFT))

#define  GALVO_GV_ERR_MSK_ERR_MASK_MASK 0x1ff
#define  GALVO_GV_ERR_MSK_ERR_MASK_SHIFT 0
#define  GALVO_GV_ERR_MSK_ERR_MASK_MASK_SHIFT(reg) (((reg) & GALVO_GV_ERR_MSK_ERR_MASK_MASK) >> GALVO_GV_ERR_MSK_ERR_MASK_SHIFT)
#define  GALVO_GV_ERR_MSK_ERR_MASK_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ERR_MSK_ERR_MASK_MASK) | (((uint32_t)val) << GALVO_GV_ERR_MSK_ERR_MASK_SHIFT))

//====================================================================
//Register:  (gv_err_stat1)
//====================================================================

#define  GALVO_GV_ERR_STAT1_RESERVED1_MASK 0xfffffe00
#define  GALVO_GV_ERR_STAT1_RESERVED1_SHIFT 9
#define  GALVO_GV_ERR_STAT1_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_ERR_STAT1_RESERVED1_MASK) >> GALVO_GV_ERR_STAT1_RESERVED1_SHIFT)
#define  GALVO_GV_ERR_STAT1_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ERR_STAT1_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_ERR_STAT1_RESERVED1_SHIFT))

#define  GALVO_GV_ERR_STAT1_ERR_BITS_MASK 0x1ff
#define  GALVO_GV_ERR_STAT1_ERR_BITS_SHIFT 0
#define  GALVO_GV_ERR_STAT1_ERR_BITS_MASK_SHIFT(reg) (((reg) & GALVO_GV_ERR_STAT1_ERR_BITS_MASK) >> GALVO_GV_ERR_STAT1_ERR_BITS_SHIFT)
#define  GALVO_GV_ERR_STAT1_ERR_BITS_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ERR_STAT1_ERR_BITS_MASK) | (((uint32_t)val) << GALVO_GV_ERR_STAT1_ERR_BITS_SHIFT))

//====================================================================
//Register:  (gv_err_stat2)
//====================================================================

#define  GALVO_GV_ERR_STAT2_RESERVED1_MASK 0xfff00000
#define  GALVO_GV_ERR_STAT2_RESERVED1_SHIFT 20
#define  GALVO_GV_ERR_STAT2_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_ERR_STAT2_RESERVED1_MASK) >> GALVO_GV_ERR_STAT2_RESERVED1_SHIFT)
#define  GALVO_GV_ERR_STAT2_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ERR_STAT2_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_ERR_STAT2_RESERVED1_SHIFT))

#define  GALVO_GV_ERR_STAT2_ERR_ZONE_MASK 0xf0000
#define  GALVO_GV_ERR_STAT2_ERR_ZONE_SHIFT 16
#define  GALVO_GV_ERR_STAT2_ERR_ZONE_MASK_SHIFT(reg) (((reg) & GALVO_GV_ERR_STAT2_ERR_ZONE_MASK) >> GALVO_GV_ERR_STAT2_ERR_ZONE_SHIFT)
#define  GALVO_GV_ERR_STAT2_ERR_ZONE_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ERR_STAT2_ERR_ZONE_MASK) | (((uint32_t)val) << GALVO_GV_ERR_STAT2_ERR_ZONE_SHIFT))

#define  GALVO_GV_ERR_STAT2_ERR_CAP_MASK 0xffff
#define  GALVO_GV_ERR_STAT2_ERR_CAP_SHIFT 0
#define  GALVO_GV_ERR_STAT2_ERR_CAP_MASK_SHIFT(reg) (((reg) & GALVO_GV_ERR_STAT2_ERR_CAP_MASK) >> GALVO_GV_ERR_STAT2_ERR_CAP_SHIFT)
#define  GALVO_GV_ERR_STAT2_ERR_CAP_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_ERR_STAT2_ERR_CAP_MASK) | (((uint32_t)val) << GALVO_GV_ERR_STAT2_ERR_CAP_SHIFT))

//====================================================================
//Register: Galvo Status/Control  (gv_statcntl)
//====================================================================

#define  GALVO_GV_STATCNTL_RESERVED1_MASK 0xf0000000
#define  GALVO_GV_STATCNTL_RESERVED1_SHIFT 28
#define  GALVO_GV_STATCNTL_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_GV_STATCNTL_RESERVED1_MASK) >> GALVO_GV_STATCNTL_RESERVED1_SHIFT)
#define  GALVO_GV_STATCNTL_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_STATCNTL_RESERVED1_MASK) | (((uint32_t)val) << GALVO_GV_STATCNTL_RESERVED1_SHIFT))

#define  GALVO_GV_STATCNTL_SLCTB_MASK 0xc000000
#define  GALVO_GV_STATCNTL_SLCTB_SHIFT 26
#define  GALVO_GV_STATCNTL_SLCTB_MASK_SHIFT(reg) (((reg) & GALVO_GV_STATCNTL_SLCTB_MASK) >> GALVO_GV_STATCNTL_SLCTB_SHIFT)
#define  GALVO_GV_STATCNTL_SLCTB_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_STATCNTL_SLCTB_MASK) | (((uint32_t)val) << GALVO_GV_STATCNTL_SLCTB_SHIFT))

#define  GALVO_GV_STATCNTL_SLCTA_MASK 0x3000000
#define  GALVO_GV_STATCNTL_SLCTA_SHIFT 24
#define  GALVO_GV_STATCNTL_SLCTA_MASK_SHIFT(reg) (((reg) & GALVO_GV_STATCNTL_SLCTA_MASK) >> GALVO_GV_STATCNTL_SLCTA_SHIFT)
#define  GALVO_GV_STATCNTL_SLCTA_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_STATCNTL_SLCTA_MASK) | (((uint32_t)val) << GALVO_GV_STATCNTL_SLCTA_SHIFT))

#define  GALVO_GV_STATCNTL_RESERVED2_MASK 0xe00000
#define  GALVO_GV_STATCNTL_RESERVED2_SHIFT 21
#define  GALVO_GV_STATCNTL_RESERVED2_MASK_SHIFT(reg) (((reg) & GALVO_GV_STATCNTL_RESERVED2_MASK) >> GALVO_GV_STATCNTL_RESERVED2_SHIFT)
#define  GALVO_GV_STATCNTL_RESERVED2_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_STATCNTL_RESERVED2_MASK) | (((uint32_t)val) << GALVO_GV_STATCNTL_RESERVED2_SHIFT))

#define  GALVO_GV_STATCNTL_DATARDY_MASK 0x100000
#define  GALVO_GV_STATCNTL_DATARDY_SHIFT 20
#define  GALVO_GV_STATCNTL_DATARDY_MASK_SHIFT(reg) (((reg) & GALVO_GV_STATCNTL_DATARDY_MASK) >> GALVO_GV_STATCNTL_DATARDY_SHIFT)
#define  GALVO_GV_STATCNTL_DATARDY_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_STATCNTL_DATARDY_MASK) | (((uint32_t)val) << GALVO_GV_STATCNTL_DATARDY_SHIFT))

#define  GALVO_GV_STATCNTL_RESERVED3_MASK 0x80000
#define  GALVO_GV_STATCNTL_RESERVED3_SHIFT 19
#define  GALVO_GV_STATCNTL_RESERVED3_MASK_SHIFT(reg) (((reg) & GALVO_GV_STATCNTL_RESERVED3_MASK) >> GALVO_GV_STATCNTL_RESERVED3_SHIFT)
#define  GALVO_GV_STATCNTL_RESERVED3_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_STATCNTL_RESERVED3_MASK) | (((uint32_t)val) << GALVO_GV_STATCNTL_RESERVED3_SHIFT))

#define  GALVO_GV_STATCNTL_COLLECT_MASK 0x40000
#define  GALVO_GV_STATCNTL_COLLECT_SHIFT 18
#define  GALVO_GV_STATCNTL_COLLECT_MASK_SHIFT(reg) (((reg) & GALVO_GV_STATCNTL_COLLECT_MASK) >> GALVO_GV_STATCNTL_COLLECT_SHIFT)
#define  GALVO_GV_STATCNTL_COLLECT_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_STATCNTL_COLLECT_MASK) | (((uint32_t)val) << GALVO_GV_STATCNTL_COLLECT_SHIFT))

#define  GALVO_GV_STATCNTL_RESERVED4_MASK 0x30000
#define  GALVO_GV_STATCNTL_RESERVED4_SHIFT 16
#define  GALVO_GV_STATCNTL_RESERVED4_MASK_SHIFT(reg) (((reg) & GALVO_GV_STATCNTL_RESERVED4_MASK) >> GALVO_GV_STATCNTL_RESERVED4_SHIFT)
#define  GALVO_GV_STATCNTL_RESERVED4_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_STATCNTL_RESERVED4_MASK) | (((uint32_t)val) << GALVO_GV_STATCNTL_RESERVED4_SHIFT))

#define  GALVO_GV_STATCNTL_DATAPTS_MASK 0xffff
#define  GALVO_GV_STATCNTL_DATAPTS_SHIFT 0
#define  GALVO_GV_STATCNTL_DATAPTS_MASK_SHIFT(reg) (((reg) & GALVO_GV_STATCNTL_DATAPTS_MASK) >> GALVO_GV_STATCNTL_DATAPTS_SHIFT)
#define  GALVO_GV_STATCNTL_DATAPTS_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_STATCNTL_DATAPTS_MASK) | (((uint32_t)val) << GALVO_GV_STATCNTL_DATAPTS_SHIFT))

//====================================================================
//Register: Galvo CAPA:CAPB:ALIGN:PHASE:AMP:OFFSET Sum Data  (gv_cap0_sum)
//====================================================================

#define  GALVO_GV_CAP0_SUM_CAP0_SUM_MASK 0xffffffff
#define  GALVO_GV_CAP0_SUM_CAP0_SUM_SHIFT 0
#define  GALVO_GV_CAP0_SUM_CAP0_SUM_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP0_SUM_CAP0_SUM_MASK) >> GALVO_GV_CAP0_SUM_CAP0_SUM_SHIFT)
#define  GALVO_GV_CAP0_SUM_CAP0_SUM_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP0_SUM_CAP0_SUM_MASK) | (((uint32_t)val) << GALVO_GV_CAP0_SUM_CAP0_SUM_SHIFT))

//====================================================================
//Register: Galvo CAPA:CAPB:ALIGN:PHASE:AMP:OFFSET Sum Data  (gv_cap1_sum)
//====================================================================

#define  GALVO_GV_CAP1_SUM_CAP1_SUM_MASK 0xffffffff
#define  GALVO_GV_CAP1_SUM_CAP1_SUM_SHIFT 0
#define  GALVO_GV_CAP1_SUM_CAP1_SUM_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP1_SUM_CAP1_SUM_MASK) >> GALVO_GV_CAP1_SUM_CAP1_SUM_SHIFT)
#define  GALVO_GV_CAP1_SUM_CAP1_SUM_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP1_SUM_CAP1_SUM_MASK) | (((uint32_t)val) << GALVO_GV_CAP1_SUM_CAP1_SUM_SHIFT))

//====================================================================
//Register: Galvo CAPA:CAPB:ALIGN:PHASE:AMP:OFFSET Sum Data  (gv_cap2_sum)
//====================================================================

#define  GALVO_GV_CAP2_SUM_CAP2_SUM_MASK 0xffffffff
#define  GALVO_GV_CAP2_SUM_CAP2_SUM_SHIFT 0
#define  GALVO_GV_CAP2_SUM_CAP2_SUM_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP2_SUM_CAP2_SUM_MASK) >> GALVO_GV_CAP2_SUM_CAP2_SUM_SHIFT)
#define  GALVO_GV_CAP2_SUM_CAP2_SUM_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP2_SUM_CAP2_SUM_MASK) | (((uint32_t)val) << GALVO_GV_CAP2_SUM_CAP2_SUM_SHIFT))

//====================================================================
//Register: Galvo CAPA:CAPB:ALIGN:PHASE:AMP:OFFSET Sum Data  (gv_cap3_sum)
//====================================================================

#define  GALVO_GV_CAP3_SUM_CAP3_SUM_MASK 0xffffffff
#define  GALVO_GV_CAP3_SUM_CAP3_SUM_SHIFT 0
#define  GALVO_GV_CAP3_SUM_CAP3_SUM_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP3_SUM_CAP3_SUM_MASK) >> GALVO_GV_CAP3_SUM_CAP3_SUM_SHIFT)
#define  GALVO_GV_CAP3_SUM_CAP3_SUM_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP3_SUM_CAP3_SUM_MASK) | (((uint32_t)val) << GALVO_GV_CAP3_SUM_CAP3_SUM_SHIFT))

//====================================================================
//Register: Galvo CAPA:CAPB:ALIGN:PHASE:AMP:OFFSET Min/Max Data  (gv_cap0_hilo)
//====================================================================

#define  GALVO_GV_CAP0_HILO_CAP0_MAX_MASK 0xffff0000
#define  GALVO_GV_CAP0_HILO_CAP0_MAX_SHIFT 16
#define  GALVO_GV_CAP0_HILO_CAP0_MAX_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP0_HILO_CAP0_MAX_MASK) >> GALVO_GV_CAP0_HILO_CAP0_MAX_SHIFT)
#define  GALVO_GV_CAP0_HILO_CAP0_MAX_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP0_HILO_CAP0_MAX_MASK) | (((uint32_t)val) << GALVO_GV_CAP0_HILO_CAP0_MAX_SHIFT))

#define  GALVO_GV_CAP0_HILO_CAP0_MIN_MASK 0xffff
#define  GALVO_GV_CAP0_HILO_CAP0_MIN_SHIFT 0
#define  GALVO_GV_CAP0_HILO_CAP0_MIN_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP0_HILO_CAP0_MIN_MASK) >> GALVO_GV_CAP0_HILO_CAP0_MIN_SHIFT)
#define  GALVO_GV_CAP0_HILO_CAP0_MIN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP0_HILO_CAP0_MIN_MASK) | (((uint32_t)val) << GALVO_GV_CAP0_HILO_CAP0_MIN_SHIFT))

//====================================================================
//Register: Galvo CAPA:CAPB:ALIGN:PHASE:AMP:OFFSET Min/Max Data  (gv_cap1_hilo)
//====================================================================

#define  GALVO_GV_CAP1_HILO_CAP1_MAX_MASK 0xffff0000
#define  GALVO_GV_CAP1_HILO_CAP1_MAX_SHIFT 16
#define  GALVO_GV_CAP1_HILO_CAP1_MAX_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP1_HILO_CAP1_MAX_MASK) >> GALVO_GV_CAP1_HILO_CAP1_MAX_SHIFT)
#define  GALVO_GV_CAP1_HILO_CAP1_MAX_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP1_HILO_CAP1_MAX_MASK) | (((uint32_t)val) << GALVO_GV_CAP1_HILO_CAP1_MAX_SHIFT))

#define  GALVO_GV_CAP1_HILO_CAP1_MIN_MASK 0xffff
#define  GALVO_GV_CAP1_HILO_CAP1_MIN_SHIFT 0
#define  GALVO_GV_CAP1_HILO_CAP1_MIN_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP1_HILO_CAP1_MIN_MASK) >> GALVO_GV_CAP1_HILO_CAP1_MIN_SHIFT)
#define  GALVO_GV_CAP1_HILO_CAP1_MIN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP1_HILO_CAP1_MIN_MASK) | (((uint32_t)val) << GALVO_GV_CAP1_HILO_CAP1_MIN_SHIFT))

//====================================================================
//Register: Galvo CAPA:CAPB:ALIGN:PHASE:AMP:OFFSET Min/Max Data  (gv_cap2_hilo)
//====================================================================

#define  GALVO_GV_CAP2_HILO_CAP2_MAX_MASK 0xffff0000
#define  GALVO_GV_CAP2_HILO_CAP2_MAX_SHIFT 16
#define  GALVO_GV_CAP2_HILO_CAP2_MAX_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP2_HILO_CAP2_MAX_MASK) >> GALVO_GV_CAP2_HILO_CAP2_MAX_SHIFT)
#define  GALVO_GV_CAP2_HILO_CAP2_MAX_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP2_HILO_CAP2_MAX_MASK) | (((uint32_t)val) << GALVO_GV_CAP2_HILO_CAP2_MAX_SHIFT))

#define  GALVO_GV_CAP2_HILO_CAP2_MIN_MASK 0xffff
#define  GALVO_GV_CAP2_HILO_CAP2_MIN_SHIFT 0
#define  GALVO_GV_CAP2_HILO_CAP2_MIN_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP2_HILO_CAP2_MIN_MASK) >> GALVO_GV_CAP2_HILO_CAP2_MIN_SHIFT)
#define  GALVO_GV_CAP2_HILO_CAP2_MIN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP2_HILO_CAP2_MIN_MASK) | (((uint32_t)val) << GALVO_GV_CAP2_HILO_CAP2_MIN_SHIFT))

//====================================================================
//Register: Galvo CAPA:CAPB:ALIGN:PHASE:AMP:OFFSET Min/Max Data  (gv_cap3_hilo)
//====================================================================

#define  GALVO_GV_CAP3_HILO_CAP3_MAX_MASK 0xffff0000
#define  GALVO_GV_CAP3_HILO_CAP3_MAX_SHIFT 16
#define  GALVO_GV_CAP3_HILO_CAP3_MAX_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP3_HILO_CAP3_MAX_MASK) >> GALVO_GV_CAP3_HILO_CAP3_MAX_SHIFT)
#define  GALVO_GV_CAP3_HILO_CAP3_MAX_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP3_HILO_CAP3_MAX_MASK) | (((uint32_t)val) << GALVO_GV_CAP3_HILO_CAP3_MAX_SHIFT))

#define  GALVO_GV_CAP3_HILO_CAP3_MIN_MASK 0xffff
#define  GALVO_GV_CAP3_HILO_CAP3_MIN_SHIFT 0
#define  GALVO_GV_CAP3_HILO_CAP3_MIN_MASK_SHIFT(reg) (((reg) & GALVO_GV_CAP3_HILO_CAP3_MIN_MASK) >> GALVO_GV_CAP3_HILO_CAP3_MIN_SHIFT)
#define  GALVO_GV_CAP3_HILO_CAP3_MIN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_CAP3_HILO_CAP3_MIN_MASK) | (((uint32_t)val) << GALVO_GV_CAP3_HILO_CAP3_MIN_SHIFT))

//====================================================================
//Register:  (gv_amp_sum)
//====================================================================

#define  GALVO_GV_AMP_SUM_AMP_SUM_MASK 0xffffffff
#define  GALVO_GV_AMP_SUM_AMP_SUM_SHIFT 0
#define  GALVO_GV_AMP_SUM_AMP_SUM_MASK_SHIFT(reg) (((reg) & GALVO_GV_AMP_SUM_AMP_SUM_MASK) >> GALVO_GV_AMP_SUM_AMP_SUM_SHIFT)
#define  GALVO_GV_AMP_SUM_AMP_SUM_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_AMP_SUM_AMP_SUM_MASK) | (((uint32_t)val) << GALVO_GV_AMP_SUM_AMP_SUM_SHIFT))

//====================================================================
//Register:  (gv_off_sum)
//====================================================================

#define  GALVO_GV_OFF_SUM_OFFSET_SUM_MASK 0xffffffff
#define  GALVO_GV_OFF_SUM_OFFSET_SUM_SHIFT 0
#define  GALVO_GV_OFF_SUM_OFFSET_SUM_MASK_SHIFT(reg) (((reg) & GALVO_GV_OFF_SUM_OFFSET_SUM_MASK) >> GALVO_GV_OFF_SUM_OFFSET_SUM_SHIFT)
#define  GALVO_GV_OFF_SUM_OFFSET_SUM_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_OFF_SUM_OFFSET_SUM_MASK) | (((uint32_t)val) << GALVO_GV_OFF_SUM_OFFSET_SUM_SHIFT))

//====================================================================
//Register:  (gv_amp_hilo)
//====================================================================

#define  GALVO_GV_AMP_HILO_AMP_MAX_MASK 0xffff0000
#define  GALVO_GV_AMP_HILO_AMP_MAX_SHIFT 16
#define  GALVO_GV_AMP_HILO_AMP_MAX_MASK_SHIFT(reg) (((reg) & GALVO_GV_AMP_HILO_AMP_MAX_MASK) >> GALVO_GV_AMP_HILO_AMP_MAX_SHIFT)
#define  GALVO_GV_AMP_HILO_AMP_MAX_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_AMP_HILO_AMP_MAX_MASK) | (((uint32_t)val) << GALVO_GV_AMP_HILO_AMP_MAX_SHIFT))

#define  GALVO_GV_AMP_HILO_AMP_MIN_MASK 0xffff
#define  GALVO_GV_AMP_HILO_AMP_MIN_SHIFT 0
#define  GALVO_GV_AMP_HILO_AMP_MIN_MASK_SHIFT(reg) (((reg) & GALVO_GV_AMP_HILO_AMP_MIN_MASK) >> GALVO_GV_AMP_HILO_AMP_MIN_SHIFT)
#define  GALVO_GV_AMP_HILO_AMP_MIN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_AMP_HILO_AMP_MIN_MASK) | (((uint32_t)val) << GALVO_GV_AMP_HILO_AMP_MIN_SHIFT))

//====================================================================
//Register:  (gv_off_hilo)
//====================================================================

#define  GALVO_GV_OFF_HILO_OFFSET_MAX_MASK 0xffff0000
#define  GALVO_GV_OFF_HILO_OFFSET_MAX_SHIFT 16
#define  GALVO_GV_OFF_HILO_OFFSET_MAX_MASK_SHIFT(reg) (((reg) & GALVO_GV_OFF_HILO_OFFSET_MAX_MASK) >> GALVO_GV_OFF_HILO_OFFSET_MAX_SHIFT)
#define  GALVO_GV_OFF_HILO_OFFSET_MAX_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_OFF_HILO_OFFSET_MAX_MASK) | (((uint32_t)val) << GALVO_GV_OFF_HILO_OFFSET_MAX_SHIFT))

#define  GALVO_GV_OFF_HILO_OFFSET_MIN_MASK 0xffff
#define  GALVO_GV_OFF_HILO_OFFSET_MIN_SHIFT 0
#define  GALVO_GV_OFF_HILO_OFFSET_MIN_MASK_SHIFT(reg) (((reg) & GALVO_GV_OFF_HILO_OFFSET_MIN_MASK) >> GALVO_GV_OFF_HILO_OFFSET_MIN_SHIFT)
#define  GALVO_GV_OFF_HILO_OFFSET_MIN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_GV_OFF_HILO_OFFSET_MIN_MASK) | (((uint32_t)val) << GALVO_GV_OFF_HILO_OFFSET_MIN_SHIFT))

//====================================================================
//Register: tr0 (test_reg_0)
/** \brief Test register to verify Galvo module connectivity*/
//====================================================================

#define  GALVO_TEST_REG_0_GALVO_IO_TEST_ENABLE_MASK 0x80000000
#define  GALVO_TEST_REG_0_GALVO_IO_TEST_ENABLE_SHIFT 31
#define  GALVO_TEST_REG_0_GALVO_IO_TEST_ENABLE_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_GALVO_IO_TEST_ENABLE_MASK) >> GALVO_TEST_REG_0_GALVO_IO_TEST_ENABLE_SHIFT)
#define  GALVO_TEST_REG_0_GALVO_IO_TEST_ENABLE_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_GALVO_IO_TEST_ENABLE_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_GALVO_IO_TEST_ENABLE_SHIFT))

#define  GALVO_TEST_REG_0_RESERVED1_MASK 0x7fe00000
#define  GALVO_TEST_REG_0_RESERVED1_SHIFT 21
#define  GALVO_TEST_REG_0_RESERVED1_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_RESERVED1_MASK) >> GALVO_TEST_REG_0_RESERVED1_SHIFT)
#define  GALVO_TEST_REG_0_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_RESERVED1_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_RESERVED1_SHIFT))

#define  GALVO_TEST_REG_0_GALVO_MUXUNI_MASK 0x100000
#define  GALVO_TEST_REG_0_GALVO_MUXUNI_SHIFT 20
#define  GALVO_TEST_REG_0_GALVO_MUXUNI_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_GALVO_MUXUNI_MASK) >> GALVO_TEST_REG_0_GALVO_MUXUNI_SHIFT)
#define  GALVO_TEST_REG_0_GALVO_MUXUNI_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_GALVO_MUXUNI_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_GALVO_MUXUNI_SHIFT))

#define  GALVO_TEST_REG_0_GALVO_HSYNCN_MASK 0xf0000
#define  GALVO_TEST_REG_0_GALVO_HSYNCN_SHIFT 16
#define  GALVO_TEST_REG_0_GALVO_HSYNCN_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_GALVO_HSYNCN_MASK) >> GALVO_TEST_REG_0_GALVO_HSYNCN_SHIFT)
#define  GALVO_TEST_REG_0_GALVO_HSYNCN_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_GALVO_HSYNCN_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_GALVO_HSYNCN_SHIFT))

#define  GALVO_TEST_REG_0_GALVO_MPO_MASK 0x8000
#define  GALVO_TEST_REG_0_GALVO_MPO_SHIFT 15
#define  GALVO_TEST_REG_0_GALVO_MPO_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_GALVO_MPO_MASK) >> GALVO_TEST_REG_0_GALVO_MPO_SHIFT)
#define  GALVO_TEST_REG_0_GALVO_MPO_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_GALVO_MPO_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_GALVO_MPO_SHIFT))

#define  GALVO_TEST_REG_0_GALVO_IRQ_MASK 0x4000
#define  GALVO_TEST_REG_0_GALVO_IRQ_SHIFT 14
#define  GALVO_TEST_REG_0_GALVO_IRQ_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_GALVO_IRQ_MASK) >> GALVO_TEST_REG_0_GALVO_IRQ_SHIFT)
#define  GALVO_TEST_REG_0_GALVO_IRQ_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_GALVO_IRQ_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_GALVO_IRQ_SHIFT))

#define  GALVO_TEST_REG_0_GALVO_DRIVE_DIR_MASK 0x2000
#define  GALVO_TEST_REG_0_GALVO_DRIVE_DIR_SHIFT 13
#define  GALVO_TEST_REG_0_GALVO_DRIVE_DIR_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_GALVO_DRIVE_DIR_MASK) >> GALVO_TEST_REG_0_GALVO_DRIVE_DIR_SHIFT)
#define  GALVO_TEST_REG_0_GALVO_DRIVE_DIR_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_GALVO_DRIVE_DIR_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_GALVO_DRIVE_DIR_SHIFT))

#define  GALVO_TEST_REG_0_GALVO_DRIVE_MASK 0x1800
#define  GALVO_TEST_REG_0_GALVO_DRIVE_SHIFT 11
#define  GALVO_TEST_REG_0_GALVO_DRIVE_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_GALVO_DRIVE_MASK) >> GALVO_TEST_REG_0_GALVO_DRIVE_SHIFT)
#define  GALVO_TEST_REG_0_GALVO_DRIVE_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_GALVO_DRIVE_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_GALVO_DRIVE_SHIFT))

#define  GALVO_TEST_REG_0_GALVO_REVERSE_VIDEO_MASK 0x400
#define  GALVO_TEST_REG_0_GALVO_REVERSE_VIDEO_SHIFT 10
#define  GALVO_TEST_REG_0_GALVO_REVERSE_VIDEO_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_GALVO_REVERSE_VIDEO_MASK) >> GALVO_TEST_REG_0_GALVO_REVERSE_VIDEO_SHIFT)
#define  GALVO_TEST_REG_0_GALVO_REVERSE_VIDEO_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_GALVO_REVERSE_VIDEO_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_GALVO_REVERSE_VIDEO_SHIFT))

#define  GALVO_TEST_REG_0_GALVO_LASER_ON_MASK 0x200
#define  GALVO_TEST_REG_0_GALVO_LASER_ON_SHIFT 9
#define  GALVO_TEST_REG_0_GALVO_LASER_ON_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_GALVO_LASER_ON_MASK) >> GALVO_TEST_REG_0_GALVO_LASER_ON_SHIFT)
#define  GALVO_TEST_REG_0_GALVO_LASER_ON_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_GALVO_LASER_ON_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_GALVO_LASER_ON_SHIFT))

#define  GALVO_TEST_REG_0_GALVO_ENABLE_MASK 0x100
#define  GALVO_TEST_REG_0_GALVO_ENABLE_SHIFT 8
#define  GALVO_TEST_REG_0_GALVO_ENABLE_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_GALVO_ENABLE_MASK) >> GALVO_TEST_REG_0_GALVO_ENABLE_SHIFT)
#define  GALVO_TEST_REG_0_GALVO_ENABLE_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_GALVO_ENABLE_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_GALVO_ENABLE_SHIFT))

#define  GALVO_TEST_REG_0_GALVO_BOOST_MASK 0x80
#define  GALVO_TEST_REG_0_GALVO_BOOST_SHIFT 7
#define  GALVO_TEST_REG_0_GALVO_BOOST_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_GALVO_BOOST_MASK) >> GALVO_TEST_REG_0_GALVO_BOOST_SHIFT)
#define  GALVO_TEST_REG_0_GALVO_BOOST_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_GALVO_BOOST_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_GALVO_BOOST_SHIFT))

#define  GALVO_TEST_REG_0_VSYNC_TRIGGER_HW_MASK 0x40
#define  GALVO_TEST_REG_0_VSYNC_TRIGGER_HW_SHIFT 6
#define  GALVO_TEST_REG_0_VSYNC_TRIGGER_HW_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_VSYNC_TRIGGER_HW_MASK) >> GALVO_TEST_REG_0_VSYNC_TRIGGER_HW_SHIFT)
#define  GALVO_TEST_REG_0_VSYNC_TRIGGER_HW_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_VSYNC_TRIGGER_HW_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_VSYNC_TRIGGER_HW_SHIFT))

#define  GALVO_TEST_REG_0_HSYNCN2_RAW_MASK 0x20
#define  GALVO_TEST_REG_0_HSYNCN2_RAW_SHIFT 5
#define  GALVO_TEST_REG_0_HSYNCN2_RAW_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_HSYNCN2_RAW_MASK) >> GALVO_TEST_REG_0_HSYNCN2_RAW_SHIFT)
#define  GALVO_TEST_REG_0_HSYNCN2_RAW_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_HSYNCN2_RAW_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_HSYNCN2_RAW_SHIFT))

#define  GALVO_TEST_REG_0_HSYNCN1_RAW_MASK 0x10
#define  GALVO_TEST_REG_0_HSYNCN1_RAW_SHIFT 4
#define  GALVO_TEST_REG_0_HSYNCN1_RAW_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_HSYNCN1_RAW_MASK) >> GALVO_TEST_REG_0_HSYNCN1_RAW_SHIFT)
#define  GALVO_TEST_REG_0_HSYNCN1_RAW_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_HSYNCN1_RAW_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_HSYNCN1_RAW_SHIFT))

#define  GALVO_TEST_REG_0_ALIGN_FB_RAW_MASK 0xf
#define  GALVO_TEST_REG_0_ALIGN_FB_RAW_SHIFT 0
#define  GALVO_TEST_REG_0_ALIGN_FB_RAW_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_0_ALIGN_FB_RAW_MASK) >> GALVO_TEST_REG_0_ALIGN_FB_RAW_SHIFT)
#define  GALVO_TEST_REG_0_ALIGN_FB_RAW_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_0_ALIGN_FB_RAW_MASK) | (((uint32_t)val) << GALVO_TEST_REG_0_ALIGN_FB_RAW_SHIFT))

//====================================================================
//Register: tr1 (test_reg_1)
/** \brief Test register to verify Galvo module connectivity*/
//====================================================================

#define  GALVO_TEST_REG_1_ASELA_MASK 0xffffffff
#define  GALVO_TEST_REG_1_ASELA_SHIFT 0
#define  GALVO_TEST_REG_1_ASELA_MASK_SHIFT(reg) (((reg) & GALVO_TEST_REG_1_ASELA_MASK) >> GALVO_TEST_REG_1_ASELA_SHIFT)
#define  GALVO_TEST_REG_1_ASELA_REPLACE_VAL(reg,val) (((reg) & ~GALVO_TEST_REG_1_ASELA_MASK) | (((uint32_t)val) << GALVO_TEST_REG_1_ASELA_SHIFT))

#endif // GALVO
