 /*
 **************************************************************************************
 *
 * Copyright (c) 2011 Marvell International, Ltd.
 *
 **************************************************************************************
 *
 * Marvell Commercial License Option
 *
 * If you received this File from Marvell as part of a proprietary software release,
 * the File is considered Marvell Proprietary and Confidential Information, and is
 * licensed to you under the terms of the applicable Commercial License.
 *
 **************************************************************************************
 *
 * Marvell GPL License Option
 *
 * If you received this File from Marvell as part of a Linux distribution, this File
 * is licensed to you in accordance with the terms and conditions of the General Public
 * License Version 2, June 1991 (the "GPL License").  You can redistribute it and/or
 * modify it under the terms of the GPL License; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GPL License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this
 * program.  If not, see http://www.gnu.org/licenses/.
 *
 **************************************************************************************
 *
 * \file PIE_ICE_Common_regmasks.h
 * Generated using RegBuild 1.6.1
 *
 *************************************************************************
 */

#ifndef _PIE_COMMON_ICE_REGMASKS_H_
#define _PIE_COMMON_ICE_REGMASKS_H_

#include <stdint.h>

//====================================================================
//
//Register File: PIE Common (PIE_Common_ICE)
/** \brief Register Descriptions for the PIE Common block*/
//
//====================================================================

//====================================================================
//Register: Interrupt Enable Register (IENR)
/** \brief Interrupt Enable Register*/
//====================================================================

#define  PIE_COMMON_ICE_IENR_RESERVED1_MASK 0xffffe000
#define  PIE_COMMON_ICE_IENR_RESERVED1_SHIFT 13
#define  PIE_COMMON_ICE_IENR_RESERVED1_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_RESERVED1_MASK) >> PIE_COMMON_ICE_IENR_RESERVED1_SHIFT)
#define  PIE_COMMON_ICE_IENR_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_RESERVED1_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_RESERVED1_SHIFT))

#define  PIE_COMMON_ICE_IENR_WDMACINTEN_MASK 0x1000
#define  PIE_COMMON_ICE_IENR_WDMACINTEN_SHIFT 12
#define  PIE_COMMON_ICE_IENR_WDMACINTEN_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_WDMACINTEN_MASK) >> PIE_COMMON_ICE_IENR_WDMACINTEN_SHIFT)
#define  PIE_COMMON_ICE_IENR_WDMACINTEN_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_WDMACINTEN_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_WDMACINTEN_SHIFT))

#define  PIE_COMMON_ICE_IENR_WDMA2INTEN_MASK 0x800
#define  PIE_COMMON_ICE_IENR_WDMA2INTEN_SHIFT 11
#define  PIE_COMMON_ICE_IENR_WDMA2INTEN_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_WDMA2INTEN_MASK) >> PIE_COMMON_ICE_IENR_WDMA2INTEN_SHIFT)
#define  PIE_COMMON_ICE_IENR_WDMA2INTEN_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_WDMA2INTEN_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_WDMA2INTEN_SHIFT))

#define  PIE_COMMON_ICE_IENR_WDMA1INTEN_MASK 0x400
#define  PIE_COMMON_ICE_IENR_WDMA1INTEN_SHIFT 10
#define  PIE_COMMON_ICE_IENR_WDMA1INTEN_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_WDMA1INTEN_MASK) >> PIE_COMMON_ICE_IENR_WDMA1INTEN_SHIFT)
#define  PIE_COMMON_ICE_IENR_WDMA1INTEN_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_WDMA1INTEN_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_WDMA1INTEN_SHIFT))

#define  PIE_COMMON_ICE_IENR_WDMA0INTEN_MASK 0x200
#define  PIE_COMMON_ICE_IENR_WDMA0INTEN_SHIFT 9
#define  PIE_COMMON_ICE_IENR_WDMA0INTEN_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_WDMA0INTEN_MASK) >> PIE_COMMON_ICE_IENR_WDMA0INTEN_SHIFT)
#define  PIE_COMMON_ICE_IENR_WDMA0INTEN_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_WDMA0INTEN_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_WDMA0INTEN_SHIFT))

#define  PIE_COMMON_ICE_IENR_RDMACINTEN_MASK 0x100
#define  PIE_COMMON_ICE_IENR_RDMACINTEN_SHIFT 8
#define  PIE_COMMON_ICE_IENR_RDMACINTEN_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_RDMACINTEN_MASK) >> PIE_COMMON_ICE_IENR_RDMACINTEN_SHIFT)
#define  PIE_COMMON_ICE_IENR_RDMACINTEN_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_RDMACINTEN_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_RDMACINTEN_SHIFT))

#define  PIE_COMMON_ICE_IENR_RDMA5INTEN_MASK 0x80
#define  PIE_COMMON_ICE_IENR_RDMA5INTEN_SHIFT 7
#define  PIE_COMMON_ICE_IENR_RDMA5INTEN_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_RDMA5INTEN_MASK) >> PIE_COMMON_ICE_IENR_RDMA5INTEN_SHIFT)
#define  PIE_COMMON_ICE_IENR_RDMA5INTEN_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_RDMA5INTEN_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_RDMA5INTEN_SHIFT))

#define  PIE_COMMON_ICE_IENR_RDMA4INTEN_MASK 0x40
#define  PIE_COMMON_ICE_IENR_RDMA4INTEN_SHIFT 6
#define  PIE_COMMON_ICE_IENR_RDMA4INTEN_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_RDMA4INTEN_MASK) >> PIE_COMMON_ICE_IENR_RDMA4INTEN_SHIFT)
#define  PIE_COMMON_ICE_IENR_RDMA4INTEN_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_RDMA4INTEN_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_RDMA4INTEN_SHIFT))

#define  PIE_COMMON_ICE_IENR_RDMA3INTEN_MASK 0x20
#define  PIE_COMMON_ICE_IENR_RDMA3INTEN_SHIFT 5
#define  PIE_COMMON_ICE_IENR_RDMA3INTEN_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_RDMA3INTEN_MASK) >> PIE_COMMON_ICE_IENR_RDMA3INTEN_SHIFT)
#define  PIE_COMMON_ICE_IENR_RDMA3INTEN_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_RDMA3INTEN_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_RDMA3INTEN_SHIFT))

#define  PIE_COMMON_ICE_IENR_RDMA2INTEN_MASK 0x10
#define  PIE_COMMON_ICE_IENR_RDMA2INTEN_SHIFT 4
#define  PIE_COMMON_ICE_IENR_RDMA2INTEN_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_RDMA2INTEN_MASK) >> PIE_COMMON_ICE_IENR_RDMA2INTEN_SHIFT)
#define  PIE_COMMON_ICE_IENR_RDMA2INTEN_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_RDMA2INTEN_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_RDMA2INTEN_SHIFT))

#define  PIE_COMMON_ICE_IENR_RDMA1INTEN_MASK 0x8
#define  PIE_COMMON_ICE_IENR_RDMA1INTEN_SHIFT 3
#define  PIE_COMMON_ICE_IENR_RDMA1INTEN_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_RDMA1INTEN_MASK) >> PIE_COMMON_ICE_IENR_RDMA1INTEN_SHIFT)
#define  PIE_COMMON_ICE_IENR_RDMA1INTEN_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_RDMA1INTEN_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_RDMA1INTEN_SHIFT))

#define  PIE_COMMON_ICE_IENR_RDMA0INTEN_MASK 0x4
#define  PIE_COMMON_ICE_IENR_RDMA0INTEN_SHIFT 2
#define  PIE_COMMON_ICE_IENR_RDMA0INTEN_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_RDMA0INTEN_MASK) >> PIE_COMMON_ICE_IENR_RDMA0INTEN_SHIFT)
#define  PIE_COMMON_ICE_IENR_RDMA0INTEN_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_RDMA0INTEN_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_RDMA0INTEN_SHIFT))

#define  PIE_COMMON_ICE_IENR_RESERVED2_MASK 0x3
#define  PIE_COMMON_ICE_IENR_RESERVED2_SHIFT 0
#define  PIE_COMMON_ICE_IENR_RESERVED2_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IENR_RESERVED2_MASK) >> PIE_COMMON_ICE_IENR_RESERVED2_SHIFT)
#define  PIE_COMMON_ICE_IENR_RESERVED2_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IENR_RESERVED2_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IENR_RESERVED2_SHIFT))

//====================================================================
//Register: Interrupt Pending Register (IPR)
/** \brief Interrupt Pending Register*/
//====================================================================

#define  PIE_COMMON_ICE_IPR_RESERVED1_MASK 0xffffe000
#define  PIE_COMMON_ICE_IPR_RESERVED1_SHIFT 13
#define  PIE_COMMON_ICE_IPR_RESERVED1_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_RESERVED1_MASK) >> PIE_COMMON_ICE_IPR_RESERVED1_SHIFT)
#define  PIE_COMMON_ICE_IPR_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_RESERVED1_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_RESERVED1_SHIFT))

#define  PIE_COMMON_ICE_IPR_WDMACINTPEND_MASK 0x1000
#define  PIE_COMMON_ICE_IPR_WDMACINTPEND_SHIFT 12
#define  PIE_COMMON_ICE_IPR_WDMACINTPEND_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_WDMACINTPEND_MASK) >> PIE_COMMON_ICE_IPR_WDMACINTPEND_SHIFT)
#define  PIE_COMMON_ICE_IPR_WDMACINTPEND_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_WDMACINTPEND_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_WDMACINTPEND_SHIFT))

#define  PIE_COMMON_ICE_IPR_WDMA2INTPEND_MASK 0x800
#define  PIE_COMMON_ICE_IPR_WDMA2INTPEND_SHIFT 11
#define  PIE_COMMON_ICE_IPR_WDMA2INTPEND_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_WDMA2INTPEND_MASK) >> PIE_COMMON_ICE_IPR_WDMA2INTPEND_SHIFT)
#define  PIE_COMMON_ICE_IPR_WDMA2INTPEND_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_WDMA2INTPEND_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_WDMA2INTPEND_SHIFT))

#define  PIE_COMMON_ICE_IPR_WDMA1INTPEND_MASK 0x400
#define  PIE_COMMON_ICE_IPR_WDMA1INTPEND_SHIFT 10
#define  PIE_COMMON_ICE_IPR_WDMA1INTPEND_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_WDMA1INTPEND_MASK) >> PIE_COMMON_ICE_IPR_WDMA1INTPEND_SHIFT)
#define  PIE_COMMON_ICE_IPR_WDMA1INTPEND_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_WDMA1INTPEND_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_WDMA1INTPEND_SHIFT))

#define  PIE_COMMON_ICE_IPR_WDMA0INTPEND_MASK 0x200
#define  PIE_COMMON_ICE_IPR_WDMA0INTPEND_SHIFT 9
#define  PIE_COMMON_ICE_IPR_WDMA0INTPEND_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_WDMA0INTPEND_MASK) >> PIE_COMMON_ICE_IPR_WDMA0INTPEND_SHIFT)
#define  PIE_COMMON_ICE_IPR_WDMA0INTPEND_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_WDMA0INTPEND_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_WDMA0INTPEND_SHIFT))

#define  PIE_COMMON_ICE_IPR_RDMACINTPEND_MASK 0x100
#define  PIE_COMMON_ICE_IPR_RDMACINTPEND_SHIFT 8
#define  PIE_COMMON_ICE_IPR_RDMACINTPEND_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_RDMACINTPEND_MASK) >> PIE_COMMON_ICE_IPR_RDMACINTPEND_SHIFT)
#define  PIE_COMMON_ICE_IPR_RDMACINTPEND_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_RDMACINTPEND_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_RDMACINTPEND_SHIFT))

#define  PIE_COMMON_ICE_IPR_RDMA5INTPEND_MASK 0x80
#define  PIE_COMMON_ICE_IPR_RDMA5INTPEND_SHIFT 7
#define  PIE_COMMON_ICE_IPR_RDMA5INTPEND_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_RDMA5INTPEND_MASK) >> PIE_COMMON_ICE_IPR_RDMA5INTPEND_SHIFT)
#define  PIE_COMMON_ICE_IPR_RDMA5INTPEND_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_RDMA5INTPEND_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_RDMA5INTPEND_SHIFT))

#define  PIE_COMMON_ICE_IPR_RDMA4INTPEND_MASK 0x40
#define  PIE_COMMON_ICE_IPR_RDMA4INTPEND_SHIFT 6
#define  PIE_COMMON_ICE_IPR_RDMA4INTPEND_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_RDMA4INTPEND_MASK) >> PIE_COMMON_ICE_IPR_RDMA4INTPEND_SHIFT)
#define  PIE_COMMON_ICE_IPR_RDMA4INTPEND_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_RDMA4INTPEND_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_RDMA4INTPEND_SHIFT))

#define  PIE_COMMON_ICE_IPR_RDMA3INTPEND_MASK 0x20
#define  PIE_COMMON_ICE_IPR_RDMA3INTPEND_SHIFT 5
#define  PIE_COMMON_ICE_IPR_RDMA3INTPEND_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_RDMA3INTPEND_MASK) >> PIE_COMMON_ICE_IPR_RDMA3INTPEND_SHIFT)
#define  PIE_COMMON_ICE_IPR_RDMA3INTPEND_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_RDMA3INTPEND_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_RDMA3INTPEND_SHIFT))

#define  PIE_COMMON_ICE_IPR_RDMA2INTPEND_MASK 0x10
#define  PIE_COMMON_ICE_IPR_RDMA2INTPEND_SHIFT 4
#define  PIE_COMMON_ICE_IPR_RDMA2INTPEND_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_RDMA2INTPEND_MASK) >> PIE_COMMON_ICE_IPR_RDMA2INTPEND_SHIFT)
#define  PIE_COMMON_ICE_IPR_RDMA2INTPEND_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_RDMA2INTPEND_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_RDMA2INTPEND_SHIFT))

#define  PIE_COMMON_ICE_IPR_RDMA1INTPEND_MASK 0x8
#define  PIE_COMMON_ICE_IPR_RDMA1INTPEND_SHIFT 3
#define  PIE_COMMON_ICE_IPR_RDMA1INTPEND_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_RDMA1INTPEND_MASK) >> PIE_COMMON_ICE_IPR_RDMA1INTPEND_SHIFT)
#define  PIE_COMMON_ICE_IPR_RDMA1INTPEND_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_RDMA1INTPEND_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_RDMA1INTPEND_SHIFT))

#define  PIE_COMMON_ICE_IPR_RDMA0INTPEND_MASK 0x4
#define  PIE_COMMON_ICE_IPR_RDMA0INTPEND_SHIFT 2
#define  PIE_COMMON_ICE_IPR_RDMA0INTPEND_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_RDMA0INTPEND_MASK) >> PIE_COMMON_ICE_IPR_RDMA0INTPEND_SHIFT)
#define  PIE_COMMON_ICE_IPR_RDMA0INTPEND_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_RDMA0INTPEND_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_RDMA0INTPEND_SHIFT))

#define  PIE_COMMON_ICE_IPR_RESERVED2_MASK 0x3
#define  PIE_COMMON_ICE_IPR_RESERVED2_SHIFT 0
#define  PIE_COMMON_ICE_IPR_RESERVED2_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_IPR_RESERVED2_MASK) >> PIE_COMMON_ICE_IPR_RESERVED2_SHIFT)
#define  PIE_COMMON_ICE_IPR_RESERVED2_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_IPR_RESERVED2_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_IPR_RESERVED2_SHIFT))

//====================================================================
//Register: Interrupt Test Register (ITR)
/** \brief Interrupt Test Register*/
//====================================================================

#define  PIE_COMMON_ICE_ITR_RESERVED1_MASK 0xffffe000
#define  PIE_COMMON_ICE_ITR_RESERVED1_SHIFT 13
#define  PIE_COMMON_ICE_ITR_RESERVED1_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_RESERVED1_MASK) >> PIE_COMMON_ICE_ITR_RESERVED1_SHIFT)
#define  PIE_COMMON_ICE_ITR_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_RESERVED1_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_RESERVED1_SHIFT))

#define  PIE_COMMON_ICE_ITR_WDMACINTTEST_MASK 0x1000
#define  PIE_COMMON_ICE_ITR_WDMACINTTEST_SHIFT 12
#define  PIE_COMMON_ICE_ITR_WDMACINTTEST_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_WDMACINTTEST_MASK) >> PIE_COMMON_ICE_ITR_WDMACINTTEST_SHIFT)
#define  PIE_COMMON_ICE_ITR_WDMACINTTEST_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_WDMACINTTEST_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_WDMACINTTEST_SHIFT))

#define  PIE_COMMON_ICE_ITR_WDMA2INTTEST_MASK 0x800
#define  PIE_COMMON_ICE_ITR_WDMA2INTTEST_SHIFT 11
#define  PIE_COMMON_ICE_ITR_WDMA2INTTEST_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_WDMA2INTTEST_MASK) >> PIE_COMMON_ICE_ITR_WDMA2INTTEST_SHIFT)
#define  PIE_COMMON_ICE_ITR_WDMA2INTTEST_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_WDMA2INTTEST_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_WDMA2INTTEST_SHIFT))

#define  PIE_COMMON_ICE_ITR_WDMA1INTTEST_MASK 0x400
#define  PIE_COMMON_ICE_ITR_WDMA1INTTEST_SHIFT 10
#define  PIE_COMMON_ICE_ITR_WDMA1INTTEST_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_WDMA1INTTEST_MASK) >> PIE_COMMON_ICE_ITR_WDMA1INTTEST_SHIFT)
#define  PIE_COMMON_ICE_ITR_WDMA1INTTEST_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_WDMA1INTTEST_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_WDMA1INTTEST_SHIFT))

#define  PIE_COMMON_ICE_ITR_WDMA0INTTEST_MASK 0x200
#define  PIE_COMMON_ICE_ITR_WDMA0INTTEST_SHIFT 9
#define  PIE_COMMON_ICE_ITR_WDMA0INTTEST_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_WDMA0INTTEST_MASK) >> PIE_COMMON_ICE_ITR_WDMA0INTTEST_SHIFT)
#define  PIE_COMMON_ICE_ITR_WDMA0INTTEST_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_WDMA0INTTEST_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_WDMA0INTTEST_SHIFT))

#define  PIE_COMMON_ICE_ITR_RDMACINTTEST_MASK 0x100
#define  PIE_COMMON_ICE_ITR_RDMACINTTEST_SHIFT 8
#define  PIE_COMMON_ICE_ITR_RDMACINTTEST_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_RDMACINTTEST_MASK) >> PIE_COMMON_ICE_ITR_RDMACINTTEST_SHIFT)
#define  PIE_COMMON_ICE_ITR_RDMACINTTEST_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_RDMACINTTEST_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_RDMACINTTEST_SHIFT))

#define  PIE_COMMON_ICE_ITR_RDMA5INTTEST_MASK 0x80
#define  PIE_COMMON_ICE_ITR_RDMA5INTTEST_SHIFT 7
#define  PIE_COMMON_ICE_ITR_RDMA5INTTEST_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_RDMA5INTTEST_MASK) >> PIE_COMMON_ICE_ITR_RDMA5INTTEST_SHIFT)
#define  PIE_COMMON_ICE_ITR_RDMA5INTTEST_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_RDMA5INTTEST_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_RDMA5INTTEST_SHIFT))

#define  PIE_COMMON_ICE_ITR_RDMA4INTTEST_MASK 0x40
#define  PIE_COMMON_ICE_ITR_RDMA4INTTEST_SHIFT 6
#define  PIE_COMMON_ICE_ITR_RDMA4INTTEST_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_RDMA4INTTEST_MASK) >> PIE_COMMON_ICE_ITR_RDMA4INTTEST_SHIFT)
#define  PIE_COMMON_ICE_ITR_RDMA4INTTEST_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_RDMA4INTTEST_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_RDMA4INTTEST_SHIFT))

#define  PIE_COMMON_ICE_ITR_RDMA3INTTEST_MASK 0x20
#define  PIE_COMMON_ICE_ITR_RDMA3INTTEST_SHIFT 5
#define  PIE_COMMON_ICE_ITR_RDMA3INTTEST_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_RDMA3INTTEST_MASK) >> PIE_COMMON_ICE_ITR_RDMA3INTTEST_SHIFT)
#define  PIE_COMMON_ICE_ITR_RDMA3INTTEST_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_RDMA3INTTEST_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_RDMA3INTTEST_SHIFT))

#define  PIE_COMMON_ICE_ITR_RDMA2INTTEST_MASK 0x10
#define  PIE_COMMON_ICE_ITR_RDMA2INTTEST_SHIFT 4
#define  PIE_COMMON_ICE_ITR_RDMA2INTTEST_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_RDMA2INTTEST_MASK) >> PIE_COMMON_ICE_ITR_RDMA2INTTEST_SHIFT)
#define  PIE_COMMON_ICE_ITR_RDMA2INTTEST_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_RDMA2INTTEST_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_RDMA2INTTEST_SHIFT))

#define  PIE_COMMON_ICE_ITR_RDMA1INTTEST_MASK 0x8
#define  PIE_COMMON_ICE_ITR_RDMA1INTTEST_SHIFT 3
#define  PIE_COMMON_ICE_ITR_RDMA1INTTEST_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_RDMA1INTTEST_MASK) >> PIE_COMMON_ICE_ITR_RDMA1INTTEST_SHIFT)
#define  PIE_COMMON_ICE_ITR_RDMA1INTTEST_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_RDMA1INTTEST_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_RDMA1INTTEST_SHIFT))

#define  PIE_COMMON_ICE_ITR_RDMA0INTTEST_MASK 0x4
#define  PIE_COMMON_ICE_ITR_RDMA0INTTEST_SHIFT 2
#define  PIE_COMMON_ICE_ITR_RDMA0INTTEST_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_RDMA0INTTEST_MASK) >> PIE_COMMON_ICE_ITR_RDMA0INTTEST_SHIFT)
#define  PIE_COMMON_ICE_ITR_RDMA0INTTEST_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_RDMA0INTTEST_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_RDMA0INTTEST_SHIFT))

#define  PIE_COMMON_ICE_ITR_RESERVED2_MASK 0x3
#define  PIE_COMMON_ICE_ITR_RESERVED2_SHIFT 0
#define  PIE_COMMON_ICE_ITR_RESERVED2_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_ITR_RESERVED2_MASK) >> PIE_COMMON_ICE_ITR_RESERVED2_SHIFT)
#define  PIE_COMMON_ICE_ITR_RESERVED2_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_ITR_RESERVED2_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_ITR_RESERVED2_SHIFT))

//====================================================================
//Register: Common Block Interface Register (CBIR)
/** \brief Common Block Interface Register*/
//====================================================================

#define  PIE_COMMON_ICE_CBIR_RESERVED1_MASK 0xfffffffe
#define  PIE_COMMON_ICE_CBIR_RESERVED1_SHIFT 1
#define  PIE_COMMON_ICE_CBIR_RESERVED1_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_CBIR_RESERVED1_MASK) >> PIE_COMMON_ICE_CBIR_RESERVED1_SHIFT)
#define  PIE_COMMON_ICE_CBIR_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_CBIR_RESERVED1_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_CBIR_RESERVED1_SHIFT))

#define  PIE_COMMON_ICE_CBIR_SOFTRESET_MASK 0x1
#define  PIE_COMMON_ICE_CBIR_SOFTRESET_SHIFT 0
#define  PIE_COMMON_ICE_CBIR_SOFTRESET_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_CBIR_SOFTRESET_MASK) >> PIE_COMMON_ICE_CBIR_SOFTRESET_SHIFT)
#define  PIE_COMMON_ICE_CBIR_SOFTRESET_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_CBIR_SOFTRESET_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_CBIR_SOFTRESET_SHIFT))

//====================================================================
//Register: Pipe Configuration Register (PipeConfig)
/** \brief This register is used to configure various aspects of the PIE pipeline.*/
//====================================================================

#define  PIE_COMMON_ICE_PIPECONFIG_RESERVED1_MASK 0xfffffff8
#define  PIE_COMMON_ICE_PIPECONFIG_RESERVED1_SHIFT 3
#define  PIE_COMMON_ICE_PIPECONFIG_RESERVED1_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_PIPECONFIG_RESERVED1_MASK) >> PIE_COMMON_ICE_PIPECONFIG_RESERVED1_SHIFT)
#define  PIE_COMMON_ICE_PIPECONFIG_RESERVED1_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_PIPECONFIG_RESERVED1_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_PIPECONFIG_RESERVED1_SHIFT))

#define  PIE_COMMON_ICE_PIPECONFIG_ANTICMODE_MASK 0x4
#define  PIE_COMMON_ICE_PIPECONFIG_ANTICMODE_SHIFT 2
#define  PIE_COMMON_ICE_PIPECONFIG_ANTICMODE_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_PIPECONFIG_ANTICMODE_MASK) >> PIE_COMMON_ICE_PIPECONFIG_ANTICMODE_SHIFT)
#define  PIE_COMMON_ICE_PIPECONFIG_ANTICMODE_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_PIPECONFIG_ANTICMODE_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_PIPECONFIG_ANTICMODE_SHIFT))

#define  PIE_COMMON_ICE_PIPECONFIG_SCALESEL_MASK 0x2
#define  PIE_COMMON_ICE_PIPECONFIG_SCALESEL_SHIFT 1
#define  PIE_COMMON_ICE_PIPECONFIG_SCALESEL_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_PIPECONFIG_SCALESEL_MASK) >> PIE_COMMON_ICE_PIPECONFIG_SCALESEL_SHIFT)
#define  PIE_COMMON_ICE_PIPECONFIG_SCALESEL_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_PIPECONFIG_SCALESEL_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_PIPECONFIG_SCALESEL_SHIFT))

#define  PIE_COMMON_ICE_PIPECONFIG_SCALESPACE_MASK 0x1
#define  PIE_COMMON_ICE_PIPECONFIG_SCALESPACE_SHIFT 0
#define  PIE_COMMON_ICE_PIPECONFIG_SCALESPACE_MASK_SHIFT(reg) (((reg) & PIE_COMMON_ICE_PIPECONFIG_SCALESPACE_MASK) >> PIE_COMMON_ICE_PIPECONFIG_SCALESPACE_SHIFT)
#define  PIE_COMMON_ICE_PIPECONFIG_SCALESPACE_REPLACE_VAL(reg,val) (((reg) & ~PIE_COMMON_ICE_PIPECONFIG_SCALESPACE_MASK) | (((uint32_t)val) << PIE_COMMON_ICE_PIPECONFIG_SCALESPACE_SHIFT))

#endif // PIE_COMMON_ICE
