 /*
 **************************************************************************************
 *
 * Copyright (c) 2010 Marvell International, Ltd.
 *
 **************************************************************************************
 *
 * Marvell Commercial License Option
 *
 * If you received this File from Marvell as part of a proprietary software release,
 * the File is considered Marvell Proprietary and Confidential Information, and is
 * licensed to you under the terms of the applicable Commercial License.
 *
 **************************************************************************************
 *
 * Marvell GPL License Option
 *
 * If you received this File from Marvell as part of a Linux distribution, this File
 * is licensed to you in accordance with the terms and conditions of the General Public
 * License Version 2, June 1991 (the "GPL License").  You can redistribute it and/or
 * modify it under the terms of the GPL License; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GPL License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this
 * program.  If not, see http://www.gnu.org/licenses/.
 *
 **************************************************************************************
 *
 * \file regAddrs.h
 * Generated using RegBuild 1.6.1
 *
 *************************************************************************
 */
#ifndef _X1P_LVDS2_REGADDRS_H_
#define _X1P_LVDS2_REGADDRS_H_

// APB_BASE Address
#define APB_BASE (0xF8000000)

// APB_CONFIG_BASE Address
#define APB_CONFIG_BASE ((APB_BASE) + 0x0)

// APB_DRO_BASE Address
#define APB_DRO_BASE ((APB_BASE) + 0x10000)

// APB_TMR_BASE Address
#define APB_TMR_BASE ((APB_BASE) + 0x20000)

// APB_TIMEBASE_BASE Address
#define APB_TIMEBASE_BASE ((APB_BASE) + 0x30000)

// APB_GPIOA_BASE Address
#define APB_GPIOA_BASE ((APB_BASE) + 0x40000)

// APB_GPIOB_BASE Address
#define APB_GPIOB_BASE ((APB_BASE) + 0x41000)

// APB_GPIOC_BASE Address
#define APB_GPIOC_BASE ((APB_BASE) + 0x42000)

// APB_GPIOD_BASE Address
#define APB_GPIOD_BASE ((APB_BASE) + 0x43000)

// APB_GPIOE_BASE Address
#define APB_GPIOE_BASE ((APB_BASE) + 0x44000)

// APB_GPIOF_BASE Address
#define APB_GPIOF_BASE ((APB_BASE) + 0x45000)

// APB_GPIOG_BASE Address
#define APB_GPIOG_BASE ((APB_BASE) + 0x46000)

// APB_GPIOH_BASE Address
#define APB_GPIOH_BASE ((APB_BASE) + 0x47000)

// APB_APB_SIC0_BASE Address
#define APB_APB_SIC0_BASE ((APB_BASE) + 0x50000)

// APB_APB_SIC1_BASE Address
#define APB_APB_SIC1_BASE ((APB_BASE) + 0x51000)

// APB_UART0_BASE Address
#define APB_UART0_BASE ((APB_BASE) + 0x60000)

// APB_UART1_BASE Address
#define APB_UART1_BASE ((APB_BASE) + 0x61000)

// APB_UART2_BASE Address
#define APB_UART2_BASE ((APB_BASE) + 0x62000)

// APB_UART3_BASE Address
#define APB_UART3_BASE ((APB_BASE) + 0x63000)

// APB_GPSPI0_BASE Address
#define APB_GPSPI0_BASE ((APB_BASE) + 0x70000)

// APB_GPSPI1_BASE Address
#define APB_GPSPI1_BASE ((APB_BASE) + 0x71000)

// APB_GPSPI2_BASE Address
#define APB_GPSPI2_BASE ((APB_BASE) + 0x72000)

// APB_SILABS_BASE Address
#define APB_SILABS_BASE ((APB_BASE) + 0x80000)

// APB_IEEE1284_BASE Address
#define APB_IEEE1284_BASE ((APB_BASE) + 0x90000)

// APB_I2C0_BASE Address
#define APB_I2C0_BASE ((APB_BASE) + 0xA0000)

// APB_I2C1_BASE Address
#define APB_I2C1_BASE ((APB_BASE) + 0xA1000)

// APB_I2C2_BASE Address
#define APB_I2C2_BASE ((APB_BASE) + 0xA2000)

// APB_I2C3_BASE Address
#define APB_I2C3_BASE ((APB_BASE) + 0xA3000)

// APB_I2S_BASE Address
#define APB_I2S_BASE ((APB_BASE) + 0xB0000)

// APB_AUDIO_BASE Address
#define APB_AUDIO_BASE ((APB_BASE) + 0xC0000)

// APB_EFUSE_BASE Address
#define APB_EFUSE_BASE ((APB_BASE) + 0xD0000)

// APB_CSSCG_BASE Address
#define APB_CSSCG_BASE ((APB_BASE) + 0xE0000)

// APB_TSEN_BASE Address
#define APB_TSEN_BASE ((APB_BASE) + 0xF0000)

// APB_RTC_BASE Address
#define APB_RTC_BASE ((APB_BASE) + 0x100000)

// APB_SW_BASE Address
#define APB_SW_BASE ((APB_BASE) + 0x110000)

// APB_ENGCTL_BASE Address
#define APB_ENGCTL_BASE ((APB_BASE) + 0x130000)

// APB_DCMOTOR6PIN0_BASE Address
#define APB_DCMOTOR6PIN0_BASE ((APB_BASE) + 0x140000)

// APB_DCMOTOR6PIN1_BASE Address
#define APB_DCMOTOR6PIN1_BASE ((APB_BASE) + 0x141000)

// APB_DCMOTOR6PIN2_BASE Address
#define APB_DCMOTOR6PIN2_BASE ((APB_BASE) + 0x142000)

// APB_DCMOTOR6PIN3_BASE Address
#define APB_DCMOTOR6PIN3_BASE ((APB_BASE) + 0x143000)

// APB_DCMOTOR4PIN_0_BASE Address
#define APB_DCMOTOR4PIN_0_BASE ((APB_BASE) + 0x144000)

// APB_DCMOTOR4PIN_1_BASE Address
#define APB_DCMOTOR4PIN_1_BASE ((APB_BASE) + 0x145000)

// APB_DCMOTOR4PIN_2_BASE Address
#define APB_DCMOTOR4PIN_2_BASE ((APB_BASE) + 0x146000)

// APB_STMOTOR6PIN0_BASE Address
#define APB_STMOTOR6PIN0_BASE ((APB_BASE) + 0x150000)

// APB_STMOTOR6PIN1_BASE Address
#define APB_STMOTOR6PIN1_BASE ((APB_BASE) + 0x151000)

// APB_STMOTOR6PIN2_BASE Address
#define APB_STMOTOR6PIN2_BASE ((APB_BASE) + 0x152000)

// APB_STMOTOR6PIN3_BASE Address
#define APB_STMOTOR6PIN3_BASE ((APB_BASE) + 0x153000)

// APB_STMOTOR4PIN0_BASE Address
#define APB_STMOTOR4PIN0_BASE ((APB_BASE) + 0x154000)

// APB_STMOTOR4PIN1_BASE Address
#define APB_STMOTOR4PIN1_BASE ((APB_BASE) + 0x155000)

// APB_OWI_BASE Address
#define APB_OWI_BASE ((APB_BASE) + 0x170000)

// APB_SCCP0_BASE Address
#define APB_SCCP0_BASE ((APB_BASE) + 0x180000)

// APB_SCCP1_BASE Address
#define APB_SCCP1_BASE ((APB_BASE) + 0x184000)

// LPT_BASE Address
#define LPT_BASE (0xF9E00000)

// BOOTSPI_BASE Address
#define BOOTSPI_BASE (0xF9010000)

// JBIG_BASE Address
#define JBIG_BASE (0xF9020000)

// JBIG_JBIG_CODEC_BASE Address
#define JBIG_JBIG_CODEC_BASE ((JBIG_BASE) + 0x0)

// JBIG_JBIG_CODEC_IDMA_BASE Address
#define JBIG_JBIG_CODEC_IDMA_BASE ((JBIG_JBIG_CODEC_BASE) + 0x1000)

// JBIG_JBIG_CODEC_ODMA_BASE Address
#define JBIG_JBIG_CODEC_ODMA_BASE ((JBIG_JBIG_CODEC_BASE) + 0x2000)

// JBIG_JBIG_DECODE_BASE Address
#define JBIG_JBIG_DECODE_BASE ((JBIG_BASE) + 0x3000)

// JBIG_JBIG_DECODE_IDMA_BASE Address
#define JBIG_JBIG_DECODE_IDMA_BASE ((JBIG_JBIG_DECODE_BASE) + 0x1000)

// JBIG_JBIG_DECODE_ODMA_BASE Address
#define JBIG_JBIG_DECODE_ODMA_BASE ((JBIG_JBIG_DECODE_BASE) + 0x2000)

// JEDI_BASE Address
#define JEDI_BASE (0xF9030000)

// JEDI_RDMA_BASE Address
#define JEDI_RDMA_BASE ((JEDI_BASE) + 0x0)

// JEDI_WDMA_BASE Address
#define JEDI_WDMA_BASE ((JEDI_BASE) + 0x1000)

// JEDI_CSC_BASE Address
#define JEDI_CSC_BASE ((JEDI_BASE) + 0x2000)

// JEDI_MCU_JPEG_BASE Address
#define JEDI_MCU_JPEG_BASE ((JEDI_BASE) + 0x3000)

// USB_BASE Address
#define USB_BASE (0xF9040000)

// USB_USB2D_BASE Address
#define USB_USB2D_BASE ((USB_BASE) + 0x0)

// USB_USB2H_BASE Address
#define USB_USB2H_BASE ((USB_BASE) + 0x1000)

// USB_USB2O_BASE Address
#define USB_USB2O_BASE ((USB_BASE) + 0x8000)

// USB_USB2PHY_BASE Address
#define USB_USB2PHY_BASE ((USB_BASE) + 0xF000)

// USB_USB2PHY_USB2_UTM_PLL_BASE Address
#define USB_USB2PHY_USB2_UTM_PLL_BASE ((USB_USB2PHY_BASE) + 0x0)

// USB_USB2PHY_USB2_UTM1_BASE Address
#define USB_USB2PHY_USB2_UTM1_BASE ((USB_USB2PHY_BASE) + 0x40)

// USB_USB2PHY_USB2_UTM2_BASE Address
#define USB_USB2PHY_USB2_UTM2_BASE ((USB_USB2PHY_BASE) + 0x80)

// USB_USB2PHY_USB2_UTM3_BASE Address
#define USB_USB2PHY_USB2_UTM3_BASE ((USB_USB2PHY_BASE) + 0xC0)

// LAN_BASE Address
#define LAN_BASE (0xF9050000)

// LAN_MAC_BASE Address
#define LAN_MAC_BASE ((LAN_BASE) + 0x0)

// LAN_MMC_BASE Address
#define LAN_MMC_BASE ((LAN_BASE) + 0x0)

// LAN_MAC_16PLUS_BASE Address
#define LAN_MAC_16PLUS_BASE ((LAN_BASE) + 0x0)

// LAN_MAD_BASE Address
#define LAN_MAD_BASE ((LAN_BASE) + 0x0)

// CDMA_BASE Address
#define CDMA_BASE (0xF9060000)

// CDMA_CDMA0_BASE Address
#define CDMA_CDMA0_BASE ((CDMA_BASE) + 0x0)

// CDMA_CDMA1_BASE Address
#define CDMA_CDMA1_BASE ((CDMA_BASE) + 0x1000)

// CDMA_CDMA2_BASE Address
#define CDMA_CDMA2_BASE ((CDMA_BASE) + 0x2000)

// CDMA_CDMA3_BASE Address
#define CDMA_CDMA3_BASE ((CDMA_BASE) + 0x3000)

// CDMA_CDMA4_BASE Address
#define CDMA_CDMA4_BASE ((CDMA_BASE) + 0x4000)

// CDMA_CDMA5_BASE Address
#define CDMA_CDMA5_BASE ((CDMA_BASE) + 0x5000)

// CDMA_CDMA6_BASE Address
#define CDMA_CDMA6_BASE ((CDMA_BASE) + 0x6000)

// CDMA_CDMA7_BASE Address
#define CDMA_CDMA7_BASE ((CDMA_BASE) + 0x7000)

// CDMA_CDMA8_BASE Address
#define CDMA_CDMA8_BASE ((CDMA_BASE) + 0x8000)

// CDMA_CDMA9_BASE Address
#define CDMA_CDMA9_BASE ((CDMA_BASE) + 0x9000)

// CDMA_CDMA10_BASE Address
#define CDMA_CDMA10_BASE ((CDMA_BASE) + 0xA000)

// CDMA_CDMA11_BASE Address
#define CDMA_CDMA11_BASE ((CDMA_BASE) + 0xB000)

// CDMA_CDMA_TOP_INT_BASE Address
#define CDMA_CDMA_TOP_INT_BASE ((CDMA_BASE) + 0xC000)

// LCD_BASE Address
#define LCD_BASE (0xF9070000)

// SD_BASE Address
#define SD_BASE (0xF9080000)

// DNAND_BASE Address
#define DNAND_BASE (0xF9082000)

// DNAND_NAND_BASE Address
#define DNAND_NAND_BASE ((DNAND_BASE) + 0x0)

// DNAND_CONF_BASE Address
#define DNAND_CONF_BASE ((DNAND_BASE) + 0x100)

// MVDO_BASE Address
#define MVDO_BASE (0xF9090000)

// MVDO_HIPS_BASE Address
#define MVDO_HIPS_BASE ((MVDO_BASE) + 0x0)

// MVDO_HVSYNC_BASE Address
#define MVDO_HVSYNC_BASE ((MVDO_BASE) + 0x1000)

// MVDO_MVDO_TOP_BASE Address
#define MVDO_MVDO_TOP_BASE ((MVDO_BASE) + 0x2000)

// MVDO_SVDO0_BASE Address
#define MVDO_SVDO0_BASE ((MVDO_BASE) + 0x3000)

// MVDO_SVDO1_BASE Address
#define MVDO_SVDO1_BASE ((MVDO_BASE) + 0x4000)

// MVDO_SVDO2_BASE Address
#define MVDO_SVDO2_BASE ((MVDO_BASE) + 0x5000)

// MVDO_SVDO3_BASE Address
#define MVDO_SVDO3_BASE ((MVDO_BASE) + 0x6000)

// MVDO_SVDO4_BASE Address
#define MVDO_SVDO4_BASE ((MVDO_BASE) + 0x7000)

// MVDO_SVDO5_BASE Address
#define MVDO_SVDO5_BASE ((MVDO_BASE) + 0x8000)

// MVDO_SVDO6_BASE Address
#define MVDO_SVDO6_BASE ((MVDO_BASE) + 0x9000)

// MVDO_SVDO7_BASE Address
#define MVDO_SVDO7_BASE ((MVDO_BASE) + 0xA000)

// MVDO_HIPWM0_BASE Address
#define MVDO_HIPWM0_BASE ((MVDO_BASE) + 0x3800)

// MVDO_HIPWM1_BASE Address
#define MVDO_HIPWM1_BASE ((MVDO_BASE) + 0x4800)

// MVDO_HIPWM2_BASE Address
#define MVDO_HIPWM2_BASE ((MVDO_BASE) + 0x5800)

// MVDO_HIPWM3_BASE Address
#define MVDO_HIPWM3_BASE ((MVDO_BASE) + 0x6800)

// MVDO_HIPWM4_BASE Address
#define MVDO_HIPWM4_BASE ((MVDO_BASE) + 0x7800)

// MVDO_HIPWM5_BASE Address
#define MVDO_HIPWM5_BASE ((MVDO_BASE) + 0x8800)

// MVDO_HIPWM6_BASE Address
#define MVDO_HIPWM6_BASE ((MVDO_BASE) + 0x9800)

// MVDO_HIPWM7_BASE Address
#define MVDO_HIPWM7_BASE ((MVDO_BASE) + 0xA800)

// ZX_BASE Address
#define ZX_BASE (0xF90A0000)

// VCF_BASE Address
#define VCF_BASE (0xF90B0000)

// VCF_CORE_BASE Address
#define VCF_CORE_BASE ((VCF_BASE) + 0x0)

// VCF_WRAPPER_BASE Address
#define VCF_WRAPPER_BASE ((VCF_BASE) + 0x1000)

// VCF_ROM_BASE Address
#define VCF_ROM_BASE ((VCF_BASE) + 0x4000)

// VCF_UPC_BASE Address, note only viewable from the dragonites
#define VCF_UPC_BASE 0xf920f000

// M2MTOP_BASE Address
#define M2MTOP_BASE (0xF90C0000)

// M2MTOP_M2M0_BASE Address
#define M2MTOP_M2M0_BASE ((M2MTOP_BASE) + 0x0)

// M2MTOP_M2M1_BASE Address
#define M2MTOP_M2M1_BASE ((M2MTOP_BASE) + 0x1000)

// ANTIC_BASE Address
#define ANTIC_BASE (0xF90D0000)

// ANTIC_ANTIC_BASE Address
#define ANTIC_ANTIC_BASE ((ANTIC_BASE) + 0x0)

// ANTIC_IDMA_AXI_ANTIC_BASE Address
#define ANTIC_IDMA_AXI_ANTIC_BASE ((ANTIC_BASE) + 0x1000)

// ANTIC_ODMA_AXI_ANTIC_BASE Address
#define ANTIC_ODMA_AXI_ANTIC_BASE ((ANTIC_BASE) + 0x2000)

// PIP_BASE Address
#define PIP_BASE (0xF9100000)

// PIP_PIP_BASE Address
#define PIP_PIP_BASE ((PIP_BASE) + 0x0)

// PIP_TP_BASE Address
#define PIP_TP_BASE ((PIP_BASE) + 0x3000)

// PIP_CP_BASE Address
#define PIP_CP_BASE ((PIP_BASE) + 0x2000)

// PIP_CR_BASE Address
#define PIP_CR_BASE ((PIP_BASE) + 0x8000)

// PIP_CSC_BASE Address
#define PIP_CSC_BASE ((PIP_BASE) + 0x4000)

// PIP_NGA_BASE Address
#define PIP_NGA_BASE ((PIP_BASE) + 0xA000)

// PIP_SC_CSC_BASE Address
#define PIP_SC_CSC_BASE ((PIP_BASE) + 0x10000)

// PIP_SERP_BASE Address
#define PIP_SERP_BASE ((PIP_BASE) + 0x11000)

// PIP_UED_BASE Address
#define PIP_UED_BASE ((PIP_BASE) + 0x40000)

// PIP_YIPI_BASE Address
#define PIP_YIPI_BASE ((PIP_BASE) + 0x39000)

// PIP_AUTO_HT_BASE Address
#define PIP_AUTO_HT_BASE ((PIP_BASE) + 0x3A000)

// PIP_KMOD_BASE Address
#define PIP_KMOD_BASE ((PIP_BASE) + 0x3C000)

// PIP_STAT_CDMA0_BASE Address
#define PIP_STAT_CDMA0_BASE ((PIP_BASE) + 0x53000)

// PIP_STAT_CDMA1_BASE Address
#define PIP_STAT_CDMA1_BASE ((PIP_BASE) + 0x54000)

// PIP_STAT_CDMA2_BASE Address
#define PIP_STAT_CDMA2_BASE ((PIP_BASE) + 0x55000)

// PIP_ODMA0_BASE Address
#define PIP_ODMA0_BASE ((PIP_BASE) + 0x5F000)

// PIP_ODMA1_BASE Address
#define PIP_ODMA1_BASE ((PIP_BASE) + 0x60000)

// PIP_ODMA2_BASE Address
#define PIP_ODMA2_BASE ((PIP_BASE) + 0x61000)

// PIP_ODMA3_BASE Address
#define PIP_ODMA3_BASE ((PIP_BASE) + 0x62000)

// PIP_ODMA4_BASE Address
#define PIP_ODMA4_BASE ((PIP_BASE) + 0x63000)

// PIP_ODMA5_BASE Address
#define PIP_ODMA5_BASE ((PIP_BASE) + 0x64000)

// PIP_ODMA6_BASE Address
#define PIP_ODMA6_BASE ((PIP_BASE) + 0x65000)

// PIP_ODMA7_BASE Address
#define PIP_ODMA7_BASE ((PIP_BASE) + 0x66000)

// PIP_PA_CDMA_BASE Address
#define PIP_PA_CDMA_BASE ((PIP_BASE) + 0xB000)

// PIP_PA_BASE Address
#define PIP_PA_BASE ((PIP_BASE) + 0xC000)

// PIP_PA_PA_ODMA_BASE Address
#define PIP_PA_PA_ODMA_BASE ((PIP_PA_BASE) + 0x2000)

// PIP_PA_PA_IDMA_BASE Address
#define PIP_PA_PA_IDMA_BASE ((PIP_PA_BASE) + 0x3000)

// PIP_DB_HT_BASE Address
#define PIP_DB_HT_BASE ((PIP_BASE) + 0x38000)

// PIP_DB_KMOD_BASE Address
#define PIP_DB_KMOD_BASE ((PIP_BASE) + 0x3D000)

// PIP_DB_SERP_BASE Address
#define PIP_DB_SERP_BASE ((PIP_BASE) + 0x12000)

// PIP_FHS_BASE Address
#define PIP_FHS_BASE ((PIP_BASE) + 0x1000)

// PIP_TH0_BASE Address
#define PIP_TH0_BASE ((PIP_BASE) + 0x18000)

// PIP_TH0_CORE_BASE Address
#define PIP_TH0_CORE_BASE ((PIP_TH0_BASE) + 0x0)

// PIP_TH0_SRAM_BASE Address
#define PIP_TH0_SRAM_BASE ((PIP_TH0_BASE) + 0x0)

// PIP_TH1_BASE Address
#define PIP_TH1_BASE ((PIP_BASE) + 0x20000)

// PIP_TH1_CORE_BASE Address
#define PIP_TH1_CORE_BASE ((PIP_TH1_BASE) + 0x0)

// PIP_TH1_SRAM_BASE Address
#define PIP_TH1_SRAM_BASE ((PIP_TH1_BASE) + 0x0)

// PIP_TH2_BASE Address
#define PIP_TH2_BASE ((PIP_BASE) + 0x28000)

// PIP_TH2_CORE_BASE Address
#define PIP_TH2_CORE_BASE ((PIP_TH2_BASE) + 0x0)

// PIP_TH2_SRAM_BASE Address
#define PIP_TH2_SRAM_BASE ((PIP_TH2_BASE) + 0x0)

// PIP_TH3_BASE Address
#define PIP_TH3_BASE ((PIP_BASE) + 0x30000)

// PIP_TH3_CORE_BASE Address
#define PIP_TH3_CORE_BASE ((PIP_TH3_BASE) + 0x0)

// PIP_TH3_SRAM_BASE Address
#define PIP_TH3_SRAM_BASE ((PIP_TH3_BASE) + 0x0)

// PIP_MIP_BASE Address
#define PIP_MIP_BASE ((PIP_BASE) + 0x9000)

// PIP_BLOOM_BASE Address
#define PIP_BLOOM_BASE ((PIP_BASE) + 0x3E000)

// PIP_CRE_BASE Address
#define PIP_CRE_BASE ((PIP_BASE) + 0x56000)

// PIP_LPC0_BASE Address
#define PIP_LPC0_BASE ((PIP_BASE) + 0x57000)

// PIP_LPC1_BASE Address
#define PIP_LPC1_BASE ((PIP_BASE) + 0x58000)

// PIP_LPC2_BASE Address
#define PIP_LPC2_BASE ((PIP_BASE) + 0x59000)

// PIP_LPC3_BASE Address
#define PIP_LPC3_BASE ((PIP_BASE) + 0x5A000)

// PIP_LPC_IDMA0_BASE Address
#define PIP_LPC_IDMA0_BASE ((PIP_BASE) + 0x5B000)

// PIP_LPC_IDMA1_BASE Address
#define PIP_LPC_IDMA1_BASE ((PIP_BASE) + 0x5C000)

// PIP_LPC_IDMA2_BASE Address
#define PIP_LPC_IDMA2_BASE ((PIP_BASE) + 0x5D000)

// PIP_LPC_IDMA3_BASE Address
#define PIP_LPC_IDMA3_BASE ((PIP_BASE) + 0x5E000)

// PIP_STATS_BASE Address
#define PIP_STATS_BASE ((PIP_BASE) + 0x52000)

// PIP_PLNR_BASE Address
#define PIP_PLNR_BASE ((PIP_BASE) + 0x67000)

// XENA_BASE Address
#define XENA_BASE (0xF9200000)

// XENA_XENA_BASE Address
#define XENA_XENA_BASE ((XENA_BASE) + 0x8000)

// DEC_BASE Address
#define DEC_BASE (0xF9300000)

// DEC_DEC_CONFIG_BASE Address
#define DEC_DEC_CONFIG_BASE ((DEC_BASE) + 0x0)

// DEC_SIC0_BASE Address
#define DEC_SIC0_BASE ((DEC_BASE) + 0x100)

// DEC_SIC1_BASE Address
#define DEC_SIC1_BASE ((DEC_BASE) + 0x200)

// DEC_DEC_FUSER_BASE Address
#define DEC_DEC_FUSER_BASE ((DEC_BASE) + 0x300)

// DEC_DEC_EXP_BASE Address
#define DEC_DEC_EXP_BASE ((DEC_BASE) + 0x400)

// DEC_DEC_TIMERS0_BASE Address
#define DEC_DEC_TIMERS0_BASE ((DEC_BASE) + 0x500)

// DEC_DEC_TIMERS1_BASE Address
#define DEC_DEC_TIMERS1_BASE ((DEC_BASE) + 0x540)

// DEC_DEC_GALVO_BASE Address
#define DEC_DEC_GALVO_BASE ((DEC_BASE) + 0x600)

// DEC_DEC_SENSOR_BASE Address
#define DEC_DEC_SENSOR_BASE ((DEC_BASE) + 0x1000)

// DEC_DEC_PWM_BASE Address
#define DEC_DEC_PWM_BASE ((DEC_BASE) + 0x4000)

// DEC_DEC_PWM_DPWM_REGS0_BASE Address
#define DEC_DEC_PWM_DPWM_REGS0_BASE ((DEC_DEC_PWM_BASE) + 0x100)

// DEC_DEC_PWM_DPWM_REGS1_BASE Address
#define DEC_DEC_PWM_DPWM_REGS1_BASE ((DEC_DEC_PWM_BASE) + 0x200)

// DEC_DEC_PWM_DPWM_REGS2_BASE Address
#define DEC_DEC_PWM_DPWM_REGS2_BASE ((DEC_DEC_PWM_BASE) + 0x300)

// DEC_DEC_PWM_DPWM_REGS3_BASE Address
#define DEC_DEC_PWM_DPWM_REGS3_BASE ((DEC_DEC_PWM_BASE) + 0x400)

// DEC_DEC_PWM_DPWM_REGS4_BASE Address
#define DEC_DEC_PWM_DPWM_REGS4_BASE ((DEC_DEC_PWM_BASE) + 0x500)

// DEC_DEC_PWM_DPWM_REGS5_BASE Address
#define DEC_DEC_PWM_DPWM_REGS5_BASE ((DEC_DEC_PWM_BASE) + 0x600)

// DEC_DEC_PWM_DPWM_REGS6_BASE Address
#define DEC_DEC_PWM_DPWM_REGS6_BASE ((DEC_DEC_PWM_BASE) + 0x700)

// DEC_DEC_PWM_DPWM_REGS7_BASE Address
#define DEC_DEC_PWM_DPWM_REGS7_BASE ((DEC_DEC_PWM_BASE) + 0x800)

// DEC_DEC_PWM_DPWM_REGS8_BASE Address
#define DEC_DEC_PWM_DPWM_REGS8_BASE ((DEC_DEC_PWM_BASE) + 0x900)

// DEC_DEC_PWM_DPWM_REGS9_BASE Address
#define DEC_DEC_PWM_DPWM_REGS9_BASE ((DEC_DEC_PWM_BASE) + 0xA00)

// DEC_DEC_PWM_DPWM_REGS10_BASE Address
#define DEC_DEC_PWM_DPWM_REGS10_BASE ((DEC_DEC_PWM_BASE) + 0xB00)

// DEC_DEC_PWM_DPWM_REGS11_BASE Address
#define DEC_DEC_PWM_DPWM_REGS11_BASE ((DEC_DEC_PWM_BASE) + 0xC00)

// DEC_DEC_PWM_DPWM_REGS12_BASE Address
#define DEC_DEC_PWM_DPWM_REGS12_BASE ((DEC_DEC_PWM_BASE) + 0xD00)

// DEC_DEC_PWM_DPWM_REGS13_BASE Address
#define DEC_DEC_PWM_DPWM_REGS13_BASE ((DEC_DEC_PWM_BASE) + 0xE00)

// DEC_DEC_PWM_DPWM_REGS14_BASE Address
#define DEC_DEC_PWM_DPWM_REGS14_BASE ((DEC_DEC_PWM_BASE) + 0xF00)

// DEC_DEC_PWM_DPWM_REGS15_BASE Address
#define DEC_DEC_PWM_DPWM_REGS15_BASE ((DEC_DEC_PWM_BASE) + 0x1000)

// DEC_DEC_PWM_DPWM_REGS16_BASE Address
#define DEC_DEC_PWM_DPWM_REGS16_BASE ((DEC_DEC_PWM_BASE) + 0x1100)

// DEC_DEC_PWM_DPWM_REGS17_BASE Address
#define DEC_DEC_PWM_DPWM_REGS17_BASE ((DEC_DEC_PWM_BASE) + 0x1200)

// DEC_DEC_PWM_DPWM_REGS18_BASE Address
#define DEC_DEC_PWM_DPWM_REGS18_BASE ((DEC_DEC_PWM_BASE) + 0x1300)

// DEC_DEC_PWM_DPWM_REGS19_BASE Address
#define DEC_DEC_PWM_DPWM_REGS19_BASE ((DEC_DEC_PWM_BASE) + 0x1400)

// DEC_DEC_PWM_DPWM_REGS20_BASE Address
#define DEC_DEC_PWM_DPWM_REGS20_BASE ((DEC_DEC_PWM_BASE) + 0x1500)

// DEC_DEC_PWM_DPWM_REGS21_BASE Address
#define DEC_DEC_PWM_DPWM_REGS21_BASE ((DEC_DEC_PWM_BASE) + 0x1600)

// DEC_DEC_PWM_DPWM_REGS22_BASE Address
#define DEC_DEC_PWM_DPWM_REGS22_BASE ((DEC_DEC_PWM_BASE) + 0x1700)

// DEC_DEC_PWM_DPWM_REGS23_BASE Address
#define DEC_DEC_PWM_DPWM_REGS23_BASE ((DEC_DEC_PWM_BASE) + 0x1800)

// DEC_DEC_PWM_DPWM_REGS24_BASE Address
#define DEC_DEC_PWM_DPWM_REGS24_BASE ((DEC_DEC_PWM_BASE) + 0x1900)

// DEC_DEC_PWM_DPWM_REGS25_BASE Address
#define DEC_DEC_PWM_DPWM_REGS25_BASE ((DEC_DEC_PWM_BASE) + 0x1A00)

// DEC_DEC_PWM_DPWM_REGS26_BASE Address
#define DEC_DEC_PWM_DPWM_REGS26_BASE ((DEC_DEC_PWM_BASE) + 0x1B00)

// DEC_DEC_PWM_DPWM_REGS27_BASE Address
#define DEC_DEC_PWM_DPWM_REGS27_BASE ((DEC_DEC_PWM_BASE) + 0x1C00)

// DEC_DEC_PWM_DPWM_REGS28_BASE Address
#define DEC_DEC_PWM_DPWM_REGS28_BASE ((DEC_DEC_PWM_BASE) + 0x1D00)

// DEC_DEC_PWM_DPWM_REGS29_BASE Address
#define DEC_DEC_PWM_DPWM_REGS29_BASE ((DEC_DEC_PWM_BASE) + 0x1E00)

// DEC_DEC_PWM_DPWM_REGS30_BASE Address
#define DEC_DEC_PWM_DPWM_REGS30_BASE ((DEC_DEC_PWM_BASE) + 0x1F00)

// DEC_DEC_PWM_DPWM_REGS31_BASE Address
#define DEC_DEC_PWM_DPWM_REGS31_BASE ((DEC_DEC_PWM_BASE) + 0x2000)

// DEC_DEC_CREG_BASE Address
#define DEC_DEC_CREG_BASE ((DEC_BASE) + 0x8000)

// DEC_DEC_TIMEBASE_BASE Address
#define DEC_DEC_TIMEBASE_BASE ((DEC_BASE) + 0x8100)

// DEC_WAVEGEN0_BASE Address
#define DEC_WAVEGEN0_BASE ((DEC_BASE) + 0x9000)

// DEC_WAVEGEN1_BASE Address
#define DEC_WAVEGEN1_BASE ((DEC_BASE) + 0x9100)

// DEC_WAVEGEN2_BASE Address
#define DEC_WAVEGEN2_BASE ((DEC_BASE) + 0x9200)

// DEC_WAVEGEN3_BASE Address
#define DEC_WAVEGEN3_BASE ((DEC_BASE) + 0x9300)

// DEC_ADC_REGS_BASE Address
#define DEC_ADC_REGS_BASE ((DEC_BASE) + 0xA000)

// DEC_DEC_LSCAN_BASE Address
#define DEC_DEC_LSCAN_BASE ((DEC_BASE) + 0xB000)

// DEC_DEC_LSCAN_HSYNC_BASE Address
#define DEC_DEC_LSCAN_HSYNC_BASE ((DEC_DEC_LSCAN_BASE) + 0x0)

// DEC_DEC_LSCAN_MIRROR0_BASE Address
#define DEC_DEC_LSCAN_MIRROR0_BASE ((DEC_DEC_LSCAN_BASE) + 0x100)

// DEC_DEC_LSCAN_MIRROR1_BASE Address
#define DEC_DEC_LSCAN_MIRROR1_BASE ((DEC_DEC_LSCAN_BASE) + 0x200)

// DEC_DEC_LSCAN_WFG0_BASE Address
#define DEC_DEC_LSCAN_WFG0_BASE ((DEC_DEC_LSCAN_BASE) + 0x300)

// DEC_DEC_LSCAN_WFG1_BASE Address
#define DEC_DEC_LSCAN_WFG1_BASE ((DEC_DEC_LSCAN_BASE) + 0x400)

// DEC_DEC_LSCAN_WFG2_BASE Address
#define DEC_DEC_LSCAN_WFG2_BASE ((DEC_DEC_LSCAN_BASE) + 0x500)

// DEC_DEC_LSCAN_WFG3_BASE Address
#define DEC_DEC_LSCAN_WFG3_BASE ((DEC_DEC_LSCAN_BASE) + 0x600)

// DEC_DEC_LSCAN_WFS_BASE Address
#define DEC_DEC_LSCAN_WFS_BASE ((DEC_DEC_LSCAN_BASE) + 0x800)

// ICE_BASE Address
#define ICE_BASE (0xF9400000)

// ICE_ICE_REGS_BASE Address
#define ICE_ICE_REGS_BASE ((ICE_BASE) + 0x0)

// ICE_ICE_REGS_TESTIDMA_BASE Address
#define ICE_ICE_REGS_TESTIDMA_BASE ((ICE_ICE_REGS_BASE) + 0x40)

// ICE_CISX_BASE Address
#define ICE_CISX_BASE ((ICE_BASE) + 0x10000)

// ICE_CISX_CISX0_BASE Address
#define ICE_CISX_CISX0_BASE ((ICE_CISX_BASE) + 0x0)

// ICE_CISX_CISX0_ODMA0_BASE Address
#define ICE_CISX_CISX0_ODMA0_BASE ((ICE_CISX_CISX0_BASE) + 0x0)

// ICE_CISX_CISX0_ODMA1_BASE Address
#define ICE_CISX_CISX0_ODMA1_BASE ((ICE_CISX_CISX0_BASE) + 0x1000)

// ICE_CISX_CISX0_ODMA2_BASE Address
#define ICE_CISX_CISX0_ODMA2_BASE ((ICE_CISX_CISX0_BASE) + 0x2000)

// ICE_CISX_CISX0_IDMA0_BASE Address
#define ICE_CISX_CISX0_IDMA0_BASE ((ICE_CISX_CISX0_BASE) + 0x3000)

// ICE_CISX_CISX0_IDMA1_BASE Address
#define ICE_CISX_CISX0_IDMA1_BASE ((ICE_CISX_CISX0_BASE) + 0x4000)

// ICE_CISX_CISX0_CISX_INT_BASE Address
#define ICE_CISX_CISX0_CISX_INT_BASE ((ICE_CISX_CISX0_BASE) + 0x5000)

// ICE_CISX_CISX1_BASE Address
#define ICE_CISX_CISX1_BASE ((ICE_CISX_BASE) + 0x8000)

// ICE_CISX_CISX1_ODMA0_BASE Address
#define ICE_CISX_CISX1_ODMA0_BASE ((ICE_CISX_CISX1_BASE) + 0x0)

// ICE_CISX_CISX1_ODMA1_BASE Address
#define ICE_CISX_CISX1_ODMA1_BASE ((ICE_CISX_CISX1_BASE) + 0x1000)

// ICE_CISX_CISX1_ODMA2_BASE Address
#define ICE_CISX_CISX1_ODMA2_BASE ((ICE_CISX_CISX1_BASE) + 0x2000)

// ICE_CISX_CISX1_IDMA0_BASE Address
#define ICE_CISX_CISX1_IDMA0_BASE ((ICE_CISX_CISX1_BASE) + 0x3000)

// ICE_CISX_CISX1_IDMA1_BASE Address
#define ICE_CISX_CISX1_IDMA1_BASE ((ICE_CISX_CISX1_BASE) + 0x4000)

// ICE_CISX_CISX1_CISX_INT_BASE Address
#define ICE_CISX_CISX1_CISX_INT_BASE ((ICE_CISX_CISX1_BASE) + 0x5000)

// ICE_SIZAR_BASE Address
#define ICE_SIZAR_BASE ((ICE_BASE) + 0x20000)

// ICE_SCAN_BASE Address
#define ICE_SCAN_BASE ((ICE_BASE) + 0x40000)

// ICE_SCAN_LVDSAFE_BASE Address
#define ICE_SCAN_LVDSAFE_BASE ((ICE_SCAN_BASE) + 0x300)

// ICE_SCAN_VCAP_BASE Address
#define ICE_SCAN_VCAP_BASE ((ICE_SCAN_BASE) + 0x200)

// ICE_PIC_BASE Address
#define ICE_PIC_BASE ((ICE_BASE) + 0x80000)

// ICE_PIC_PIC_INTCTRL_BASE Address
#define ICE_PIC_PIC_INTCTRL_BASE ((ICE_PIC_BASE) + 0x0)

// ICE_PIC_ADCNORM_BASE Address
#define ICE_PIC_ADCNORM_BASE ((ICE_PIC_BASE) + 0x1000)

// ICE_PIC_BULBMONLRMARGIN0_BASE Address
#define ICE_PIC_BULBMONLRMARGIN0_BASE ((ICE_PIC_BASE) + 0x2000)

// ICE_PIC_BULBMONLRMARGIN1_BASE Address
#define ICE_PIC_BULBMONLRMARGIN1_BASE ((ICE_PIC_BASE) + 0x3000)

// ICE_PIC_PRNUDSNU_BASE Address
#define ICE_PIC_PRNUDSNU_BASE ((ICE_PIC_BASE) + 0x8000)

// ICE_PIC_PRNUDSNU_PRNUDSNU_CORR0_BASE Address
#define ICE_PIC_PRNUDSNU_PRNUDSNU_CORR0_BASE ((ICE_PIC_PRNUDSNU_BASE) + 0x0)

// ICE_PIC_PRNUDSNU_PRNUDSNU_CORR1_BASE Address
#define ICE_PIC_PRNUDSNU_PRNUDSNU_CORR1_BASE ((ICE_PIC_PRNUDSNU_BASE) + 0x1000)

// ICE_PIC_PRNUDSNU_PNU2D_BASE Address
#define ICE_PIC_PRNUDSNU_PNU2D_BASE ((ICE_PIC_PRNUDSNU_BASE) + 0x2000)

// ICE_PIC_PRNUDSNU_IDMA_2D0_BASE Address
#define ICE_PIC_PRNUDSNU_IDMA_2D0_BASE ((ICE_PIC_PRNUDSNU_BASE) + 0x3000)

// ICE_PIC_PRNUDSNU_IDMA_2D1_BASE Address
#define ICE_PIC_PRNUDSNU_IDMA_2D1_BASE ((ICE_PIC_PRNUDSNU_BASE) + 0x4000)

// ICE_PIC_HFIR_BASE Address
#define ICE_PIC_HFIR_BASE ((ICE_PIC_BASE) + 0x4000)

// ICE_PIC_HSCALE_BASE Address
#define ICE_PIC_HSCALE_BASE ((ICE_PIC_BASE) + 0x5000)

// ICE_PIC_BITREDUCT_BASE Address
#define ICE_PIC_BITREDUCT_BASE ((ICE_PIC_BASE) + 0x6000)

// ICE_PIC_PIC_WDMA_BASE Address
#define ICE_PIC_PIC_WDMA_BASE ((ICE_PIC_BASE) + 0x10000)

// ICE_PIC_PIC_WDMA_DMA0_BASE Address
#define ICE_PIC_PIC_WDMA_DMA0_BASE ((ICE_PIC_PIC_WDMA_BASE) + 0x1000)

// ICE_PIC_PIC_WDMA_DMA1_BASE Address
#define ICE_PIC_PIC_WDMA_DMA1_BASE ((ICE_PIC_PIC_WDMA_BASE) + 0x2000)

// ICE_PIC_PIC_WDMA_DMA2_BASE Address
#define ICE_PIC_PIC_WDMA_DMA2_BASE ((ICE_PIC_PIC_WDMA_BASE) + 0x3000)

// ICE_PIC_PIC_WDMA_DMA3_BASE Address
#define ICE_PIC_PIC_WDMA_DMA3_BASE ((ICE_PIC_PIC_WDMA_BASE) + 0x4000)

// ICE_PIC_PIC_WDMA_DMA4_BASE Address
#define ICE_PIC_PIC_WDMA_DMA4_BASE ((ICE_PIC_PIC_WDMA_BASE) + 0x5000)

// ICE_PIC_PIC_WDMA_DMA5_BASE Address
#define ICE_PIC_PIC_WDMA_DMA5_BASE ((ICE_PIC_PIC_WDMA_BASE) + 0x6000)

// ICE_PIE_BASE Address
#define ICE_PIE_BASE ((ICE_BASE) + 0xC0000)

// ICE_PIE_PIE_COMMON_BASE Address
#define ICE_PIE_PIE_COMMON_BASE ((ICE_PIE_BASE) + 0x0)

// ICE_PIE_PIE_RDMA_BASE Address
#define ICE_PIE_PIE_RDMA_BASE ((ICE_PIE_BASE) + 0x4000)

// ICE_PIE_PIE_RDMA_PIE_RDMA0_BASE Address
#define ICE_PIE_PIE_RDMA_PIE_RDMA0_BASE ((ICE_PIE_PIE_RDMA_BASE) + 0x40)

// ICE_PIE_PIE_RDMA_PIE_RDMA1_BASE Address
#define ICE_PIE_PIE_RDMA_PIE_RDMA1_BASE ((ICE_PIE_PIE_RDMA_BASE) + 0x80)

// ICE_PIE_PIE_RDMA_PIE_RDMA2_BASE Address
#define ICE_PIE_PIE_RDMA_PIE_RDMA2_BASE ((ICE_PIE_PIE_RDMA_BASE) + 0xC0)

// ICE_PIE_PIE_RDMA_PIE_RDMA3_BASE Address
#define ICE_PIE_PIE_RDMA_PIE_RDMA3_BASE ((ICE_PIE_PIE_RDMA_BASE) + 0x100)

// ICE_PIE_PIE_RDMA_PIE_RDMA4_BASE Address
#define ICE_PIE_PIE_RDMA_PIE_RDMA4_BASE ((ICE_PIE_PIE_RDMA_BASE) + 0x140)

// ICE_PIE_PIE_RDMA_PIE_RDMA5_BASE Address
#define ICE_PIE_PIE_RDMA_PIE_RDMA5_BASE ((ICE_PIE_PIE_RDMA_BASE) + 0x180)

// ICE_PIE_BDENHANCE_BASE Address
#define ICE_PIE_BDENHANCE_BASE ((ICE_PIE_BASE) + 0x8000)

// ICE_PIE_RGB2ES_3L_BASE Address
#define ICE_PIE_RGB2ES_3L_BASE ((ICE_PIE_BASE) + 0xC000)

// ICE_PIE_ES2Y_BASE Address
#define ICE_PIE_ES2Y_BASE ((ICE_PIE_BASE) + 0x10000)

// ICE_PIE_NGADJUST_BASE Address
#define ICE_PIE_NGADJUST_BASE ((ICE_PIE_BASE) + 0x14000)

// ICE_PIE_TCNSENSE_BASE Address
#define ICE_PIE_TCNSENSE_BASE ((ICE_PIE_BASE) + 0x18000)

// ICE_PIE_MFILTER_BASE Address
#define ICE_PIE_MFILTER_BASE ((ICE_PIE_BASE) + 0x1C000)

// ICE_PIE_MFILTER_POGO_ALIGNER_BASE Address
#define ICE_PIE_MFILTER_POGO_ALIGNER_BASE ((ICE_PIE_MFILTER_BASE) + 0x0)

// ICE_PIE_MFILTER_SCULPTOR_BASE Address
#define ICE_PIE_MFILTER_SCULPTOR_BASE ((ICE_PIE_MFILTER_BASE) + 0x4000)

// ICE_PIE_Y2ES_BASE Address
#define ICE_PIE_Y2ES_BASE ((ICE_PIE_BASE) + 0x24000)

// ICE_PIE_XYSCALE_BASE Address
#define ICE_PIE_XYSCALE_BASE ((ICE_PIE_BASE) + 0x28000)

// ICE_PIE_XYCSCALE_BASE Address
#define ICE_PIE_XYCSCALE_BASE ((ICE_PIE_BASE) + 0x2C000)

// ICE_PIE_PIE_WDMA_BASE Address
#define ICE_PIE_PIE_WDMA_BASE ((ICE_PIE_BASE) + 0x30000)

// ICE_PIE_PIE_WDMA_PIE_WDMA0_BASE Address
#define ICE_PIE_PIE_WDMA_PIE_WDMA0_BASE ((ICE_PIE_PIE_WDMA_BASE) + 0x0)

// ICE_PIE_PIE_WDMA_PIE_WDMA1_BASE Address
#define ICE_PIE_PIE_WDMA_PIE_WDMA1_BASE ((ICE_PIE_PIE_WDMA_BASE) + 0x40)

// ICE_PIE_PIE_WDMA_PIE_WDMA2_BASE Address
#define ICE_PIE_PIE_WDMA_PIE_WDMA2_BASE ((ICE_PIE_PIE_WDMA_BASE) + 0x80)

// ICE_PIE_ISTONE_BASE Address
#define ICE_PIE_ISTONE_BASE ((ICE_PIE_BASE) + 0x34000)

// ICE_PIE_CSTATS_BASE Address
#define ICE_PIE_CSTATS_BASE ((ICE_PIE_BASE) + 0x38000)

// ASELA_BASE Address
#define ASELA_BASE (0xF9500000)

// ASELA_ASELA_BASE Address
#define ASELA_ASELA_BASE ((ASELA_BASE) + 0x0)

// ASELA_ODMA_BASE Address
#define ASELA_ODMA_BASE ((ASELA_BASE) + 0x300)

// ASELA_ASELA_SRAM_BASE Address
#define ASELA_ASELA_SRAM_BASE ((ASELA_BASE) + 0x10000)

// AGATE_BASE Address
#define AGATE_BASE (0xF9600000)

// AGATE_APB2_CFG_BASE Address
#define AGATE_APB2_CFG_BASE ((AGATE_BASE) + 0x0)

// AGATE_SAPTOP_BASE Address
#define AGATE_SAPTOP_BASE ((AGATE_BASE) + 0x1000)

// AGATE_SAPTOP_MDMA_BASE Address
#define AGATE_SAPTOP_MDMA_BASE ((AGATE_SAPTOP_BASE) + 0x0)

// AGATE_SAPTOP_SAP0_BASE Address
#define AGATE_SAPTOP_SAP0_BASE ((AGATE_SAPTOP_BASE) + 0x80)

// AGATE_SAPTOP_SAP1_BASE Address
#define AGATE_SAPTOP_SAP1_BASE ((AGATE_SAPTOP_BASE) + 0x100)

// AGATE_EI_BASE Address
#define AGATE_EI_BASE ((AGATE_BASE) + 0x2000)

// AGATE_SSCG_BASE Address
#define AGATE_SSCG_BASE ((AGATE_BASE) + 0x4000)

// AGATE_URPP_BASE Address
#define AGATE_URPP_BASE ((AGATE_BASE) + 0x5000)

// AGATE_IEEE1284_A_BASE Address
#define AGATE_IEEE1284_A_BASE ((AGATE_BASE) + 0x6000)

// AGATE_PEN_BASE Address
#define AGATE_PEN_BASE ((AGATE_BASE) + 0x7000)

// AGATE_SPU_BASE Address
#define AGATE_SPU_BASE ((AGATE_BASE) + 0x8000)

// LCM_BASE Address
#define LCM_BASE (0xFA000000)

// BUS_BASE Address
#define BUS_BASE (0xFA100000)

// BUS_ADR_BASE Address
#define BUS_ADR_BASE ((BUS_BASE) + 0x0)

// BUS_MC0_M_BASE Address
#define BUS_MC0_M_BASE ((BUS_BASE) + 0x2000)

// BUS_MC1_M_BASE Address
#define BUS_MC1_M_BASE ((BUS_BASE) + 0x3000)

// BUS_LCM_M_BASE Address
#define BUS_LCM_M_BASE ((BUS_BASE) + 0x5000)

// BUS_PCIE_M_BASE Address
#define BUS_PCIE_M_BASE ((BUS_BASE) + 0x6000)

// BUS_NAND_M_BASE Address
#define BUS_NAND_M_BASE ((BUS_BASE) + 0x7000)

// BUS_BOOTSPI_M_BASE Address
#define BUS_BOOTSPI_M_BASE ((BUS_BASE) + 0x8000)

// BUS_REG_M_BASE Address
#define BUS_REG_M_BASE ((BUS_BASE) + 0x9000)

// BUS_CPU_S_BASE Address
#define BUS_CPU_S_BASE ((BUS_BASE) + 0x42000)

// BUS_PCIE_S_BASE Address
#define BUS_PCIE_S_BASE ((BUS_BASE) + 0x43000)

// BUS_M2M_S_BASE Address
#define BUS_M2M_S_BASE ((BUS_BASE) + 0x44000)

// BUS_GLAN_S_BASE Address
#define BUS_GLAN_S_BASE ((BUS_BASE) + 0x45000)

// BUS_LCD_S_BASE Address
#define BUS_LCD_S_BASE ((BUS_BASE) + 0x46000)

// BUS_ASELA_S_BASE Address
#define BUS_ASELA_S_BASE ((BUS_BASE) + 0x47000)

// BUS_PIP_S_BASE Address
#define BUS_PIP_S_BASE ((BUS_BASE) + 0x48000)

// BUS_PIE_S_BASE Address
#define BUS_PIE_S_BASE ((BUS_BASE) + 0x49000)

// BUS_ANTIC_S_BASE Address
#define BUS_ANTIC_S_BASE ((BUS_BASE) + 0x4A000)

// BUS_CSAHB_S_BASE Address
#define BUS_CSAHB_S_BASE ((BUS_BASE) + 0x4B000)

// BUS_TIC_S_BASE Address
#define BUS_TIC_S_BASE ((BUS_BASE) + 0x4C000)

// BUS_JPEGR_S_BASE Address
#define BUS_JPEGR_S_BASE ((BUS_BASE) + 0x4D000)

// BUS_JPEGW_S_BASE Address
#define BUS_JPEGW_S_BASE ((BUS_BASE) + 0x4E000)

// BUS_JBIG_S_BASE Address
#define BUS_JBIG_S_BASE ((BUS_BASE) + 0x4F000)

// BUS_MVDO_S_BASE Address
#define BUS_MVDO_S_BASE ((BUS_BASE) + 0x50000)

// BUS_UPC_S_BASE Address
#define BUS_UPC_S_BASE ((BUS_BASE) + 0x51000)

// BUS_CDMA_S_BASE Address
#define BUS_CDMA_S_BASE ((BUS_BASE) + 0x52000)

// BUS_USB_S_BASE Address
#define BUS_USB_S_BASE ((BUS_BASE) + 0x53000)

// BUS_SDMMC_S_BASE Address
#define BUS_SDMMC_S_BASE ((BUS_BASE) + 0x54000)

// BUS_ZX_S_BASE Address
#define BUS_ZX_S_BASE ((BUS_BASE) + 0x55000)

// BUS_PIC_S_BASE Address
#define BUS_PIC_S_BASE ((BUS_BASE) + 0x56000)

// BUS_CISX_S_BASE Address
#define BUS_CISX_S_BASE ((BUS_BASE) + 0x57000)

// BUS_IB1_BASE Address
#define BUS_IB1_BASE ((BUS_BASE) + 0xC2000)

// PCIE_BASE Address
#define PCIE_BASE (0xFA200000)

// MC_BASE Address
#define MC_BASE (0xFA300000)

#define GIC_DIST_BASE 0xf8fe1000
#define GIC_CPU_BASE 0xf8fe0100

#define L2_REG_BASE 0xf8fef000

#define UPC_RAM_BASE 0xf9280000
#define UPC_RAM_SIZE 0x40000

#define BOOT_ROM_BASE 0xf9f00000


#endif // X1P_LVDS2
